/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_cmserr.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_cmserr.h2pas
     and this file regenerated. TaurusTLSHeaders_cmserr.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_cmserr;

interface

// Headers for OpenSSl 1.1.1
// cmserr.h


uses
  IdCTypes,
  IdGlobal
  {$IFDEF OPENSSL_STATIC_LINK_MODEL}
  , TaurusTLSConsts
  {$ENDIF};

const
  //
  // CMS function codes.
  //
  {$EXTERNALSYM CMS_F_CHECK_CONTENT}
  CMS_F_CHECK_CONTENT                             = 99;
  {$EXTERNALSYM CMS_F_CMS_ADD0_CERT}
  CMS_F_CMS_ADD0_CERT                             = 164;
  {$EXTERNALSYM CMS_F_CMS_ADD0_RECIPIENT_KEY}
  CMS_F_CMS_ADD0_RECIPIENT_KEY                    = 100;
  {$EXTERNALSYM CMS_F_CMS_ADD0_RECIPIENT_PASSWORD}
  CMS_F_CMS_ADD0_RECIPIENT_PASSWORD               = 165;
  {$EXTERNALSYM CMS_F_CMS_ADD1_RECEIPTREQUEST}
  CMS_F_CMS_ADD1_RECEIPTREQUEST                   = 158;
  {$EXTERNALSYM CMS_F_CMS_ADD1_RECIPIENT_CERT}
  CMS_F_CMS_ADD1_RECIPIENT_CERT                   = 101;
  {$EXTERNALSYM CMS_F_CMS_ADD1_SIGNER}
  CMS_F_CMS_ADD1_SIGNER                           = 102;
  {$EXTERNALSYM CMS_F_CMS_ADD1_SIGNINGTIME}
  CMS_F_CMS_ADD1_SIGNINGTIME                      = 103;
  {$EXTERNALSYM CMS_F_CMS_COMPRESS}
  CMS_F_CMS_COMPRESS                              = 104;
  {$EXTERNALSYM CMS_F_CMS_COMPRESSEDDATA_CREATE}
  CMS_F_CMS_COMPRESSEDDATA_CREATE                 = 105;
  {$EXTERNALSYM CMS_F_CMS_COMPRESSEDDATA_INIT_BIO}
  CMS_F_CMS_COMPRESSEDDATA_INIT_BIO               = 106;
  {$EXTERNALSYM CMS_F_CMS_COPY_CONTENT}
  CMS_F_CMS_COPY_CONTENT                          = 107;
  {$EXTERNALSYM CMS_F_CMS_COPY_MESSAGEDIGEST}
  CMS_F_CMS_COPY_MESSAGEDIGEST                    = 108;
  {$EXTERNALSYM CMS_F_CMS_DATA}
  CMS_F_CMS_DATA                                  = 109;
  {$EXTERNALSYM CMS_F_CMS_DATAFINAL}
  CMS_F_CMS_DATAFINAL                             = 110;
  {$EXTERNALSYM CMS_F_CMS_DATAINIT}
  CMS_F_CMS_DATAINIT                              = 111;
  {$EXTERNALSYM CMS_F_CMS_DECRYPT}
  CMS_F_CMS_DECRYPT                               = 112;
  {$EXTERNALSYM CMS_F_CMS_DECRYPT_SET1_KEY}
  CMS_F_CMS_DECRYPT_SET1_KEY                      = 113;
  {$EXTERNALSYM CMS_F_CMS_DECRYPT_SET1_PASSWORD}
  CMS_F_CMS_DECRYPT_SET1_PASSWORD                 = 166;
  {$EXTERNALSYM CMS_F_CMS_DECRYPT_SET1_PKEY}
  CMS_F_CMS_DECRYPT_SET1_PKEY                     = 114;
  {$EXTERNALSYM CMS_F_CMS_DIGESTALGORITHM_FIND_CTX}
  CMS_F_CMS_DIGESTALGORITHM_FIND_CTX              = 115;
  {$EXTERNALSYM CMS_F_CMS_DIGESTALGORITHM_INIT_BIO}
  CMS_F_CMS_DIGESTALGORITHM_INIT_BIO              = 116;
  {$EXTERNALSYM CMS_F_CMS_DIGESTEDDATA_DO_FINAL}
  CMS_F_CMS_DIGESTEDDATA_DO_FINAL                 = 117;
  {$EXTERNALSYM CMS_F_CMS_DIGEST_VERIFY}
  CMS_F_CMS_DIGEST_VERIFY                         = 118;
  {$EXTERNALSYM CMS_F_CMS_ENCODE_RECEIPT}
  CMS_F_CMS_ENCODE_RECEIPT                        = 161;
  {$EXTERNALSYM CMS_F_CMS_ENCRYPT}
  CMS_F_CMS_ENCRYPT                               = 119;
  {$EXTERNALSYM CMS_F_CMS_ENCRYPTEDCONTENT_INIT}
  CMS_F_CMS_ENCRYPTEDCONTENT_INIT                 = 179;
  {$EXTERNALSYM CMS_F_CMS_ENCRYPTEDCONTENT_INIT_BIO}
  CMS_F_CMS_ENCRYPTEDCONTENT_INIT_BIO             = 120;
  {$EXTERNALSYM CMS_F_CMS_ENCRYPTEDDATA_DECRYPT}
  CMS_F_CMS_ENCRYPTEDDATA_DECRYPT                 = 121;
  {$EXTERNALSYM CMS_F_CMS_ENCRYPTEDDATA_ENCRYPT}
  CMS_F_CMS_ENCRYPTEDDATA_ENCRYPT                 = 122;
  {$EXTERNALSYM CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY}
  CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY                = 123;
  {$EXTERNALSYM CMS_F_CMS_ENVELOPEDDATA_CREATE}
  CMS_F_CMS_ENVELOPEDDATA_CREATE                  = 124;
  {$EXTERNALSYM CMS_F_CMS_ENVELOPEDDATA_INIT_BIO}
  CMS_F_CMS_ENVELOPEDDATA_INIT_BIO                = 125;
  {$EXTERNALSYM CMS_F_CMS_ENVELOPED_DATA_INIT}
  CMS_F_CMS_ENVELOPED_DATA_INIT                   = 126;
  {$EXTERNALSYM CMS_F_CMS_ENV_ASN1_CTRL}
  CMS_F_CMS_ENV_ASN1_CTRL                         = 171;
  {$EXTERNALSYM CMS_F_CMS_FINAL}
  CMS_F_CMS_FINAL                                 = 127;
  {$EXTERNALSYM CMS_F_CMS_GET0_CERTIFICATE_CHOICES}
  CMS_F_CMS_GET0_CERTIFICATE_CHOICES              = 128;
  {$EXTERNALSYM CMS_F_CMS_GET0_CONTENT}
  CMS_F_CMS_GET0_CONTENT                          = 129;
  {$EXTERNALSYM CMS_F_CMS_GET0_ECONTENT_TYPE}
  CMS_F_CMS_GET0_ECONTENT_TYPE                    = 130;
  {$EXTERNALSYM CMS_F_CMS_GET0_ENVELOPED}
  CMS_F_CMS_GET0_ENVELOPED                        = 131;
  {$EXTERNALSYM CMS_F_CMS_GET0_REVOCATION_CHOICES}
  CMS_F_CMS_GET0_REVOCATION_CHOICES               = 132;
  {$EXTERNALSYM CMS_F_CMS_GET0_SIGNED}
  CMS_F_CMS_GET0_SIGNED                           = 133;
  {$EXTERNALSYM CMS_F_CMS_MSGSIGDIGEST_ADD1}
  CMS_F_CMS_MSGSIGDIGEST_ADD1                     = 162;
  {$EXTERNALSYM CMS_F_CMS_RECEIPTREQUEST_CREATE0}
  CMS_F_CMS_RECEIPTREQUEST_CREATE0                = 159;
  {$EXTERNALSYM CMS_F_CMS_RECEIPT_VERIFY}
  CMS_F_CMS_RECEIPT_VERIFY                        = 160;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_DECRYPT}
  CMS_F_CMS_RECIPIENTINFO_DECRYPT                 = 134;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_ENCRYPT}
  CMS_F_CMS_RECIPIENTINFO_ENCRYPT                 = 169;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT}
  CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT            = 178;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG}
  CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG           = 175;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID}
  CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID       = 173;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS}
  CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS          = 172;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KARI_ORIG_ID_CMP}
  CMS_F_CMS_RECIPIENTINFO_KARI_ORIG_ID_CMP        = 174;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KEKRI_DECRYPT}
  CMS_F_CMS_RECIPIENTINFO_KEKRI_DECRYPT           = 135;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KEKRI_ENCRYPT}
  CMS_F_CMS_RECIPIENTINFO_KEKRI_ENCRYPT           = 136;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID}
  CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID           = 137;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP}
  CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP            = 138;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KTRI_CERT_CMP}
  CMS_F_CMS_RECIPIENTINFO_KTRI_CERT_CMP           = 139;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KTRI_DECRYPT}
  CMS_F_CMS_RECIPIENTINFO_KTRI_DECRYPT            = 140;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KTRI_ENCRYPT}
  CMS_F_CMS_RECIPIENTINFO_KTRI_ENCRYPT            = 141;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS}
  CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS          = 142;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID}
  CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID     = 143;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT}
  CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT              = 167;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_SET0_KEY}
  CMS_F_CMS_RECIPIENTINFO_SET0_KEY                = 144;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD}
  CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD           = 168;
  {$EXTERNALSYM CMS_F_CMS_RECIPIENTINFO_SET0_PKEY}
  CMS_F_CMS_RECIPIENTINFO_SET0_PKEY               = 145;
  {$EXTERNALSYM CMS_F_CMS_SD_ASN1_CTRL}
  CMS_F_CMS_SD_ASN1_CTRL                          = 170;
  {$EXTERNALSYM CMS_F_CMS_SET1_IAS}
  CMS_F_CMS_SET1_IAS                              = 176;
  {$EXTERNALSYM CMS_F_CMS_SET1_KEYID}
  CMS_F_CMS_SET1_KEYID                            = 177;
  {$EXTERNALSYM CMS_F_CMS_SET1_SIGNERIDENTIFIER}
  CMS_F_CMS_SET1_SIGNERIDENTIFIER                 = 146;
  {$EXTERNALSYM CMS_F_CMS_SET_DETACHED}
  CMS_F_CMS_SET_DETACHED                          = 147;
  {$EXTERNALSYM CMS_F_CMS_SIGN}
  CMS_F_CMS_SIGN                                  = 148;
  {$EXTERNALSYM CMS_F_CMS_SIGNED_DATA_INIT}
  CMS_F_CMS_SIGNED_DATA_INIT                      = 149;
  {$EXTERNALSYM CMS_F_CMS_SIGNERINFO_CONTENT_SIGN}
  CMS_F_CMS_SIGNERINFO_CONTENT_SIGN               = 150;
  {$EXTERNALSYM CMS_F_CMS_SIGNERINFO_SIGN}
  CMS_F_CMS_SIGNERINFO_SIGN                       = 151;
  {$EXTERNALSYM CMS_F_CMS_SIGNERINFO_VERIFY}
  CMS_F_CMS_SIGNERINFO_VERIFY                     = 152;
  {$EXTERNALSYM CMS_F_CMS_SIGNERINFO_VERIFY_CERT}
  CMS_F_CMS_SIGNERINFO_VERIFY_CERT                = 153;
  {$EXTERNALSYM CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT}
  CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT             = 154;
  {$EXTERNALSYM CMS_F_CMS_SIGN_RECEIPT}
  CMS_F_CMS_SIGN_RECEIPT                          = 163;
  {$EXTERNALSYM CMS_F_CMS_SI_CHECK_ATTRIBUTES}
  CMS_F_CMS_SI_CHECK_ATTRIBUTES                   = 183;
  {$EXTERNALSYM CMS_F_CMS_STREAM}
  CMS_F_CMS_STREAM                                = 155;
  {$EXTERNALSYM CMS_F_CMS_UNCOMPRESS}
  CMS_F_CMS_UNCOMPRESS                            = 156;
  {$EXTERNALSYM CMS_F_CMS_VERIFY}
  CMS_F_CMS_VERIFY                                = 157;
  {$EXTERNALSYM CMS_F_KEK_UNWRAP_KEY}
  CMS_F_KEK_UNWRAP_KEY                            = 180;

  //
  // CMS reason codes.
  //
  {$EXTERNALSYM CMS_R_ADD_SIGNER_ERROR}
  CMS_R_ADD_SIGNER_ERROR                          = 99;
  {$EXTERNALSYM CMS_R_ATTRIBUTE_ERROR}
  CMS_R_ATTRIBUTE_ERROR                           = 161;
  {$EXTERNALSYM CMS_R_CERTIFICATE_ALREADY_PRESENT}
  CMS_R_CERTIFICATE_ALREADY_PRESENT               = 175;
  {$EXTERNALSYM CMS_R_CERTIFICATE_HAS_NO_KEYID}
  CMS_R_CERTIFICATE_HAS_NO_KEYID                  = 160;
  {$EXTERNALSYM CMS_R_CERTIFICATE_VERIFY_ERROR}
  CMS_R_CERTIFICATE_VERIFY_ERROR                  = 100;
  {$EXTERNALSYM CMS_R_CIPHER_INITIALISATION_ERROR}
  CMS_R_CIPHER_INITIALISATION_ERROR               = 101;
  {$EXTERNALSYM CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR}
  CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR     = 102;
  {$EXTERNALSYM CMS_R_CMS_DATAFINAL_ERROR}
  CMS_R_CMS_DATAFINAL_ERROR                       = 103;
  {$EXTERNALSYM CMS_R_CMS_LIB}
  CMS_R_CMS_LIB                                   = 104;
  {$EXTERNALSYM CMS_R_CONTENTIDENTIFIER_MISMATCH}
  CMS_R_CONTENTIDENTIFIER_MISMATCH                = 170;
  {$EXTERNALSYM CMS_R_CONTENT_NOT_FOUND}
  CMS_R_CONTENT_NOT_FOUND                         = 105;
  {$EXTERNALSYM CMS_R_CONTENT_TYPE_MISMATCH}
  CMS_R_CONTENT_TYPE_MISMATCH                     = 171;
  {$EXTERNALSYM CMS_R_CONTENT_TYPE_NOT_COMPRESSED_DATA}
  CMS_R_CONTENT_TYPE_NOT_COMPRESSED_DATA          = 106;
  {$EXTERNALSYM CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA}
  CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA           = 107;
  {$EXTERNALSYM CMS_R_CONTENT_TYPE_NOT_SIGNED_DATA}
  CMS_R_CONTENT_TYPE_NOT_SIGNED_DATA              = 108;
  {$EXTERNALSYM CMS_R_CONTENT_VERIFY_ERROR}
  CMS_R_CONTENT_VERIFY_ERROR                      = 109;
  {$EXTERNALSYM CMS_R_CTRL_ERROR}
  CMS_R_CTRL_ERROR                                = 110;
  {$EXTERNALSYM CMS_R_CTRL_FAILURE}
  CMS_R_CTRL_FAILURE                              = 111;
  {$EXTERNALSYM CMS_R_DECRYPT_ERROR}
  CMS_R_DECRYPT_ERROR                             = 112;
  {$EXTERNALSYM CMS_R_ERROR_GETTING_PUBLIC_KEY}
  CMS_R_ERROR_GETTING_PUBLIC_KEY                  = 113;
  {$EXTERNALSYM CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE}
  CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE     = 114;
  {$EXTERNALSYM CMS_R_ERROR_SETTING_KEY}
  CMS_R_ERROR_SETTING_KEY                         = 115;
  {$EXTERNALSYM CMS_R_ERROR_SETTING_RECIPIENTINFO}
  CMS_R_ERROR_SETTING_RECIPIENTINFO               = 116;
  {$EXTERNALSYM CMS_R_INVALID_ENCRYPTED_KEY_LENGTH}
  CMS_R_INVALID_ENCRYPTED_KEY_LENGTH              = 117;
  {$EXTERNALSYM CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER}
  CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER          = 176;
  {$EXTERNALSYM CMS_R_INVALID_KEY_LENGTH}
  CMS_R_INVALID_KEY_LENGTH                        = 118;
  {$EXTERNALSYM CMS_R_MD_BIO_INIT_ERROR}
  CMS_R_MD_BIO_INIT_ERROR                         = 119;
  {$EXTERNALSYM CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH}
  CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH      = 120;
  {$EXTERNALSYM CMS_R_MESSAGEDIGEST_WRONG_LENGTH}
  CMS_R_MESSAGEDIGEST_WRONG_LENGTH                = 121;
  {$EXTERNALSYM CMS_R_MSGSIGDIGEST_ERROR}
  CMS_R_MSGSIGDIGEST_ERROR                        = 172;
  {$EXTERNALSYM CMS_R_MSGSIGDIGEST_VERIFICATION_FAILURE}
  CMS_R_MSGSIGDIGEST_VERIFICATION_FAILURE         = 162;
  {$EXTERNALSYM CMS_R_MSGSIGDIGEST_WRONG_LENGTH}
  CMS_R_MSGSIGDIGEST_WRONG_LENGTH                 = 163;
  {$EXTERNALSYM CMS_R_NEED_ONE_SIGNER}
  CMS_R_NEED_ONE_SIGNER                           = 164;
  {$EXTERNALSYM CMS_R_NOT_A_SIGNED_RECEIPT}
  CMS_R_NOT_A_SIGNED_RECEIPT                      = 165;
  {$EXTERNALSYM CMS_R_NOT_ENCRYPTED_DATA}
  CMS_R_NOT_ENCRYPTED_DATA                        = 122;
  {$EXTERNALSYM CMS_R_NOT_KEK}
  CMS_R_NOT_KEK                                   = 123;
  {$EXTERNALSYM CMS_R_NOT_KEY_AGREEMENT}
  CMS_R_NOT_KEY_AGREEMENT                         = 181;
  {$EXTERNALSYM CMS_R_NOT_KEY_TRANSPORT}
  CMS_R_NOT_KEY_TRANSPORT                         = 124;
  {$EXTERNALSYM CMS_R_NOT_PWRI}
  CMS_R_NOT_PWRI                                  = 177;
  {$EXTERNALSYM CMS_R_NOT_SUPPORTED_FOR_THIS_KEY_TYPE}
  CMS_R_NOT_SUPPORTED_FOR_THIS_KEY_TYPE           = 125;
  {$EXTERNALSYM CMS_R_NO_CIPHER}
  CMS_R_NO_CIPHER                                 = 126;
  {$EXTERNALSYM CMS_R_NO_CONTENT}
  CMS_R_NO_CONTENT                                = 127;
  {$EXTERNALSYM CMS_R_NO_CONTENT_TYPE}
  CMS_R_NO_CONTENT_TYPE                           = 173;
  {$EXTERNALSYM CMS_R_NO_DEFAULT_DIGEST}
  CMS_R_NO_DEFAULT_DIGEST                         = 128;
  {$EXTERNALSYM CMS_R_NO_DIGEST_SET}
  CMS_R_NO_DIGEST_SET                             = 129;
  {$EXTERNALSYM CMS_R_NO_KEY}
  CMS_R_NO_KEY                                    = 130;
  {$EXTERNALSYM CMS_R_NO_KEY_OR_CERT}
  CMS_R_NO_KEY_OR_CERT                            = 174;
  {$EXTERNALSYM CMS_R_NO_MATCHING_DIGEST}
  CMS_R_NO_MATCHING_DIGEST                        = 131;
  {$EXTERNALSYM CMS_R_NO_MATCHING_RECIPIENT}
  CMS_R_NO_MATCHING_RECIPIENT                     = 132;
  {$EXTERNALSYM CMS_R_NO_MATCHING_SIGNATURE}
  CMS_R_NO_MATCHING_SIGNATURE                     = 166;
  {$EXTERNALSYM CMS_R_NO_MSGSIGDIGEST}
  CMS_R_NO_MSGSIGDIGEST                           = 167;
  {$EXTERNALSYM CMS_R_NO_PASSWORD}
  CMS_R_NO_PASSWORD                               = 178;
  {$EXTERNALSYM CMS_R_NO_PRIVATE_KEY}
  CMS_R_NO_PRIVATE_KEY                            = 133;
  {$EXTERNALSYM CMS_R_NO_PUBLIC_KEY}
  CMS_R_NO_PUBLIC_KEY                             = 134;
  {$EXTERNALSYM CMS_R_NO_RECEIPT_REQUEST}
  CMS_R_NO_RECEIPT_REQUEST                        = 168;
  {$EXTERNALSYM CMS_R_NO_SIGNERS}
  CMS_R_NO_SIGNERS                                = 135;
  {$EXTERNALSYM CMS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE}
  CMS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE    = 136;
  {$EXTERNALSYM CMS_R_RECEIPT_DECODE_ERROR}
  CMS_R_RECEIPT_DECODE_ERROR                      = 169;
  {$EXTERNALSYM CMS_R_RECIPIENT_ERROR}
  CMS_R_RECIPIENT_ERROR                           = 137;
  {$EXTERNALSYM CMS_R_SIGNER_CERTIFICATE_NOT_FOUND}
  CMS_R_SIGNER_CERTIFICATE_NOT_FOUND              = 138;
  {$EXTERNALSYM CMS_R_SIGNFINAL_ERROR}
  CMS_R_SIGNFINAL_ERROR                           = 139;
  {$EXTERNALSYM CMS_R_SMIME_TEXT_ERROR}
  CMS_R_SMIME_TEXT_ERROR                          = 140;
  {$EXTERNALSYM CMS_R_STORE_INIT_ERROR}
  CMS_R_STORE_INIT_ERROR                          = 141;
  {$EXTERNALSYM CMS_R_TYPE_NOT_COMPRESSED_DATA}
  CMS_R_TYPE_NOT_COMPRESSED_DATA                  = 142;
  {$EXTERNALSYM CMS_R_TYPE_NOT_DATA}
  CMS_R_TYPE_NOT_DATA                             = 143;
  {$EXTERNALSYM CMS_R_TYPE_NOT_DIGESTED_DATA}
  CMS_R_TYPE_NOT_DIGESTED_DATA                    = 144;
  {$EXTERNALSYM CMS_R_TYPE_NOT_ENCRYPTED_DATA}
  CMS_R_TYPE_NOT_ENCRYPTED_DATA                   = 145;
  {$EXTERNALSYM CMS_R_TYPE_NOT_ENVELOPED_DATA}
  CMS_R_TYPE_NOT_ENVELOPED_DATA                   = 146;
  {$EXTERNALSYM CMS_R_UNABLE_TO_FINALIZE_CONTEXT}
  CMS_R_UNABLE_TO_FINALIZE_CONTEXT                = 147;
  {$EXTERNALSYM CMS_R_UNKNOWN_CIPHER}
  CMS_R_UNKNOWN_CIPHER                            = 148;
  {$EXTERNALSYM CMS_R_UNKNOWN_DIGEST_ALGORITHM}
  CMS_R_UNKNOWN_DIGEST_ALGORITHM                  = 149;
  {$EXTERNALSYM CMS_R_UNKNOWN_ID}
  CMS_R_UNKNOWN_ID                                = 150;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM}
  CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM         = 151;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_CONTENT_TYPE}
  CMS_R_UNSUPPORTED_CONTENT_TYPE                  = 152;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_KEK_ALGORITHM}
  CMS_R_UNSUPPORTED_KEK_ALGORITHM                 = 153;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM}
  CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM      = 179;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_RECIPIENTINFO_TYPE}
  CMS_R_UNSUPPORTED_RECIPIENTINFO_TYPE            = 155;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_RECIPIENT_TYPE}
  CMS_R_UNSUPPORTED_RECIPIENT_TYPE                = 154;
  {$EXTERNALSYM CMS_R_UNSUPPORTED_TYPE}
  CMS_R_UNSUPPORTED_TYPE                          = 156;
  {$EXTERNALSYM CMS_R_UNWRAP_ERROR}
  CMS_R_UNWRAP_ERROR                              = 157;
  {$EXTERNALSYM CMS_R_UNWRAP_FAILURE}
  CMS_R_UNWRAP_FAILURE                            = 180;
  {$EXTERNALSYM CMS_R_VERIFICATION_FAILURE}
  CMS_R_VERIFICATION_FAILURE                      = 158;
  {$EXTERNALSYM CMS_R_WRAP_ERROR}
  CMS_R_WRAP_ERROR                                = 159;

    { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:
		
  	  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header 
	  files generated for C++. }
	  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
var
  ERR_load_CMS_strings: function : TIdC_INT; cdecl = nil;

{$ELSE}
  function ERR_load_CMS_strings: TIdC_INT cdecl; external CLibCrypto;

{$ENDIF}

implementation

  uses
    classes, 
    TaurusTLSExceptionHandlers
  {$IFNDEF OPENSSL_STATIC_LINK_MODEL}
    ,TaurusTLSLoader
  {$ENDIF};
  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
const
  ERR_load_CMS_strings_procname = 'ERR_load_CMS_strings';

  {$IFNDEF _FIXINSIGHT_}
  {$I TaurusTLSNoRetValOff.inc} 
function  ERR_ERR_load_CMS_strings: TIdC_INT; cdecl;
begin
  ETaurusTLSAPIFunctionNotPresent.RaiseException(ERR_load_CMS_strings_procname);
end;



  {$I TaurusTLSNoRetValOn.inc} 
  {$I TaurusTLSUnusedParamOff.inc}
procedure Load(const ADllHandle: TIdLibHandle; LibVersion: TIdC_UINT; const AFailed: TStringList);

var FuncLoadError: boolean;

begin
  ERR_load_CMS_strings := LoadLibFunction(ADllHandle, ERR_load_CMS_strings_procname);
  FuncLoadError := not assigned(ERR_load_CMS_strings);
  if FuncLoadError then
  begin
    {$if not defined(ERR_load_CMS_strings_allownil)}
    ERR_load_CMS_strings := ERR_ERR_load_CMS_strings;
    {$ifend}
    {$if declared(ERR_load_CMS_strings_introduced)}
    if LibVersion < ERR_load_CMS_strings_introduced then
    begin
      {$if declared(FC_ERR_load_CMS_strings)}
      ERR_load_CMS_strings := FC_ERR_load_CMS_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if declared(ERR_load_CMS_strings_removed)}
    if ERR_load_CMS_strings_removed <= LibVersion then
    begin
      {$if declared(_ERR_load_CMS_strings)}
      ERR_load_CMS_strings := _ERR_load_CMS_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if not defined(ERR_load_CMS_strings_allownil)}
    if FuncLoadError then
      AFailed.Add('ERR_load_CMS_strings');
    {$ifend}
  end;
end;
  {$I TaurusTLSUnusedParamOn.inc}

procedure Unload;
begin
  ERR_load_CMS_strings := nil;
end;
  {$ENDIF}
{$ENDIF}

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
initialization
  Register_SSLLoader(Load,'LibCrypto');
  Register_SSLUnloader(Unload);
{$ENDIF}
end.
