/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_sslerr.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_sslerr.h2pas
     and this file regenerated. TaurusTLSHeaders_sslerr.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_sslerr;

interface

// Headers for OpenSSL 1.1.1
// sslerr.h


uses
  IdCTypes,
  IdGlobal
  {$IFDEF OPENSSL_STATIC_LINK_MODEL}
  , TaurusTLSConsts
  {$ENDIF};

(*
 * SSL function codes.
 *)
const
  {$EXTERNALSYM SSL_F_ADD_CLIENT_KEY_SHARE_EXT}
  SSL_F_ADD_CLIENT_KEY_SHARE_EXT = 438;
  {$EXTERNALSYM SSL_F_ADD_KEY_SHARE}
  SSL_F_ADD_KEY_SHARE = 512;
  {$EXTERNALSYM SSL_F_BYTES_TO_CIPHER_LIST}
  SSL_F_BYTES_TO_CIPHER_LIST = 519;
  {$EXTERNALSYM SSL_F_CHECK_SUITEB_CIPHER_LIST}
  SSL_F_CHECK_SUITEB_CIPHER_LIST = 331;
  {$EXTERNALSYM SSL_F_CIPHERSUITE_CB}
  SSL_F_CIPHERSUITE_CB = 622;
  {$EXTERNALSYM SSL_F_CONSTRUCT_CA_NAMES}
  SSL_F_CONSTRUCT_CA_NAMES = 552;
  {$EXTERNALSYM SSL_F_CONSTRUCT_KEY_EXCHANGE_TBS}
  SSL_F_CONSTRUCT_KEY_EXCHANGE_TBS = 553;
  {$EXTERNALSYM SSL_F_CONSTRUCT_STATEFUL_TICKET}
  SSL_F_CONSTRUCT_STATEFUL_TICKET = 636;
  {$EXTERNALSYM SSL_F_CONSTRUCT_STATELESS_TICKET}
  SSL_F_CONSTRUCT_STATELESS_TICKET = 637;
  {$EXTERNALSYM SSL_F_CREATE_SYNTHETIC_MESSAGE_HASH}
  SSL_F_CREATE_SYNTHETIC_MESSAGE_HASH = 539;
  {$EXTERNALSYM SSL_F_CREATE_TICKET_PREQUEL}
  SSL_F_CREATE_TICKET_PREQUEL = 638;
  {$EXTERNALSYM SSL_F_CT_MOVE_SCTS}
  SSL_F_CT_MOVE_SCTS = 345;
  {$EXTERNALSYM SSL_F_CT_STRICT}
  SSL_F_CT_STRICT = 349;
  {$EXTERNALSYM SSL_F_CUSTOM_EXT_ADD}
  SSL_F_CUSTOM_EXT_ADD = 554;
  {$EXTERNALSYM SSL_F_CUSTOM_EXT_PARSE}
  SSL_F_CUSTOM_EXT_PARSE = 555;
  {$EXTERNALSYM SSL_F_D2I_SSL_SESSION}
  SSL_F_D2I_SSL_SESSION = 103;
  {$EXTERNALSYM SSL_F_DANE_CTX_ENABLE}
  SSL_F_DANE_CTX_ENABLE = 347;
  {$EXTERNALSYM SSL_F_DANE_MTYPE_SET}
  SSL_F_DANE_MTYPE_SET = 393;
  {$EXTERNALSYM SSL_F_DANE_TLSA_ADD}
  SSL_F_DANE_TLSA_ADD = 394;
  {$EXTERNALSYM SSL_F_DERIVE_SECRET_KEY_AND_IV}
  SSL_F_DERIVE_SECRET_KEY_AND_IV = 514;
  {$EXTERNALSYM SSL_F_DO_DTLS1_WRITE}
  SSL_F_DO_DTLS1_WRITE = 245;
  {$EXTERNALSYM SSL_F_DO_SSL3_WRITE}
  SSL_F_DO_SSL3_WRITE = 104;
  {$EXTERNALSYM SSL_F_DTLS1_BUFFER_RECORD}
  SSL_F_DTLS1_BUFFER_RECORD = 247;
  {$EXTERNALSYM SSL_F_DTLS1_CHECK_TIMEOUT_NUM}
  SSL_F_DTLS1_CHECK_TIMEOUT_NUM = 318;
  {$EXTERNALSYM SSL_F_DTLS1_HEARTBEAT}
  SSL_F_DTLS1_HEARTBEAT = 305;
  {$EXTERNALSYM SSL_F_DTLS1_HM_FRAGMENT_NEW}
  SSL_F_DTLS1_HM_FRAGMENT_NEW = 623;
  {$EXTERNALSYM SSL_F_DTLS1_PREPROCESS_FRAGMENT}
  SSL_F_DTLS1_PREPROCESS_FRAGMENT = 288;
  {$EXTERNALSYM SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS}
  SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS = 424;
  {$EXTERNALSYM SSL_F_DTLS1_PROCESS_RECORD}
  SSL_F_DTLS1_PROCESS_RECORD = 257;
  {$EXTERNALSYM SSL_F_DTLS1_READ_BYTES}
  SSL_F_DTLS1_READ_BYTES = 258;
  {$EXTERNALSYM SSL_F_DTLS1_READ_FAILED}
  SSL_F_DTLS1_READ_FAILED = 339;
  {$EXTERNALSYM SSL_F_DTLS1_RETRANSMIT_MESSAGE}
  SSL_F_DTLS1_RETRANSMIT_MESSAGE = 390;
  {$EXTERNALSYM SSL_F_DTLS1_WRITE_APP_DATA_BYTES}
  SSL_F_DTLS1_WRITE_APP_DATA_BYTES = 268;
  {$EXTERNALSYM SSL_F_DTLS1_WRITE_BYTES}
  SSL_F_DTLS1_WRITE_BYTES = 545;
  {$EXTERNALSYM SSL_F_DTLSV1_LISTEN}
  SSL_F_DTLSV1_LISTEN = 350;
  {$EXTERNALSYM SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC}
  SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC = 371;
  {$EXTERNALSYM SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST}
  SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST = 385;
  {$EXTERNALSYM SSL_F_DTLS_GET_REASSEMBLED_MESSAGE}
  SSL_F_DTLS_GET_REASSEMBLED_MESSAGE = 370;
  {$EXTERNALSYM SSL_F_DTLS_PROCESS_HELLO_VERIFY}
  SSL_F_DTLS_PROCESS_HELLO_VERIFY = 386;
  {$EXTERNALSYM SSL_F_DTLS_RECORD_LAYER_NEW}
  SSL_F_DTLS_RECORD_LAYER_NEW = 635;
  {$EXTERNALSYM SSL_F_DTLS_WAIT_FOR_DRY}
  SSL_F_DTLS_WAIT_FOR_DRY = 592;
  {$EXTERNALSYM SSL_F_EARLY_DATA_COUNT_OK}
  SSL_F_EARLY_DATA_COUNT_OK = 532;
  {$EXTERNALSYM SSL_F_FINAL_EARLY_DATA}
  SSL_F_FINAL_EARLY_DATA = 556;
  {$EXTERNALSYM SSL_F_FINAL_EC_PT_FORMATS}
  SSL_F_FINAL_EC_PT_FORMATS = 485;
  {$EXTERNALSYM SSL_F_FINAL_EMS}
  SSL_F_FINAL_EMS = 486;
  {$EXTERNALSYM SSL_F_FINAL_KEY_SHARE}
  SSL_F_FINAL_KEY_SHARE = 503;
  {$EXTERNALSYM SSL_F_FINAL_MAXFRAGMENTLEN}
  SSL_F_FINAL_MAXFRAGMENTLEN = 557;
  {$EXTERNALSYM SSL_F_FINAL_RENEGOTIATE}
  SSL_F_FINAL_RENEGOTIATE = 483;
  {$EXTERNALSYM SSL_F_FINAL_SERVER_NAME}
  SSL_F_FINAL_SERVER_NAME = 558;
  {$EXTERNALSYM SSL_F_FINAL_SIG_ALGS}
  SSL_F_FINAL_SIG_ALGS = 497;
  {$EXTERNALSYM SSL_F_GET_CERT_VERIFY_TBS_DATA}
  SSL_F_GET_CERT_VERIFY_TBS_DATA = 588;
  {$EXTERNALSYM SSL_F_NSS_KEYLOG_INT}
  SSL_F_NSS_KEYLOG_INT = 500;
  {$EXTERNALSYM SSL_F_OPENSSL_INIT_SSL}
  SSL_F_OPENSSL_INIT_SSL = 342;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT13_READ_TRANSITION}
  SSL_F_OSSL_STATEM_CLIENT13_READ_TRANSITION = 436;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT13_WRITE_TRANSITION}
  SSL_F_OSSL_STATEM_CLIENT13_WRITE_TRANSITION = 598;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT_CONSTRUCT_MESSAGE}
  SSL_F_OSSL_STATEM_CLIENT_CONSTRUCT_MESSAGE = 430;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT_POST_PROCESS_MESSAGE}
  SSL_F_OSSL_STATEM_CLIENT_POST_PROCESS_MESSAGE = 593;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT_PROCESS_MESSAGE}
  SSL_F_OSSL_STATEM_CLIENT_PROCESS_MESSAGE = 594;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT_READ_TRANSITION}
  SSL_F_OSSL_STATEM_CLIENT_READ_TRANSITION = 417;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_CLIENT_WRITE_TRANSITION}
  SSL_F_OSSL_STATEM_CLIENT_WRITE_TRANSITION = 599;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER13_READ_TRANSITION}
  SSL_F_OSSL_STATEM_SERVER13_READ_TRANSITION = 437;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER13_WRITE_TRANSITION}
  SSL_F_OSSL_STATEM_SERVER13_WRITE_TRANSITION = 600;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER_CONSTRUCT_MESSAGE}
  SSL_F_OSSL_STATEM_SERVER_CONSTRUCT_MESSAGE = 431;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER_POST_PROCESS_MESSAGE}
  SSL_F_OSSL_STATEM_SERVER_POST_PROCESS_MESSAGE = 601;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER_POST_WORK}
  SSL_F_OSSL_STATEM_SERVER_POST_WORK = 602;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER_PROCESS_MESSAGE}
  SSL_F_OSSL_STATEM_SERVER_PROCESS_MESSAGE = 603;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION}
  SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION = 418;
  {$EXTERNALSYM SSL_F_OSSL_STATEM_SERVER_WRITE_TRANSITION}
  SSL_F_OSSL_STATEM_SERVER_WRITE_TRANSITION = 604;
  {$EXTERNALSYM SSL_F_PARSE_CA_NAMES}
  SSL_F_PARSE_CA_NAMES = 541;
  {$EXTERNALSYM SSL_F_PITEM_NEW}
  SSL_F_PITEM_NEW = 624;
  {$EXTERNALSYM SSL_F_PQUEUE_NEW}
  SSL_F_PQUEUE_NEW = 625;
  {$EXTERNALSYM SSL_F_PROCESS_KEY_SHARE_EXT}
  SSL_F_PROCESS_KEY_SHARE_EXT = 439;
  {$EXTERNALSYM SSL_F_READ_STATE_MACHINE}
  SSL_F_READ_STATE_MACHINE = 352;
  {$EXTERNALSYM SSL_F_SET_CLIENT_CIPHERSUITE}
  SSL_F_SET_CLIENT_CIPHERSUITE = 540;
  {$EXTERNALSYM SSL_F_SRP_GENERATE_CLIENT_MASTER_SECRET}
  SSL_F_SRP_GENERATE_CLIENT_MASTER_SECRET = 595;
  {$EXTERNALSYM SSL_F_SRP_GENERATE_SERVER_MASTER_SECRET}
  SSL_F_SRP_GENERATE_SERVER_MASTER_SECRET = 589;
  {$EXTERNALSYM SSL_F_SRP_VERIFY_SERVER_PARAM}
  SSL_F_SRP_VERIFY_SERVER_PARAM = 596;
  {$EXTERNALSYM SSL_F_SSL3_CHANGE_CIPHER_STATE}
  SSL_F_SSL3_CHANGE_CIPHER_STATE = 129;
  {$EXTERNALSYM SSL_F_SSL3_CHECK_CERT_AND_ALGORITHM}
  SSL_F_SSL3_CHECK_CERT_AND_ALGORITHM = 130;
  {$EXTERNALSYM SSL_F_SSL3_CTRL}
  SSL_F_SSL3_CTRL = 213;
  {$EXTERNALSYM SSL_F_SSL3_CTX_CTRL}
  SSL_F_SSL3_CTX_CTRL = 133;
  {$EXTERNALSYM SSL_F_SSL3_DIGEST_CACHED_RECORDS}
  SSL_F_SSL3_DIGEST_CACHED_RECORDS = 293;
  {$EXTERNALSYM SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC}
  SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC = 292;
  {$EXTERNALSYM SSL_F_SSL3_ENC}
  SSL_F_SSL3_ENC = 608;
  {$EXTERNALSYM SSL_F_SSL3_FINAL_FINISH_MAC}
  SSL_F_SSL3_FINAL_FINISH_MAC = 285;
  {$EXTERNALSYM SSL_F_SSL3_FINISH_MAC}
  SSL_F_SSL3_FINISH_MAC = 587;
  {$EXTERNALSYM SSL_F_SSL3_GENERATE_KEY_BLOCK}
  SSL_F_SSL3_GENERATE_KEY_BLOCK = 238;
  {$EXTERNALSYM SSL_F_SSL3_GENERATE_MASTER_SECRET}
  SSL_F_SSL3_GENERATE_MASTER_SECRET = 388;
  {$EXTERNALSYM SSL_F_SSL3_GET_RECORD}
  SSL_F_SSL3_GET_RECORD = 143;
  {$EXTERNALSYM SSL_F_SSL3_INIT_FINISHED_MAC}
  SSL_F_SSL3_INIT_FINISHED_MAC = 397;
  {$EXTERNALSYM SSL_F_SSL3_OUTPUT_CERT_CHAIN}
  SSL_F_SSL3_OUTPUT_CERT_CHAIN = 147;
  {$EXTERNALSYM SSL_F_SSL3_READ_BYTES}
  SSL_F_SSL3_READ_BYTES = 148;
  {$EXTERNALSYM SSL_F_SSL3_READ_N}
  SSL_F_SSL3_READ_N = 149;
  {$EXTERNALSYM SSL_F_SSL3_SETUP_KEY_BLOCK}
  SSL_F_SSL3_SETUP_KEY_BLOCK = 157;
  {$EXTERNALSYM SSL_F_SSL3_SETUP_READ_BUFFER}
  SSL_F_SSL3_SETUP_READ_BUFFER = 156;
  {$EXTERNALSYM SSL_F_SSL3_SETUP_WRITE_BUFFER}
  SSL_F_SSL3_SETUP_WRITE_BUFFER = 291;
  {$EXTERNALSYM SSL_F_SSL3_WRITE_BYTES}
  SSL_F_SSL3_WRITE_BYTES = 158;
  {$EXTERNALSYM SSL_F_SSL3_WRITE_PENDING}
  SSL_F_SSL3_WRITE_PENDING = 159;
  {$EXTERNALSYM SSL_F_SSL_ADD_CERT_CHAIN}
  SSL_F_SSL_ADD_CERT_CHAIN = 316;
  {$EXTERNALSYM SSL_F_SSL_ADD_CERT_TO_BUF}
  SSL_F_SSL_ADD_CERT_TO_BUF = 319;
  {$EXTERNALSYM SSL_F_SSL_ADD_CERT_TO_WPACKET}
  SSL_F_SSL_ADD_CERT_TO_WPACKET = 493;
  {$EXTERNALSYM SSL_F_SSL_ADD_CLIENTHELLO_RENEGOTIATE_EXT}
  SSL_F_SSL_ADD_CLIENTHELLO_RENEGOTIATE_EXT = 298;
  {$EXTERNALSYM SSL_F_SSL_ADD_CLIENTHELLO_TLSEXT}
  SSL_F_SSL_ADD_CLIENTHELLO_TLSEXT = 277;
  {$EXTERNALSYM SSL_F_SSL_ADD_CLIENTHELLO_USE_SRTP_EXT}
  SSL_F_SSL_ADD_CLIENTHELLO_USE_SRTP_EXT = 307;
  {$EXTERNALSYM SSL_F_SSL_ADD_DIR_CERT_SUBJECTS_TO_STACK}
  SSL_F_SSL_ADD_DIR_CERT_SUBJECTS_TO_STACK = 215;
  {$EXTERNALSYM SSL_F_SSL_ADD_FILE_CERT_SUBJECTS_TO_STACK}
  SSL_F_SSL_ADD_FILE_CERT_SUBJECTS_TO_STACK = 216;
  {$EXTERNALSYM SSL_F_SSL_ADD_SERVERHELLO_RENEGOTIATE_EXT}
  SSL_F_SSL_ADD_SERVERHELLO_RENEGOTIATE_EXT = 299;
  {$EXTERNALSYM SSL_F_SSL_ADD_SERVERHELLO_TLSEXT}
  SSL_F_SSL_ADD_SERVERHELLO_TLSEXT = 278;
  {$EXTERNALSYM SSL_F_SSL_ADD_SERVERHELLO_USE_SRTP_EXT}
  SSL_F_SSL_ADD_SERVERHELLO_USE_SRTP_EXT = 308;
  {$EXTERNALSYM SSL_F_SSL_BAD_METHOD}
  SSL_F_SSL_BAD_METHOD = 160;
  {$EXTERNALSYM SSL_F_SSL_BUILD_CERT_CHAIN}
  SSL_F_SSL_BUILD_CERT_CHAIN = 332;
  {$EXTERNALSYM SSL_F_SSL_BYTES_TO_CIPHER_LIST}
  SSL_F_SSL_BYTES_TO_CIPHER_LIST = 161;
  {$EXTERNALSYM SSL_F_SSL_CACHE_CIPHERLIST}
  SSL_F_SSL_CACHE_CIPHERLIST = 520;
  {$EXTERNALSYM SSL_F_SSL_CERT_ADD0_CHAIN_CERT}
  SSL_F_SSL_CERT_ADD0_CHAIN_CERT = 346;
  {$EXTERNALSYM SSL_F_SSL_CERT_DUP}
  SSL_F_SSL_CERT_DUP = 221;
  {$EXTERNALSYM SSL_F_SSL_CERT_NEW}
  SSL_F_SSL_CERT_NEW = 162;
  {$EXTERNALSYM SSL_F_SSL_CERT_SET0_CHAIN}
  SSL_F_SSL_CERT_SET0_CHAIN = 340;
  {$EXTERNALSYM SSL_F_SSL_CHECK_PRIVATE_KEY}
  SSL_F_SSL_CHECK_PRIVATE_KEY = 163;
  {$EXTERNALSYM SSL_F_SSL_CHECK_SERVERHELLO_TLSEXT}
  SSL_F_SSL_CHECK_SERVERHELLO_TLSEXT = 280;
  {$EXTERNALSYM SSL_F_SSL_CHECK_SRP_EXT_CLIENTHELLO}
  SSL_F_SSL_CHECK_SRP_EXT_CLIENTHELLO = 606;
  {$EXTERNALSYM SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG}
  SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG = 279;
  {$EXTERNALSYM SSL_F_SSL_CHOOSE_CLIENT_VERSION}
  SSL_F_SSL_CHOOSE_CLIENT_VERSION = 607;
  {$EXTERNALSYM SSL_F_SSL_CIPHER_DESCRIPTION}
  SSL_F_SSL_CIPHER_DESCRIPTION = 626;
  {$EXTERNALSYM SSL_F_SSL_CIPHER_LIST_TO_BYTES}
  SSL_F_SSL_CIPHER_LIST_TO_BYTES = 425;
  {$EXTERNALSYM SSL_F_SSL_CIPHER_PROCESS_RULESTR}
  SSL_F_SSL_CIPHER_PROCESS_RULESTR = 230;
  {$EXTERNALSYM SSL_F_SSL_CIPHER_STRENGTH_SORT}
  SSL_F_SSL_CIPHER_STRENGTH_SORT = 231;
  {$EXTERNALSYM SSL_F_SSL_CLEAR}
  SSL_F_SSL_CLEAR = 164;
  {$EXTERNALSYM SSL_F_SSL_CLIENT_HELLO_GET1_EXTENSIONS_PRESENT}
  SSL_F_SSL_CLIENT_HELLO_GET1_EXTENSIONS_PRESENT = 627;
  {$EXTERNALSYM SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD}
  SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD = 165;
  {$EXTERNALSYM SSL_F_SSL_CONF_CMD}
  SSL_F_SSL_CONF_CMD = 334;
  {$EXTERNALSYM SSL_F_SSL_CREATE_CIPHER_LIST}
  SSL_F_SSL_CREATE_CIPHER_LIST = 166;
  {$EXTERNALSYM SSL_F_SSL_CTRL}
  SSL_F_SSL_CTRL = 232;
  {$EXTERNALSYM SSL_F_SSL_CTX_CHECK_PRIVATE_KEY}
  SSL_F_SSL_CTX_CHECK_PRIVATE_KEY = 168;
  {$EXTERNALSYM SSL_F_SSL_CTX_ENABLE_CT}
  SSL_F_SSL_CTX_ENABLE_CT = 398;
  {$EXTERNALSYM SSL_F_SSL_CTX_MAKE_PROFILES}
  SSL_F_SSL_CTX_MAKE_PROFILES = 309;
  {$EXTERNALSYM SSL_F_SSL_CTX_NEW}
  SSL_F_SSL_CTX_NEW = 169;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_ALPN_PROTOS}
  SSL_F_SSL_CTX_SET_ALPN_PROTOS = 343;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_CIPHER_LIST}
  SSL_F_SSL_CTX_SET_CIPHER_LIST = 269;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE}
  SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE = 290;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_CT_VALIDATION_CALLBACK}
  SSL_F_SSL_CTX_SET_CT_VALIDATION_CALLBACK = 396;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT}
  SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT = 219;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_SSL_VERSION}
  SSL_F_SSL_CTX_SET_SSL_VERSION = 170;
  {$EXTERNALSYM SSL_F_SSL_CTX_SET_TLSEXT_MAX_FRAGMENT_LENGTH}
  SSL_F_SSL_CTX_SET_TLSEXT_MAX_FRAGMENT_LENGTH = 551;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_CERTIFICATE}
  SSL_F_SSL_CTX_USE_CERTIFICATE = 171;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_CERTIFICATE_ASN1}
  SSL_F_SSL_CTX_USE_CERTIFICATE_ASN1 = 172;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_CERTIFICATE_FILE}
  SSL_F_SSL_CTX_USE_CERTIFICATE_FILE = 173;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_PRIVATEKEY}
  SSL_F_SSL_CTX_USE_PRIVATEKEY = 174;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_PRIVATEKEY_ASN1}
  SSL_F_SSL_CTX_USE_PRIVATEKEY_ASN1 = 175;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_PRIVATEKEY_FILE}
  SSL_F_SSL_CTX_USE_PRIVATEKEY_FILE = 176;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT}
  SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT = 272;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_RSAPRIVATEKEY}
  SSL_F_SSL_CTX_USE_RSAPRIVATEKEY = 177;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_ASN1}
  SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_ASN1 = 178;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_FILE}
  SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_FILE = 179;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_SERVERINFO}
  SSL_F_SSL_CTX_USE_SERVERINFO = 336;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_SERVERINFO_EX}
  SSL_F_SSL_CTX_USE_SERVERINFO_EX = 543;
  {$EXTERNALSYM SSL_F_SSL_CTX_USE_SERVERINFO_FILE}
  SSL_F_SSL_CTX_USE_SERVERINFO_FILE = 337;
  {$EXTERNALSYM SSL_F_SSL_DANE_DUP}
  SSL_F_SSL_DANE_DUP = 403;
  {$EXTERNALSYM SSL_F_SSL_DANE_ENABLE}
  SSL_F_SSL_DANE_ENABLE = 395;
  {$EXTERNALSYM SSL_F_SSL_DERIVE}
  SSL_F_SSL_DERIVE = 590;
  {$EXTERNALSYM SSL_F_SSL_DO_CONFIG}
  SSL_F_SSL_DO_CONFIG = 391;
  {$EXTERNALSYM SSL_F_SSL_DO_HANDSHAKE}
  SSL_F_SSL_DO_HANDSHAKE = 180;
  {$EXTERNALSYM SSL_F_SSL_DUP_CA_LIST}
  SSL_F_SSL_DUP_CA_LIST = 408;
  {$EXTERNALSYM SSL_F_SSL_ENABLE_CT}
  SSL_F_SSL_ENABLE_CT = 402;
  {$EXTERNALSYM SSL_F_SSL_GENERATE_PKEY_GROUP}
  SSL_F_SSL_GENERATE_PKEY_GROUP = 559;
  {$EXTERNALSYM SSL_F_SSL_GENERATE_SESSION_ID}
  SSL_F_SSL_GENERATE_SESSION_ID = 547;
  {$EXTERNALSYM SSL_F_SSL_GET_NEW_SESSION}
  SSL_F_SSL_GET_NEW_SESSION = 181;
  {$EXTERNALSYM SSL_F_SSL_GET_PREV_SESSION}
  SSL_F_SSL_GET_PREV_SESSION = 217;
  {$EXTERNALSYM SSL_F_SSL_GET_SERVER_CERT_INDEX}
  SSL_F_SSL_GET_SERVER_CERT_INDEX = 322;
  {$EXTERNALSYM SSL_F_SSL_GET_SIGN_PKEY}
  SSL_F_SSL_GET_SIGN_PKEY = 183;
  {$EXTERNALSYM SSL_F_SSL_HANDSHAKE_HASH}
  SSL_F_SSL_HANDSHAKE_HASH = 560;
  {$EXTERNALSYM SSL_F_SSL_INIT_WBIO_BUFFER}
  SSL_F_SSL_INIT_WBIO_BUFFER = 184;
  {$EXTERNALSYM SSL_F_SSL_KEY_UPDATE}
  SSL_F_SSL_KEY_UPDATE = 515;
  {$EXTERNALSYM SSL_F_SSL_LOAD_CLIENT_CA_FILE}
  SSL_F_SSL_LOAD_CLIENT_CA_FILE = 185;
  {$EXTERNALSYM SSL_F_SSL_LOG_MASTER_SECRET}
  SSL_F_SSL_LOG_MASTER_SECRET = 498;
  {$EXTERNALSYM SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE}
  SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE = 499;
  {$EXTERNALSYM SSL_F_SSL_MODULE_INIT}
  SSL_F_SSL_MODULE_INIT = 392;
  {$EXTERNALSYM SSL_F_SSL_NEW}
  SSL_F_SSL_NEW = 186;
  {$EXTERNALSYM SSL_F_SSL_NEXT_PROTO_VALIDATE}
  SSL_F_SSL_NEXT_PROTO_VALIDATE = 565;
  {$EXTERNALSYM SSL_F_SSL_PARSE_CLIENTHELLO_RENEGOTIATE_EXT}
  SSL_F_SSL_PARSE_CLIENTHELLO_RENEGOTIATE_EXT = 300;
  {$EXTERNALSYM SSL_F_SSL_PARSE_CLIENTHELLO_TLSEXT}
  SSL_F_SSL_PARSE_CLIENTHELLO_TLSEXT = 302;
  {$EXTERNALSYM SSL_F_SSL_PARSE_CLIENTHELLO_USE_SRTP_EXT}
  SSL_F_SSL_PARSE_CLIENTHELLO_USE_SRTP_EXT = 310;
  {$EXTERNALSYM SSL_F_SSL_PARSE_SERVERHELLO_RENEGOTIATE_EXT}
  SSL_F_SSL_PARSE_SERVERHELLO_RENEGOTIATE_EXT = 301;
  {$EXTERNALSYM SSL_F_SSL_PARSE_SERVERHELLO_TLSEXT}
  SSL_F_SSL_PARSE_SERVERHELLO_TLSEXT = 303;
  {$EXTERNALSYM SSL_F_SSL_PARSE_SERVERHELLO_USE_SRTP_EXT}
  SSL_F_SSL_PARSE_SERVERHELLO_USE_SRTP_EXT = 311;
  {$EXTERNALSYM SSL_F_SSL_PEEK}
  SSL_F_SSL_PEEK = 270;
  {$EXTERNALSYM SSL_F_SSL_PEEK_EX}
  SSL_F_SSL_PEEK_EX = 432;
  {$EXTERNALSYM SSL_F_SSL_PEEK_INTERNAL}
  SSL_F_SSL_PEEK_INTERNAL = 522;
  {$EXTERNALSYM SSL_F_SSL_READ}
  SSL_F_SSL_READ = 223;
  {$EXTERNALSYM SSL_F_SSL_READ_EARLY_DATA}
  SSL_F_SSL_READ_EARLY_DATA = 529;
  {$EXTERNALSYM SSL_F_SSL_READ_EX}
  SSL_F_SSL_READ_EX = 434;
  {$EXTERNALSYM SSL_F_SSL_READ_INTERNAL}
  SSL_F_SSL_READ_INTERNAL = 523;
  {$EXTERNALSYM SSL_F_SSL_RENEGOTIATE}
  SSL_F_SSL_RENEGOTIATE = 516;
  {$EXTERNALSYM SSL_F_SSL_RENEGOTIATE_ABBREVIATED}
  SSL_F_SSL_RENEGOTIATE_ABBREVIATED = 546;
  {$EXTERNALSYM SSL_F_SSL_SCAN_CLIENTHELLO_TLSEXT}
  SSL_F_SSL_SCAN_CLIENTHELLO_TLSEXT = 320;
  {$EXTERNALSYM SSL_F_SSL_SCAN_SERVERHELLO_TLSEXT}
  SSL_F_SSL_SCAN_SERVERHELLO_TLSEXT = 321;
  {$EXTERNALSYM SSL_F_SSL_SESSION_DUP}
  SSL_F_SSL_SESSION_DUP = 348;
  {$EXTERNALSYM SSL_F_SSL_SESSION_NEW}
  SSL_F_SSL_SESSION_NEW = 189;
  {$EXTERNALSYM SSL_F_SSL_SESSION_PRINT_FP}
  SSL_F_SSL_SESSION_PRINT_FP = 190;
  {$EXTERNALSYM SSL_F_SSL_SESSION_SET1_ID}
  SSL_F_SSL_SESSION_SET1_ID = 423;
  {$EXTERNALSYM SSL_F_SSL_SESSION_SET1_ID_CONTEXT}
  SSL_F_SSL_SESSION_SET1_ID_CONTEXT = 312;
  {$EXTERNALSYM SSL_F_SSL_SET_ALPN_PROTOS}
  SSL_F_SSL_SET_ALPN_PROTOS = 344;
  {$EXTERNALSYM SSL_F_SSL_SET_CERT}
  SSL_F_SSL_SET_CERT = 191;
  {$EXTERNALSYM SSL_F_SSL_SET_CERT_AND_KEY}
  SSL_F_SSL_SET_CERT_AND_KEY = 621;
  {$EXTERNALSYM SSL_F_SSL_SET_CIPHER_LIST}
  SSL_F_SSL_SET_CIPHER_LIST = 271;
  {$EXTERNALSYM SSL_F_SSL_SET_CT_VALIDATION_CALLBACK}
  SSL_F_SSL_SET_CT_VALIDATION_CALLBACK = 399;
  {$EXTERNALSYM SSL_F_SSL_SET_FD}
  SSL_F_SSL_SET_FD = 192;
  {$EXTERNALSYM SSL_F_SSL_SET_PKEY}
  SSL_F_SSL_SET_PKEY = 193;
  {$EXTERNALSYM SSL_F_SSL_SET_RFD}
  SSL_F_SSL_SET_RFD = 194;
  {$EXTERNALSYM SSL_F_SSL_SET_SESSION}
  SSL_F_SSL_SET_SESSION = 195;
  {$EXTERNALSYM SSL_F_SSL_SET_SESSION_ID_CONTEXT}
  SSL_F_SSL_SET_SESSION_ID_CONTEXT = 218;
  {$EXTERNALSYM SSL_F_SSL_SET_SESSION_TICKET_EXT}
  SSL_F_SSL_SET_SESSION_TICKET_EXT = 294;
  {$EXTERNALSYM SSL_F_SSL_SET_TLSEXT_MAX_FRAGMENT_LENGTH}
  SSL_F_SSL_SET_TLSEXT_MAX_FRAGMENT_LENGTH = 550;
  {$EXTERNALSYM SSL_F_SSL_SET_WFD}
  SSL_F_SSL_SET_WFD = 196;
  {$EXTERNALSYM SSL_F_SSL_SHUTDOWN}
  SSL_F_SSL_SHUTDOWN = 224;
  {$EXTERNALSYM SSL_F_SSL_SRP_CTX_INIT}
  SSL_F_SSL_SRP_CTX_INIT = 313;
  {$EXTERNALSYM SSL_F_SSL_START_ASYNC_JOB}
  SSL_F_SSL_START_ASYNC_JOB = 389;
  {$EXTERNALSYM SSL_F_SSL_UNDEFINED_FUNCTION}
  SSL_F_SSL_UNDEFINED_FUNCTION = 197;
  {$EXTERNALSYM SSL_F_SSL_UNDEFINED_VOID_FUNCTION}
  SSL_F_SSL_UNDEFINED_VOID_FUNCTION = 244;
  {$EXTERNALSYM SSL_F_SSL_USE_CERTIFICATE}
  SSL_F_SSL_USE_CERTIFICATE = 198;
  {$EXTERNALSYM SSL_F_SSL_USE_CERTIFICATE_ASN1}
  SSL_F_SSL_USE_CERTIFICATE_ASN1 = 199;
  {$EXTERNALSYM SSL_F_SSL_USE_CERTIFICATE_FILE}
  SSL_F_SSL_USE_CERTIFICATE_FILE = 200;
  {$EXTERNALSYM SSL_F_SSL_USE_PRIVATEKEY}
  SSL_F_SSL_USE_PRIVATEKEY = 201;
  {$EXTERNALSYM SSL_F_SSL_USE_PRIVATEKEY_ASN1}
  SSL_F_SSL_USE_PRIVATEKEY_ASN1 = 202;
  {$EXTERNALSYM SSL_F_SSL_USE_PRIVATEKEY_FILE}
  SSL_F_SSL_USE_PRIVATEKEY_FILE = 203;
  {$EXTERNALSYM SSL_F_SSL_USE_PSK_IDENTITY_HINT}
  SSL_F_SSL_USE_PSK_IDENTITY_HINT = 273;
  {$EXTERNALSYM SSL_F_SSL_USE_RSAPRIVATEKEY}
  SSL_F_SSL_USE_RSAPRIVATEKEY = 204;
  {$EXTERNALSYM SSL_F_SSL_USE_RSAPRIVATEKEY_ASN1}
  SSL_F_SSL_USE_RSAPRIVATEKEY_ASN1 = 205;
  {$EXTERNALSYM SSL_F_SSL_USE_RSAPRIVATEKEY_FILE}
  SSL_F_SSL_USE_RSAPRIVATEKEY_FILE = 206;
  {$EXTERNALSYM SSL_F_SSL_VALIDATE_CT}
  SSL_F_SSL_VALIDATE_CT = 400;
  {$EXTERNALSYM SSL_F_SSL_VERIFY_CERT_CHAIN}
  SSL_F_SSL_VERIFY_CERT_CHAIN = 207;
  {$EXTERNALSYM SSL_F_SSL_VERIFY_CLIENT_POST_HANDSHAKE}
  SSL_F_SSL_VERIFY_CLIENT_POST_HANDSHAKE = 616;
  {$EXTERNALSYM SSL_F_SSL_WRITE}
  SSL_F_SSL_WRITE = 208;
  {$EXTERNALSYM SSL_F_SSL_WRITE_EARLY_DATA}
  SSL_F_SSL_WRITE_EARLY_DATA = 526;
  {$EXTERNALSYM SSL_F_SSL_WRITE_EARLY_FINISH}
  SSL_F_SSL_WRITE_EARLY_FINISH = 527;
  {$EXTERNALSYM SSL_F_SSL_WRITE_EX}
  SSL_F_SSL_WRITE_EX = 433;
  {$EXTERNALSYM SSL_F_SSL_WRITE_INTERNAL}
  SSL_F_SSL_WRITE_INTERNAL = 524;
  {$EXTERNALSYM SSL_F_STATE_MACHINE}
  SSL_F_STATE_MACHINE = 353;
  {$EXTERNALSYM SSL_F_TLS12_CHECK_PEER_SIGALG}
  SSL_F_TLS12_CHECK_PEER_SIGALG = 333;
  {$EXTERNALSYM SSL_F_TLS12_COPY_SIGALGS}
  SSL_F_TLS12_COPY_SIGALGS = 533;
  {$EXTERNALSYM SSL_F_TLS13_CHANGE_CIPHER_STATE}
  SSL_F_TLS13_CHANGE_CIPHER_STATE = 440;
  {$EXTERNALSYM SSL_F_TLS13_ENC}
  SSL_F_TLS13_ENC = 609;
  {$EXTERNALSYM SSL_F_TLS13_FINAL_FINISH_MAC}
  SSL_F_TLS13_FINAL_FINISH_MAC = 605;
  {$EXTERNALSYM SSL_F_TLS13_GENERATE_SECRET}
  SSL_F_TLS13_GENERATE_SECRET = 591;
  {$EXTERNALSYM SSL_F_TLS13_HKDF_EXPAND}
  SSL_F_TLS13_HKDF_EXPAND = 561;
  {$EXTERNALSYM SSL_F_TLS13_RESTORE_HANDSHAKE_DIGEST_FOR_PHA}
  SSL_F_TLS13_RESTORE_HANDSHAKE_DIGEST_FOR_PHA = 617;
  {$EXTERNALSYM SSL_F_TLS13_SAVE_HANDSHAKE_DIGEST_FOR_PHA}
  SSL_F_TLS13_SAVE_HANDSHAKE_DIGEST_FOR_PHA = 618;
  {$EXTERNALSYM SSL_F_TLS13_SETUP_KEY_BLOCK}
  SSL_F_TLS13_SETUP_KEY_BLOCK = 441;
  {$EXTERNALSYM SSL_F_TLS1_CHANGE_CIPHER_STATE}
  SSL_F_TLS1_CHANGE_CIPHER_STATE = 209;
  {$EXTERNALSYM SSL_F_TLS1_CHECK_DUPLICATE_EXTENSIONS}
  SSL_F_TLS1_CHECK_DUPLICATE_EXTENSIONS = 341;
  {$EXTERNALSYM SSL_F_TLS1_ENC}
  SSL_F_TLS1_ENC = 401;
  {$EXTERNALSYM SSL_F_TLS1_EXPORT_KEYING_MATERIAL}
  SSL_F_TLS1_EXPORT_KEYING_MATERIAL = 314;
  {$EXTERNALSYM SSL_F_TLS1_GET_CURVELIST}
  SSL_F_TLS1_GET_CURVELIST = 338;
  {$EXTERNALSYM SSL_F_TLS1_PRF}
  SSL_F_TLS1_PRF = 284;
  {$EXTERNALSYM SSL_F_TLS1_SAVE_U16}
  SSL_F_TLS1_SAVE_U16 = 628;
  {$EXTERNALSYM SSL_F_TLS1_SETUP_KEY_BLOCK}
  SSL_F_TLS1_SETUP_KEY_BLOCK = 211;
  {$EXTERNALSYM SSL_F_TLS1_SET_GROUPS}
  SSL_F_TLS1_SET_GROUPS = 629;
  {$EXTERNALSYM SSL_F_TLS1_SET_RAW_SIGALGS}
  SSL_F_TLS1_SET_RAW_SIGALGS = 630;
  {$EXTERNALSYM SSL_F_TLS1_SET_SERVER_SIGALGS}
  SSL_F_TLS1_SET_SERVER_SIGALGS = 335;
  {$EXTERNALSYM SSL_F_TLS1_SET_SHARED_SIGALGS}
  SSL_F_TLS1_SET_SHARED_SIGALGS = 631;
  {$EXTERNALSYM SSL_F_TLS1_SET_SIGALGS}
  SSL_F_TLS1_SET_SIGALGS = 632;
  {$EXTERNALSYM SSL_F_TLS_CHOOSE_SIGALG}
  SSL_F_TLS_CHOOSE_SIGALG = 513;
  {$EXTERNALSYM SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK}
  SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK = 354;
  {$EXTERNALSYM SSL_F_TLS_COLLECT_EXTENSIONS}
  SSL_F_TLS_COLLECT_EXTENSIONS = 435;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CERTIFICATE_AUTHORITIES}
  SSL_F_TLS_CONSTRUCT_CERTIFICATE_AUTHORITIES = 542;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CERTIFICATE_REQUEST}
  SSL_F_TLS_CONSTRUCT_CERTIFICATE_REQUEST = 372;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CERT_STATUS}
  SSL_F_TLS_CONSTRUCT_CERT_STATUS = 429;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY}
  SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY = 494;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CERT_VERIFY}
  SSL_F_TLS_CONSTRUCT_CERT_VERIFY = 496;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC}
  SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC = 427;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CKE_DHE}
  SSL_F_TLS_CONSTRUCT_CKE_DHE = 404;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CKE_ECDHE}
  SSL_F_TLS_CONSTRUCT_CKE_ECDHE = 405;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CKE_GOST}
  SSL_F_TLS_CONSTRUCT_CKE_GOST = 406;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CKE_PSK_PREAMBLE}
  SSL_F_TLS_CONSTRUCT_CKE_PSK_PREAMBLE = 407;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CKE_RSA}
  SSL_F_TLS_CONSTRUCT_CKE_RSA = 409;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CKE_SRP}
  SSL_F_TLS_CONSTRUCT_CKE_SRP = 410;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE}
  SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE = 484;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CLIENT_HELLO}
  SSL_F_TLS_CONSTRUCT_CLIENT_HELLO = 487;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CLIENT_KEY_EXCHANGE}
  SSL_F_TLS_CONSTRUCT_CLIENT_KEY_EXCHANGE = 488;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CLIENT_VERIFY}
  SSL_F_TLS_CONSTRUCT_CLIENT_VERIFY = 489;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_ALPN}
  SSL_F_TLS_CONSTRUCT_CTOS_ALPN = 466;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_CERTIFICATE}
  SSL_F_TLS_CONSTRUCT_CTOS_CERTIFICATE = 355;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_COOKIE}
  SSL_F_TLS_CONSTRUCT_CTOS_COOKIE = 535;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_EARLY_DATA}
  SSL_F_TLS_CONSTRUCT_CTOS_EARLY_DATA = 530;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_EC_PT_FORMATS}
  SSL_F_TLS_CONSTRUCT_CTOS_EC_PT_FORMATS = 467;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_EMS}
  SSL_F_TLS_CONSTRUCT_CTOS_EMS = 468;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_ETM}
  SSL_F_TLS_CONSTRUCT_CTOS_ETM = 469;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_HELLO}
  SSL_F_TLS_CONSTRUCT_CTOS_HELLO = 356;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_KEY_EXCHANGE}
  SSL_F_TLS_CONSTRUCT_CTOS_KEY_EXCHANGE = 357;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE}
  SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE = 470;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_MAXFRAGMENTLEN}
  SSL_F_TLS_CONSTRUCT_CTOS_MAXFRAGMENTLEN = 549;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_NPN}
  SSL_F_TLS_CONSTRUCT_CTOS_NPN = 471;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_PADDING}
  SSL_F_TLS_CONSTRUCT_CTOS_PADDING = 472;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_POST_HANDSHAKE_AUTH}
  SSL_F_TLS_CONSTRUCT_CTOS_POST_HANDSHAKE_AUTH = 619;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_PSK}
  SSL_F_TLS_CONSTRUCT_CTOS_PSK = 501;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES}
  SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES = 509;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE}
  SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE = 473;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SCT}
  SSL_F_TLS_CONSTRUCT_CTOS_SCT = 474;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME}
  SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME = 475;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET}
  SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET = 476;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS}
  SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS = 477;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SRP}
  SSL_F_TLS_CONSTRUCT_CTOS_SRP = 478;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST}
  SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST = 479;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_GROUPS}
  SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_GROUPS = 480;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS}
  SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS = 481;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP}
  SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP = 482;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_CTOS_VERIFY}
  SSL_F_TLS_CONSTRUCT_CTOS_VERIFY = 358;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_ENCRYPTED_EXTENSIONS}
  SSL_F_TLS_CONSTRUCT_ENCRYPTED_EXTENSIONS = 443;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_END_OF_EARLY_DATA}
  SSL_F_TLS_CONSTRUCT_END_OF_EARLY_DATA = 536;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_EXTENSIONS}
  SSL_F_TLS_CONSTRUCT_EXTENSIONS = 447;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_FINISHED}
  SSL_F_TLS_CONSTRUCT_FINISHED = 359;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_HELLO_REQUEST}
  SSL_F_TLS_CONSTRUCT_HELLO_REQUEST = 373;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_HELLO_RETRY_REQUEST}
  SSL_F_TLS_CONSTRUCT_HELLO_RETRY_REQUEST = 510;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_KEY_UPDATE}
  SSL_F_TLS_CONSTRUCT_KEY_UPDATE = 517;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_NEW_SESSION_TICKET}
  SSL_F_TLS_CONSTRUCT_NEW_SESSION_TICKET = 428;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_NEXT_PROTO}
  SSL_F_TLS_CONSTRUCT_NEXT_PROTO = 426;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE}
  SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE = 490;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_SERVER_HELLO}
  SSL_F_TLS_CONSTRUCT_SERVER_HELLO = 491;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_SERVER_KEY_EXCHANGE}
  SSL_F_TLS_CONSTRUCT_SERVER_KEY_EXCHANGE = 492;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_ALPN}
  SSL_F_TLS_CONSTRUCT_STOC_ALPN = 451;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_CERTIFICATE}
  SSL_F_TLS_CONSTRUCT_STOC_CERTIFICATE = 374;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_COOKIE}
  SSL_F_TLS_CONSTRUCT_STOC_COOKIE = 613;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG}
  SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG = 452;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_DONE}
  SSL_F_TLS_CONSTRUCT_STOC_DONE = 375;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_EARLY_DATA}
  SSL_F_TLS_CONSTRUCT_STOC_EARLY_DATA = 531;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_EARLY_DATA_INFO}
  SSL_F_TLS_CONSTRUCT_STOC_EARLY_DATA_INFO = 525;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS}
  SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS = 453;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_EMS}
  SSL_F_TLS_CONSTRUCT_STOC_EMS = 454;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_ETM}
  SSL_F_TLS_CONSTRUCT_STOC_ETM = 455;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_HELLO}
  SSL_F_TLS_CONSTRUCT_STOC_HELLO = 376;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_KEY_EXCHANGE}
  SSL_F_TLS_CONSTRUCT_STOC_KEY_EXCHANGE = 377;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE}
  SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE = 456;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_MAXFRAGMENTLEN}
  SSL_F_TLS_CONSTRUCT_STOC_MAXFRAGMENTLEN = 548;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_NEXT_PROTO_NEG}
  SSL_F_TLS_CONSTRUCT_STOC_NEXT_PROTO_NEG = 457;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_PSK}
  SSL_F_TLS_CONSTRUCT_STOC_PSK = 504;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE}
  SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE = 458;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME}
  SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME = 459;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET}
  SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET = 460;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST}
  SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST = 461;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_SUPPORTED_GROUPS}
  SSL_F_TLS_CONSTRUCT_STOC_SUPPORTED_GROUPS = 544;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_SUPPORTED_VERSIONS}
  SSL_F_TLS_CONSTRUCT_STOC_SUPPORTED_VERSIONS = 611;
  {$EXTERNALSYM SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP}
  SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP = 462;
  {$EXTERNALSYM SSL_F_TLS_EARLY_POST_PROCESS_CLIENT_HELLO}
  SSL_F_TLS_EARLY_POST_PROCESS_CLIENT_HELLO = 521;
  {$EXTERNALSYM SSL_F_TLS_FINISH_HANDSHAKE}
  SSL_F_TLS_FINISH_HANDSHAKE = 597;
  {$EXTERNALSYM SSL_F_TLS_GET_MESSAGE_BODY}
  SSL_F_TLS_GET_MESSAGE_BODY = 351;
  {$EXTERNALSYM SSL_F_TLS_GET_MESSAGE_HEADER}
  SSL_F_TLS_GET_MESSAGE_HEADER = 387;
  {$EXTERNALSYM SSL_F_TLS_HANDLE_ALPN}
  SSL_F_TLS_HANDLE_ALPN = 562;
  {$EXTERNALSYM SSL_F_TLS_HANDLE_STATUS_REQUEST}
  SSL_F_TLS_HANDLE_STATUS_REQUEST = 563;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CERTIFICATE_AUTHORITIES}
  SSL_F_TLS_PARSE_CERTIFICATE_AUTHORITIES = 566;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CLIENTHELLO_TLSEXT}
  SSL_F_TLS_PARSE_CLIENTHELLO_TLSEXT = 449;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_ALPN}
  SSL_F_TLS_PARSE_CTOS_ALPN = 567;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_COOKIE}
  SSL_F_TLS_PARSE_CTOS_COOKIE = 614;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_EARLY_DATA}
  SSL_F_TLS_PARSE_CTOS_EARLY_DATA = 568;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_EC_PT_FORMATS}
  SSL_F_TLS_PARSE_CTOS_EC_PT_FORMATS = 569;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_EMS}
  SSL_F_TLS_PARSE_CTOS_EMS = 570;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_KEY_SHARE}
  SSL_F_TLS_PARSE_CTOS_KEY_SHARE = 463;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_MAXFRAGMENTLEN}
  SSL_F_TLS_PARSE_CTOS_MAXFRAGMENTLEN = 571;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_POST_HANDSHAKE_AUTH}
  SSL_F_TLS_PARSE_CTOS_POST_HANDSHAKE_AUTH = 620;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_PSK}
  SSL_F_TLS_PARSE_CTOS_PSK = 505;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_PSK_KEX_MODES}
  SSL_F_TLS_PARSE_CTOS_PSK_KEX_MODES = 572;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_RENEGOTIATE}
  SSL_F_TLS_PARSE_CTOS_RENEGOTIATE = 464;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_SERVER_NAME}
  SSL_F_TLS_PARSE_CTOS_SERVER_NAME = 573;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_SESSION_TICKET}
  SSL_F_TLS_PARSE_CTOS_SESSION_TICKET = 574;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_SIG_ALGS}
  SSL_F_TLS_PARSE_CTOS_SIG_ALGS = 575;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_SIG_ALGS_CERT}
  SSL_F_TLS_PARSE_CTOS_SIG_ALGS_CERT = 615;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_SRP}
  SSL_F_TLS_PARSE_CTOS_SRP = 576;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_STATUS_REQUEST}
  SSL_F_TLS_PARSE_CTOS_STATUS_REQUEST = 577;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_SUPPORTED_GROUPS}
  SSL_F_TLS_PARSE_CTOS_SUPPORTED_GROUPS = 578;
  {$EXTERNALSYM SSL_F_TLS_PARSE_CTOS_USE_SRTP}
  SSL_F_TLS_PARSE_CTOS_USE_SRTP = 465;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_ALPN}
  SSL_F_TLS_PARSE_STOC_ALPN = 579;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_COOKIE}
  SSL_F_TLS_PARSE_STOC_COOKIE = 534;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_EARLY_DATA}
  SSL_F_TLS_PARSE_STOC_EARLY_DATA = 538;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_EARLY_DATA_INFO}
  SSL_F_TLS_PARSE_STOC_EARLY_DATA_INFO = 528;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_EC_PT_FORMATS}
  SSL_F_TLS_PARSE_STOC_EC_PT_FORMATS = 580;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_KEY_SHARE}
  SSL_F_TLS_PARSE_STOC_KEY_SHARE = 445;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_MAXFRAGMENTLEN}
  SSL_F_TLS_PARSE_STOC_MAXFRAGMENTLEN = 581;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_NPN}
  SSL_F_TLS_PARSE_STOC_NPN = 582;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_PSK}
  SSL_F_TLS_PARSE_STOC_PSK = 502;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_RENEGOTIATE}
  SSL_F_TLS_PARSE_STOC_RENEGOTIATE = 448;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_SCT}
  SSL_F_TLS_PARSE_STOC_SCT = 564;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_SERVER_NAME}
  SSL_F_TLS_PARSE_STOC_SERVER_NAME = 583;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_SESSION_TICKET}
  SSL_F_TLS_PARSE_STOC_SESSION_TICKET = 584;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_STATUS_REQUEST}
  SSL_F_TLS_PARSE_STOC_STATUS_REQUEST = 585;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_SUPPORTED_VERSIONS}
  SSL_F_TLS_PARSE_STOC_SUPPORTED_VERSIONS = 612;
  {$EXTERNALSYM SSL_F_TLS_PARSE_STOC_USE_SRTP}
  SSL_F_TLS_PARSE_STOC_USE_SRTP = 446;
  {$EXTERNALSYM SSL_F_TLS_POST_PROCESS_CLIENT_HELLO}
  SSL_F_TLS_POST_PROCESS_CLIENT_HELLO = 378;
  {$EXTERNALSYM SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE}
  SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE = 384;
  {$EXTERNALSYM SSL_F_TLS_PREPARE_CLIENT_CERTIFICATE}
  SSL_F_TLS_PREPARE_CLIENT_CERTIFICATE = 360;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_AS_HELLO_RETRY_REQUEST}
  SSL_F_TLS_PROCESS_AS_HELLO_RETRY_REQUEST = 610;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CERTIFICATE_REQUEST}
  SSL_F_TLS_PROCESS_CERTIFICATE_REQUEST = 361;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CERT_STATUS}
  SSL_F_TLS_PROCESS_CERT_STATUS = 362;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CERT_STATUS_BODY}
  SSL_F_TLS_PROCESS_CERT_STATUS_BODY = 495;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CERT_VERIFY}
  SSL_F_TLS_PROCESS_CERT_VERIFY = 379;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CHANGE_CIPHER_SPEC}
  SSL_F_TLS_PROCESS_CHANGE_CIPHER_SPEC = 363;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CKE_DHE}
  SSL_F_TLS_PROCESS_CKE_DHE = 411;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CKE_ECDHE}
  SSL_F_TLS_PROCESS_CKE_ECDHE = 412;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CKE_GOST}
  SSL_F_TLS_PROCESS_CKE_GOST = 413;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE}
  SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE = 414;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CKE_RSA}
  SSL_F_TLS_PROCESS_CKE_RSA = 415;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CKE_SRP}
  SSL_F_TLS_PROCESS_CKE_SRP = 416;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE}
  SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE = 380;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CLIENT_HELLO}
  SSL_F_TLS_PROCESS_CLIENT_HELLO = 381;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_CLIENT_KEY_EXCHANGE}
  SSL_F_TLS_PROCESS_CLIENT_KEY_EXCHANGE = 382;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_ENCRYPTED_EXTENSIONS}
  SSL_F_TLS_PROCESS_ENCRYPTED_EXTENSIONS = 444;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_END_OF_EARLY_DATA}
  SSL_F_TLS_PROCESS_END_OF_EARLY_DATA = 537;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_FINISHED}
  SSL_F_TLS_PROCESS_FINISHED = 364;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_HELLO_REQ}
  SSL_F_TLS_PROCESS_HELLO_REQ = 507;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_HELLO_RETRY_REQUEST}
  SSL_F_TLS_PROCESS_HELLO_RETRY_REQUEST = 511;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_INITIAL_SERVER_FLIGHT}
  SSL_F_TLS_PROCESS_INITIAL_SERVER_FLIGHT = 442;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_KEY_EXCHANGE}
  SSL_F_TLS_PROCESS_KEY_EXCHANGE = 365;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_KEY_UPDATE}
  SSL_F_TLS_PROCESS_KEY_UPDATE = 518;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_NEW_SESSION_TICKET}
  SSL_F_TLS_PROCESS_NEW_SESSION_TICKET = 366;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_NEXT_PROTO}
  SSL_F_TLS_PROCESS_NEXT_PROTO = 383;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SERVER_CERTIFICATE}
  SSL_F_TLS_PROCESS_SERVER_CERTIFICATE = 367;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SERVER_DONE}
  SSL_F_TLS_PROCESS_SERVER_DONE = 368;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SERVER_HELLO}
  SSL_F_TLS_PROCESS_SERVER_HELLO = 369;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SKE_DHE}
  SSL_F_TLS_PROCESS_SKE_DHE = 419;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SKE_ECDHE}
  SSL_F_TLS_PROCESS_SKE_ECDHE = 420;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SKE_PSK_PREAMBLE}
  SSL_F_TLS_PROCESS_SKE_PSK_PREAMBLE = 421;
  {$EXTERNALSYM SSL_F_TLS_PROCESS_SKE_SRP}
  SSL_F_TLS_PROCESS_SKE_SRP = 422;
  {$EXTERNALSYM SSL_F_TLS_PSK_DO_BINDER}
  SSL_F_TLS_PSK_DO_BINDER = 506;
  {$EXTERNALSYM SSL_F_TLS_SCAN_CLIENTHELLO_TLSEXT}
  SSL_F_TLS_SCAN_CLIENTHELLO_TLSEXT = 450;
  {$EXTERNALSYM SSL_F_TLS_SETUP_HANDSHAKE}
  SSL_F_TLS_SETUP_HANDSHAKE = 508;
  {$EXTERNALSYM SSL_F_USE_CERTIFICATE_CHAIN_FILE}
  SSL_F_USE_CERTIFICATE_CHAIN_FILE = 220;
  {$EXTERNALSYM SSL_F_WPACKET_INTERN_INIT_LEN}
  SSL_F_WPACKET_INTERN_INIT_LEN = 633;
  {$EXTERNALSYM SSL_F_WPACKET_START_SUB_PACKET_LEN__}
  SSL_F_WPACKET_START_SUB_PACKET_LEN__ = 634;
  {$EXTERNALSYM SSL_F_WRITE_STATE_MACHINE}
  SSL_F_WRITE_STATE_MACHINE = 586;
  {$EXTERNALSYM SSL_R_APPLICATION_DATA_AFTER_CLOSE_NOTIFY}
  SSL_R_APPLICATION_DATA_AFTER_CLOSE_NOTIFY = 291;
  {$EXTERNALSYM SSL_R_APP_DATA_IN_HANDSHAKE}
  SSL_R_APP_DATA_IN_HANDSHAKE = 100;
  {$EXTERNALSYM SSL_R_ATTEMPT_TO_REUSE_SESSION_IN_DIFFERENT_CONTEXT}
  SSL_R_ATTEMPT_TO_REUSE_SESSION_IN_DIFFERENT_CONTEXT = 272;
  {$EXTERNALSYM SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE}
  SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE = 143;
  {$EXTERNALSYM SSL_R_AT_LEAST_TLS_1_2_NEEDED_IN_SUITEB_MODE}
  SSL_R_AT_LEAST_TLS_1_2_NEEDED_IN_SUITEB_MODE = 158;
  {$EXTERNALSYM SSL_R_BAD_CHANGE_CIPHER_SPEC}
  SSL_R_BAD_CHANGE_CIPHER_SPEC = 103;
  {$EXTERNALSYM SSL_R_BAD_CIPHER}
  SSL_R_BAD_CIPHER = 186;
  {$EXTERNALSYM SSL_R_BAD_DATA}
  SSL_R_BAD_DATA = 390;
  {$EXTERNALSYM SSL_R_BAD_DATA_RETURNED_BY_CALLBACK}
  SSL_R_BAD_DATA_RETURNED_BY_CALLBACK = 106;
  {$EXTERNALSYM SSL_R_BAD_DECOMPRESSION}
  SSL_R_BAD_DECOMPRESSION = 107;
  {$EXTERNALSYM SSL_R_BAD_DH_VALUE}
  SSL_R_BAD_DH_VALUE = 102;
  {$EXTERNALSYM SSL_R_BAD_DIGEST_LENGTH}
  SSL_R_BAD_DIGEST_LENGTH = 111;
  {$EXTERNALSYM SSL_R_BAD_EARLY_DATA}
  SSL_R_BAD_EARLY_DATA = 233;
  {$EXTERNALSYM SSL_R_BAD_ECC_CERT}
  SSL_R_BAD_ECC_CERT = 304;
  {$EXTERNALSYM SSL_R_BAD_ECPOINT}
  SSL_R_BAD_ECPOINT = 306;
  {$EXTERNALSYM SSL_R_BAD_EXTENSION}
  SSL_R_BAD_EXTENSION = 110;
  {$EXTERNALSYM SSL_R_BAD_HANDSHAKE_LENGTH}
  SSL_R_BAD_HANDSHAKE_LENGTH = 332;
  {$EXTERNALSYM SSL_R_BAD_HANDSHAKE_STATE}
  SSL_R_BAD_HANDSHAKE_STATE = 236;
  {$EXTERNALSYM SSL_R_BAD_HELLO_REQUEST}
  SSL_R_BAD_HELLO_REQUEST = 105;
  {$EXTERNALSYM SSL_R_BAD_HRR_VERSION}
  SSL_R_BAD_HRR_VERSION = 263;
  {$EXTERNALSYM SSL_R_BAD_KEY_SHARE}
  SSL_R_BAD_KEY_SHARE = 108;
  {$EXTERNALSYM SSL_R_BAD_KEY_UPDATE}
  SSL_R_BAD_KEY_UPDATE = 122;
  {$EXTERNALSYM SSL_R_BAD_LEGACY_VERSION}
  SSL_R_BAD_LEGACY_VERSION = 292;
  {$EXTERNALSYM SSL_R_BAD_LENGTH}
  SSL_R_BAD_LENGTH = 271;
  {$EXTERNALSYM SSL_R_BAD_PACKET}
  SSL_R_BAD_PACKET = 240;
  {$EXTERNALSYM SSL_R_BAD_PACKET_LENGTH}
  SSL_R_BAD_PACKET_LENGTH = 115;
  {$EXTERNALSYM SSL_R_BAD_PROTOCOL_VERSION_NUMBER}
  SSL_R_BAD_PROTOCOL_VERSION_NUMBER = 116;
  {$EXTERNALSYM SSL_R_BAD_PSK}
  SSL_R_BAD_PSK = 219;
  {$EXTERNALSYM SSL_R_BAD_PSK_IDENTITY}
  SSL_R_BAD_PSK_IDENTITY = 114;
  {$EXTERNALSYM SSL_R_BAD_RECORD_TYPE}
  SSL_R_BAD_RECORD_TYPE = 443;
  {$EXTERNALSYM SSL_R_BAD_RSA_ENCRYPT}
  SSL_R_BAD_RSA_ENCRYPT = 119;
  {$EXTERNALSYM SSL_R_BAD_SIGNATURE}
  SSL_R_BAD_SIGNATURE = 123;
  {$EXTERNALSYM SSL_R_BAD_SRP_A_LENGTH}
  SSL_R_BAD_SRP_A_LENGTH = 347;
  {$EXTERNALSYM SSL_R_BAD_SRP_PARAMETERS}
  SSL_R_BAD_SRP_PARAMETERS = 371;
  {$EXTERNALSYM SSL_R_BAD_SRTP_MKI_VALUE}
  SSL_R_BAD_SRTP_MKI_VALUE = 352;
  {$EXTERNALSYM SSL_R_BAD_SRTP_PROTECTION_PROFILE_LIST}
  SSL_R_BAD_SRTP_PROTECTION_PROFILE_LIST = 353;
  {$EXTERNALSYM SSL_R_BAD_SSL_FILETYPE}
  SSL_R_BAD_SSL_FILETYPE = 124;
  {$EXTERNALSYM SSL_R_BAD_VALUE}
  SSL_R_BAD_VALUE = 384;
  {$EXTERNALSYM SSL_R_BAD_WRITE_RETRY}
  SSL_R_BAD_WRITE_RETRY = 127;
  {$EXTERNALSYM SSL_R_BINDER_DOES_NOT_VERIFY}
  SSL_R_BINDER_DOES_NOT_VERIFY = 253;
  {$EXTERNALSYM SSL_R_BIO_NOT_SET}
  SSL_R_BIO_NOT_SET = 128;
  {$EXTERNALSYM SSL_R_BLOCK_CIPHER_PAD_IS_WRONG}
  SSL_R_BLOCK_CIPHER_PAD_IS_WRONG = 129;
  {$EXTERNALSYM SSL_R_BN_LIB}
  SSL_R_BN_LIB = 130;
  {$EXTERNALSYM SSL_R_CALLBACK_FAILED}
  SSL_R_CALLBACK_FAILED = 234;
  {$EXTERNALSYM SSL_R_CANNOT_CHANGE_CIPHER}
  SSL_R_CANNOT_CHANGE_CIPHER = 109;
  {$EXTERNALSYM SSL_R_CA_DN_LENGTH_MISMATCH}
  SSL_R_CA_DN_LENGTH_MISMATCH = 131;
  {$EXTERNALSYM SSL_R_CA_KEY_TOO_SMALL}
  SSL_R_CA_KEY_TOO_SMALL = 397;
  {$EXTERNALSYM SSL_R_CA_MD_TOO_WEAK}
  SSL_R_CA_MD_TOO_WEAK = 398;
  {$EXTERNALSYM SSL_R_CCS_RECEIVED_EARLY}
  SSL_R_CCS_RECEIVED_EARLY = 133;
  {$EXTERNALSYM SSL_R_CERTIFICATE_VERIFY_FAILED}
  SSL_R_CERTIFICATE_VERIFY_FAILED = 134;
  {$EXTERNALSYM SSL_R_CERT_CB_ERROR}
  SSL_R_CERT_CB_ERROR = 377;
  {$EXTERNALSYM SSL_R_CERT_LENGTH_MISMATCH}
  SSL_R_CERT_LENGTH_MISMATCH = 135;
  {$EXTERNALSYM SSL_R_CIPHERSUITE_DIGEST_HAS_CHANGED}
  SSL_R_CIPHERSUITE_DIGEST_HAS_CHANGED = 218;
  {$EXTERNALSYM SSL_R_CIPHER_CODE_WRONG_LENGTH}
  SSL_R_CIPHER_CODE_WRONG_LENGTH = 137;
  {$EXTERNALSYM SSL_R_CIPHER_OR_HASH_UNAVAILABLE}
  SSL_R_CIPHER_OR_HASH_UNAVAILABLE = 138;
  {$EXTERNALSYM SSL_R_CLIENTHELLO_TLSEXT}
  SSL_R_CLIENTHELLO_TLSEXT = 226;
  {$EXTERNALSYM SSL_R_COMPRESSED_LENGTH_TOO_LONG}
  SSL_R_COMPRESSED_LENGTH_TOO_LONG = 140;
  {$EXTERNALSYM SSL_R_COMPRESSION_DISABLED}
  SSL_R_COMPRESSION_DISABLED = 343;
  {$EXTERNALSYM SSL_R_COMPRESSION_FAILURE}
  SSL_R_COMPRESSION_FAILURE = 141;
  {$EXTERNALSYM SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE}
  SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE = 307;
  {$EXTERNALSYM SSL_R_COMPRESSION_LIBRARY_ERROR}
  SSL_R_COMPRESSION_LIBRARY_ERROR = 142;
  {$EXTERNALSYM SSL_R_CONNECTION_TYPE_NOT_SET}
  SSL_R_CONNECTION_TYPE_NOT_SET = 144;
  {$EXTERNALSYM SSL_R_CONTEXT_NOT_DANE_ENABLED}
  SSL_R_CONTEXT_NOT_DANE_ENABLED = 167;
  {$EXTERNALSYM SSL_R_COOKIE_GEN_CALLBACK_FAILURE}
  SSL_R_COOKIE_GEN_CALLBACK_FAILURE = 400;
  {$EXTERNALSYM SSL_R_COOKIE_MISMATCH}
  SSL_R_COOKIE_MISMATCH = 308;
  {$EXTERNALSYM SSL_R_CUSTOM_EXT_HANDLER_ALREADY_INSTALLED}
  SSL_R_CUSTOM_EXT_HANDLER_ALREADY_INSTALLED = 206;
  {$EXTERNALSYM SSL_R_DANE_ALREADY_ENABLED}
  SSL_R_DANE_ALREADY_ENABLED = 172;
  {$EXTERNALSYM SSL_R_DANE_CANNOT_OVERRIDE_MTYPE_FULL}
  SSL_R_DANE_CANNOT_OVERRIDE_MTYPE_FULL = 173;
  {$EXTERNALSYM SSL_R_DANE_NOT_ENABLED}
  SSL_R_DANE_NOT_ENABLED = 175;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_CERTIFICATE}
  SSL_R_DANE_TLSA_BAD_CERTIFICATE = 180;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_CERTIFICATE_USAGE}
  SSL_R_DANE_TLSA_BAD_CERTIFICATE_USAGE = 184;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_DATA_LENGTH}
  SSL_R_DANE_TLSA_BAD_DATA_LENGTH = 189;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_DIGEST_LENGTH}
  SSL_R_DANE_TLSA_BAD_DIGEST_LENGTH = 192;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_MATCHING_TYPE}
  SSL_R_DANE_TLSA_BAD_MATCHING_TYPE = 200;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_PUBLIC_KEY}
  SSL_R_DANE_TLSA_BAD_PUBLIC_KEY = 201;
  {$EXTERNALSYM SSL_R_DANE_TLSA_BAD_SELECTOR}
  SSL_R_DANE_TLSA_BAD_SELECTOR = 202;
  {$EXTERNALSYM SSL_R_DANE_TLSA_NULL_DATA}
  SSL_R_DANE_TLSA_NULL_DATA = 203;
  {$EXTERNALSYM SSL_R_DATA_BETWEEN_CCS_AND_FINISHED}
  SSL_R_DATA_BETWEEN_CCS_AND_FINISHED = 145;
  {$EXTERNALSYM SSL_R_DATA_LENGTH_TOO_LONG}
  SSL_R_DATA_LENGTH_TOO_LONG = 146;
  {$EXTERNALSYM SSL_R_DECRYPTION_FAILED}
  SSL_R_DECRYPTION_FAILED = 147;
  {$EXTERNALSYM SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC}
  SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC = 281;
  {$EXTERNALSYM SSL_R_DH_KEY_TOO_SMALL}
  SSL_R_DH_KEY_TOO_SMALL = 394;
  {$EXTERNALSYM SSL_R_DH_PUBLIC_VALUE_LENGTH_IS_WRONG}
  SSL_R_DH_PUBLIC_VALUE_LENGTH_IS_WRONG = 148;
  {$EXTERNALSYM SSL_R_DIGEST_CHECK_FAILED}
  SSL_R_DIGEST_CHECK_FAILED = 149;
  {$EXTERNALSYM SSL_R_DTLS_MESSAGE_TOO_BIG}
  SSL_R_DTLS_MESSAGE_TOO_BIG = 334;
  {$EXTERNALSYM SSL_R_DUPLICATE_COMPRESSION_ID}
  SSL_R_DUPLICATE_COMPRESSION_ID = 309;
  {$EXTERNALSYM SSL_R_ECC_CERT_NOT_FOR_SIGNING}
  SSL_R_ECC_CERT_NOT_FOR_SIGNING = 318;
  {$EXTERNALSYM SSL_R_ECDH_REQUIRED_FOR_SUITEB_MODE}
  SSL_R_ECDH_REQUIRED_FOR_SUITEB_MODE = 374;
  {$EXTERNALSYM SSL_R_EE_KEY_TOO_SMALL}
  SSL_R_EE_KEY_TOO_SMALL = 399;
  {$EXTERNALSYM SSL_R_EMPTY_SRTP_PROTECTION_PROFILE_LIST}
  SSL_R_EMPTY_SRTP_PROTECTION_PROFILE_LIST = 354;
  {$EXTERNALSYM SSL_R_ENCRYPTED_LENGTH_TOO_LONG}
  SSL_R_ENCRYPTED_LENGTH_TOO_LONG = 150;
  {$EXTERNALSYM SSL_R_ERROR_IN_RECEIVED_CIPHER_LIST}
  SSL_R_ERROR_IN_RECEIVED_CIPHER_LIST = 151;
  {$EXTERNALSYM SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN}
  SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN = 204;
  {$EXTERNALSYM SSL_R_EXCEEDS_MAX_FRAGMENT_SIZE}
  SSL_R_EXCEEDS_MAX_FRAGMENT_SIZE = 194;
  {$EXTERNALSYM SSL_R_EXCESSIVE_MESSAGE_SIZE}
  SSL_R_EXCESSIVE_MESSAGE_SIZE = 152;
  {$EXTERNALSYM SSL_R_EXTENSION_NOT_RECEIVED}
  SSL_R_EXTENSION_NOT_RECEIVED = 279;
  {$EXTERNALSYM SSL_R_EXTRA_DATA_IN_MESSAGE}
  SSL_R_EXTRA_DATA_IN_MESSAGE = 153;
  {$EXTERNALSYM SSL_R_EXT_LENGTH_MISMATCH}
  SSL_R_EXT_LENGTH_MISMATCH = 163;
  {$EXTERNALSYM SSL_R_FAILED_TO_INIT_ASYNC}
  SSL_R_FAILED_TO_INIT_ASYNC = 405;
  {$EXTERNALSYM SSL_R_FRAGMENTED_CLIENT_HELLO}
  SSL_R_FRAGMENTED_CLIENT_HELLO = 401;
  {$EXTERNALSYM SSL_R_GOT_A_FIN_BEFORE_A_CCS}
  SSL_R_GOT_A_FIN_BEFORE_A_CCS = 154;
  {$EXTERNALSYM SSL_R_HTTPS_PROXY_REQUEST}
  SSL_R_HTTPS_PROXY_REQUEST = 155;
  {$EXTERNALSYM SSL_R_HTTP_REQUEST}
  SSL_R_HTTP_REQUEST = 156;
  {$EXTERNALSYM SSL_R_ILLEGAL_POINT_COMPRESSION}
  SSL_R_ILLEGAL_POINT_COMPRESSION = 162;
  {$EXTERNALSYM SSL_R_ILLEGAL_SUITEB_DIGEST}
  SSL_R_ILLEGAL_SUITEB_DIGEST = 380;
  {$EXTERNALSYM SSL_R_INAPPROPRIATE_FALLBACK}
  SSL_R_INAPPROPRIATE_FALLBACK = 373;
  {$EXTERNALSYM SSL_R_INCONSISTENT_COMPRESSION}
  SSL_R_INCONSISTENT_COMPRESSION = 340;
  {$EXTERNALSYM SSL_R_INCONSISTENT_EARLY_DATA_ALPN}
  SSL_R_INCONSISTENT_EARLY_DATA_ALPN = 222;
  {$EXTERNALSYM SSL_R_INCONSISTENT_EARLY_DATA_SNI}
  SSL_R_INCONSISTENT_EARLY_DATA_SNI = 231;
  {$EXTERNALSYM SSL_R_INCONSISTENT_EXTMS}
  SSL_R_INCONSISTENT_EXTMS = 104;
  {$EXTERNALSYM SSL_R_INSUFFICIENT_SECURITY}
  SSL_R_INSUFFICIENT_SECURITY = 241;
  {$EXTERNALSYM SSL_R_INVALID_ALERT}
  SSL_R_INVALID_ALERT = 205;
  {$EXTERNALSYM SSL_R_INVALID_CCS_MESSAGE}
  SSL_R_INVALID_CCS_MESSAGE = 260;
  {$EXTERNALSYM SSL_R_INVALID_CERTIFICATE_OR_ALG}
  SSL_R_INVALID_CERTIFICATE_OR_ALG = 238;
  {$EXTERNALSYM SSL_R_INVALID_COMMAND}
  SSL_R_INVALID_COMMAND = 280;
  {$EXTERNALSYM SSL_R_INVALID_COMPRESSION_ALGORITHM}
  SSL_R_INVALID_COMPRESSION_ALGORITHM = 341;
  {$EXTERNALSYM SSL_R_INVALID_CONFIG}
  SSL_R_INVALID_CONFIG = 283;
  {$EXTERNALSYM SSL_R_INVALID_CONFIGURATION_NAME}
  SSL_R_INVALID_CONFIGURATION_NAME = 113;
  {$EXTERNALSYM SSL_R_INVALID_CONTEXT}
  SSL_R_INVALID_CONTEXT = 282;
  {$EXTERNALSYM SSL_R_INVALID_CT_VALIDATION_TYPE}
  SSL_R_INVALID_CT_VALIDATION_TYPE = 212;
  {$EXTERNALSYM SSL_R_INVALID_KEY_UPDATE_TYPE}
  SSL_R_INVALID_KEY_UPDATE_TYPE = 120;
  {$EXTERNALSYM SSL_R_INVALID_MAX_EARLY_DATA}
  SSL_R_INVALID_MAX_EARLY_DATA = 174;
  {$EXTERNALSYM SSL_R_INVALID_NULL_CMD_NAME}
  SSL_R_INVALID_NULL_CMD_NAME = 385;
  {$EXTERNALSYM SSL_R_INVALID_SEQUENCE_NUMBER}
  SSL_R_INVALID_SEQUENCE_NUMBER = 402;
  {$EXTERNALSYM SSL_R_INVALID_SERVERINFO_DATA}
  SSL_R_INVALID_SERVERINFO_DATA = 388;
  {$EXTERNALSYM SSL_R_INVALID_SESSION_ID}
  SSL_R_INVALID_SESSION_ID = 999;
  {$EXTERNALSYM SSL_R_INVALID_SRP_USERNAME}
  SSL_R_INVALID_SRP_USERNAME = 357;
  {$EXTERNALSYM SSL_R_INVALID_STATUS_RESPONSE}
  SSL_R_INVALID_STATUS_RESPONSE = 328;
  {$EXTERNALSYM SSL_R_INVALID_TICKET_KEYS_LENGTH}
  SSL_R_INVALID_TICKET_KEYS_LENGTH = 325;
  {$EXTERNALSYM SSL_R_LENGTH_MISMATCH}
  SSL_R_LENGTH_MISMATCH = 159;
  {$EXTERNALSYM SSL_R_LENGTH_TOO_LONG}
  SSL_R_LENGTH_TOO_LONG = 404;
  {$EXTERNALSYM SSL_R_LENGTH_TOO_SHORT}
  SSL_R_LENGTH_TOO_SHORT = 160;
  {$EXTERNALSYM SSL_R_LIBRARY_BUG}
  SSL_R_LIBRARY_BUG = 274;
  {$EXTERNALSYM SSL_R_LIBRARY_HAS_NO_CIPHERS}
  SSL_R_LIBRARY_HAS_NO_CIPHERS = 161;
  {$EXTERNALSYM SSL_R_MISSING_DSA_SIGNING_CERT}
  SSL_R_MISSING_DSA_SIGNING_CERT = 165;
  {$EXTERNALSYM SSL_R_MISSING_ECDSA_SIGNING_CERT}
  SSL_R_MISSING_ECDSA_SIGNING_CERT = 381;
  {$EXTERNALSYM SSL_R_MISSING_FATAL}
  SSL_R_MISSING_FATAL = 256;
  {$EXTERNALSYM SSL_R_MISSING_PARAMETERS}
  SSL_R_MISSING_PARAMETERS = 290;
  {$EXTERNALSYM SSL_R_MISSING_RSA_CERTIFICATE}
  SSL_R_MISSING_RSA_CERTIFICATE = 168;
  {$EXTERNALSYM SSL_R_MISSING_RSA_ENCRYPTING_CERT}
  SSL_R_MISSING_RSA_ENCRYPTING_CERT = 169;
  {$EXTERNALSYM SSL_R_MISSING_RSA_SIGNING_CERT}
  SSL_R_MISSING_RSA_SIGNING_CERT = 170;
  {$EXTERNALSYM SSL_R_MISSING_SIGALGS_EXTENSION}
  SSL_R_MISSING_SIGALGS_EXTENSION = 112;
  {$EXTERNALSYM SSL_R_MISSING_SIGNING_CERT}
  SSL_R_MISSING_SIGNING_CERT = 221;
  {$EXTERNALSYM SSL_R_MISSING_SRP_PARAM}
  SSL_R_MISSING_SRP_PARAM = 358;
  {$EXTERNALSYM SSL_R_MISSING_SUPPORTED_GROUPS_EXTENSION}
  SSL_R_MISSING_SUPPORTED_GROUPS_EXTENSION = 209;
  {$EXTERNALSYM SSL_R_MISSING_TMP_DH_KEY}
  SSL_R_MISSING_TMP_DH_KEY = 171;
  {$EXTERNALSYM SSL_R_MISSING_TMP_ECDH_KEY}
  SSL_R_MISSING_TMP_ECDH_KEY = 311;
  {$EXTERNALSYM SSL_R_MIXED_HANDSHAKE_AND_NON_HANDSHAKE_DATA}
  SSL_R_MIXED_HANDSHAKE_AND_NON_HANDSHAKE_DATA = 293;
  {$EXTERNALSYM SSL_R_NOT_ON_RECORD_BOUNDARY}
  SSL_R_NOT_ON_RECORD_BOUNDARY = 182;
  {$EXTERNALSYM SSL_R_NOT_REPLACING_CERTIFICATE}
  SSL_R_NOT_REPLACING_CERTIFICATE = 289;
  {$EXTERNALSYM SSL_R_NOT_SERVER}
  SSL_R_NOT_SERVER = 284;
  {$EXTERNALSYM SSL_R_NO_APPLICATION_PROTOCOL}
  SSL_R_NO_APPLICATION_PROTOCOL = 235;
  {$EXTERNALSYM SSL_R_NO_CERTIFICATES_RETURNED}
  SSL_R_NO_CERTIFICATES_RETURNED = 176;
  {$EXTERNALSYM SSL_R_NO_CERTIFICATE_ASSIGNED}
  SSL_R_NO_CERTIFICATE_ASSIGNED = 177;
  {$EXTERNALSYM SSL_R_NO_CERTIFICATE_SET}
  SSL_R_NO_CERTIFICATE_SET = 179;
  {$EXTERNALSYM SSL_R_NO_CHANGE_FOLLOWING_HRR}
  SSL_R_NO_CHANGE_FOLLOWING_HRR = 214;
  {$EXTERNALSYM SSL_R_NO_CIPHERS_AVAILABLE}
  SSL_R_NO_CIPHERS_AVAILABLE = 181;
  {$EXTERNALSYM SSL_R_NO_CIPHERS_SPECIFIED}
  SSL_R_NO_CIPHERS_SPECIFIED = 183;
  {$EXTERNALSYM SSL_R_NO_CIPHER_MATCH}
  SSL_R_NO_CIPHER_MATCH = 185;
  {$EXTERNALSYM SSL_R_NO_CLIENT_CERT_METHOD}
  SSL_R_NO_CLIENT_CERT_METHOD = 331;
  {$EXTERNALSYM SSL_R_NO_COMPRESSION_SPECIFIED}
  SSL_R_NO_COMPRESSION_SPECIFIED = 187;
  {$EXTERNALSYM SSL_R_NO_COOKIE_CALLBACK_SET}
  SSL_R_NO_COOKIE_CALLBACK_SET = 287;
  {$EXTERNALSYM SSL_R_NO_GOST_CERTIFICATE_SENT_BY_PEER}
  SSL_R_NO_GOST_CERTIFICATE_SENT_BY_PEER = 330;
  {$EXTERNALSYM SSL_R_NO_METHOD_SPECIFIED}
  SSL_R_NO_METHOD_SPECIFIED = 188;
  {$EXTERNALSYM SSL_R_NO_PEM_EXTENSIONS}
  SSL_R_NO_PEM_EXTENSIONS = 389;
  {$EXTERNALSYM SSL_R_NO_PRIVATE_KEY_ASSIGNED}
  SSL_R_NO_PRIVATE_KEY_ASSIGNED = 190;
  {$EXTERNALSYM SSL_R_NO_PROTOCOLS_AVAILABLE}
  SSL_R_NO_PROTOCOLS_AVAILABLE = 191;
  {$EXTERNALSYM SSL_R_NO_RENEGOTIATION}
  SSL_R_NO_RENEGOTIATION = 339;
  {$EXTERNALSYM SSL_R_NO_REQUIRED_DIGEST}
  SSL_R_NO_REQUIRED_DIGEST = 324;
  {$EXTERNALSYM SSL_R_NO_SHARED_CIPHER}
  SSL_R_NO_SHARED_CIPHER = 193;
  {$EXTERNALSYM SSL_R_NO_SHARED_GROUPS}
  SSL_R_NO_SHARED_GROUPS = 410;
  {$EXTERNALSYM SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS}
  SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS = 376;
  {$EXTERNALSYM SSL_R_NO_SRTP_PROFILES}
  SSL_R_NO_SRTP_PROFILES = 359;
  {$EXTERNALSYM SSL_R_NO_SUITABLE_KEY_SHARE}
  SSL_R_NO_SUITABLE_KEY_SHARE = 101;
  {$EXTERNALSYM SSL_R_NO_SUITABLE_SIGNATURE_ALGORITHM}
  SSL_R_NO_SUITABLE_SIGNATURE_ALGORITHM = 118;
  {$EXTERNALSYM SSL_R_NO_VALID_SCTS}
  SSL_R_NO_VALID_SCTS = 216;
  {$EXTERNALSYM SSL_R_NO_VERIFY_COOKIE_CALLBACK}
  SSL_R_NO_VERIFY_COOKIE_CALLBACK = 403;
  {$EXTERNALSYM SSL_R_NULL_SSL_CTX}
  SSL_R_NULL_SSL_CTX = 195;
  {$EXTERNALSYM SSL_R_NULL_SSL_METHOD_PASSED}
  SSL_R_NULL_SSL_METHOD_PASSED = 196;
  {$EXTERNALSYM SSL_R_OLD_SESSION_CIPHER_NOT_RETURNED}
  SSL_R_OLD_SESSION_CIPHER_NOT_RETURNED = 197;
  {$EXTERNALSYM SSL_R_OLD_SESSION_COMPRESSION_ALGORITHM_NOT_RETURNED}
  SSL_R_OLD_SESSION_COMPRESSION_ALGORITHM_NOT_RETURNED = 344;
  {$EXTERNALSYM SSL_R_OVERFLOW_ERROR}
  SSL_R_OVERFLOW_ERROR = 237;
  {$EXTERNALSYM SSL_R_PACKET_LENGTH_TOO_LONG}
  SSL_R_PACKET_LENGTH_TOO_LONG = 198;
  {$EXTERNALSYM SSL_R_PARSE_TLSEXT}
  SSL_R_PARSE_TLSEXT = 227;
  {$EXTERNALSYM SSL_R_PATH_TOO_LONG}
  SSL_R_PATH_TOO_LONG = 270;
  {$EXTERNALSYM SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE}
  SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE = 199;
  {$EXTERNALSYM SSL_R_PEM_NAME_BAD_PREFIX}
  SSL_R_PEM_NAME_BAD_PREFIX = 391;
  {$EXTERNALSYM SSL_R_PEM_NAME_TOO_SHORT}
  SSL_R_PEM_NAME_TOO_SHORT = 392;
  {$EXTERNALSYM SSL_R_PIPELINE_FAILURE}
  SSL_R_PIPELINE_FAILURE = 406;
  {$EXTERNALSYM SSL_R_POST_HANDSHAKE_AUTH_ENCODING_ERR}
  SSL_R_POST_HANDSHAKE_AUTH_ENCODING_ERR = 278;
  {$EXTERNALSYM SSL_R_PRIVATE_KEY_MISMATCH}
  SSL_R_PRIVATE_KEY_MISMATCH = 288;
  {$EXTERNALSYM SSL_R_PROTOCOL_IS_SHUTDOWN}
  SSL_R_PROTOCOL_IS_SHUTDOWN = 207;
  {$EXTERNALSYM SSL_R_PSK_IDENTITY_NOT_FOUND}
  SSL_R_PSK_IDENTITY_NOT_FOUND = 223;
  {$EXTERNALSYM SSL_R_PSK_NO_CLIENT_CB}
  SSL_R_PSK_NO_CLIENT_CB = 224;
  {$EXTERNALSYM SSL_R_PSK_NO_SERVER_CB}
  SSL_R_PSK_NO_SERVER_CB = 225;
  {$EXTERNALSYM SSL_R_READ_BIO_NOT_SET}
  SSL_R_READ_BIO_NOT_SET = 211;
  {$EXTERNALSYM SSL_R_READ_TIMEOUT_EXPIRED}
  SSL_R_READ_TIMEOUT_EXPIRED = 312;
  {$EXTERNALSYM SSL_R_RECORD_LENGTH_MISMATCH}
  SSL_R_RECORD_LENGTH_MISMATCH = 213;
  {$EXTERNALSYM SSL_R_RECORD_TOO_SMALL}
  SSL_R_RECORD_TOO_SMALL = 298;
  {$EXTERNALSYM SSL_R_RENEGOTIATE_EXT_TOO_LONG}
  SSL_R_RENEGOTIATE_EXT_TOO_LONG = 335;
  {$EXTERNALSYM SSL_R_RENEGOTIATION_ENCODING_ERR}
  SSL_R_RENEGOTIATION_ENCODING_ERR = 336;
  {$EXTERNALSYM SSL_R_RENEGOTIATION_MISMATCH}
  SSL_R_RENEGOTIATION_MISMATCH = 337;
  {$EXTERNALSYM SSL_R_REQUEST_PENDING}
  SSL_R_REQUEST_PENDING = 285;
  {$EXTERNALSYM SSL_R_REQUEST_SENT}
  SSL_R_REQUEST_SENT = 286;
  {$EXTERNALSYM SSL_R_REQUIRED_CIPHER_MISSING}
  SSL_R_REQUIRED_CIPHER_MISSING = 215;
  {$EXTERNALSYM SSL_R_REQUIRED_COMPRESSION_ALGORITHM_MISSING}
  SSL_R_REQUIRED_COMPRESSION_ALGORITHM_MISSING = 342;
  {$EXTERNALSYM SSL_R_SCSV_RECEIVED_WHEN_RENEGOTIATING}
  SSL_R_SCSV_RECEIVED_WHEN_RENEGOTIATING = 345;
  {$EXTERNALSYM SSL_R_SCT_VERIFICATION_FAILED}
  SSL_R_SCT_VERIFICATION_FAILED = 208;
  {$EXTERNALSYM SSL_R_SERVERHELLO_TLSEXT}
  SSL_R_SERVERHELLO_TLSEXT = 275;
  {$EXTERNALSYM SSL_R_SESSION_ID_CONTEXT_UNINITIALIZED}
  SSL_R_SESSION_ID_CONTEXT_UNINITIALIZED = 277;
  {$EXTERNALSYM SSL_R_SHUTDOWN_WHILE_IN_INIT}
  SSL_R_SHUTDOWN_WHILE_IN_INIT = 407;
  {$EXTERNALSYM SSL_R_SIGNATURE_ALGORITHMS_ERROR}
  SSL_R_SIGNATURE_ALGORITHMS_ERROR = 360;
  {$EXTERNALSYM SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE}
  SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE = 220;
  {$EXTERNALSYM SSL_R_SRP_A_CALC}
  SSL_R_SRP_A_CALC = 361;
  {$EXTERNALSYM SSL_R_SRTP_COULD_NOT_ALLOCATE_PROFILES}
  SSL_R_SRTP_COULD_NOT_ALLOCATE_PROFILES = 362;
  {$EXTERNALSYM SSL_R_SRTP_PROTECTION_PROFILE_LIST_TOO_LONG}
  SSL_R_SRTP_PROTECTION_PROFILE_LIST_TOO_LONG = 363;
  {$EXTERNALSYM SSL_R_SRTP_UNKNOWN_PROTECTION_PROFILE}
  SSL_R_SRTP_UNKNOWN_PROTECTION_PROFILE = 364;
  {$EXTERNALSYM SSL_R_SSL3_EXT_INVALID_MAX_FRAGMENT_LENGTH}
  SSL_R_SSL3_EXT_INVALID_MAX_FRAGMENT_LENGTH = 232;
  {$EXTERNALSYM SSL_R_SSL3_EXT_INVALID_SERVERNAME}
  SSL_R_SSL3_EXT_INVALID_SERVERNAME = 319;
  {$EXTERNALSYM SSL_R_SSL3_EXT_INVALID_SERVERNAME_TYPE}
  SSL_R_SSL3_EXT_INVALID_SERVERNAME_TYPE = 320;
  {$EXTERNALSYM SSL_R_SSL3_SESSION_ID_TOO_LONG}
  SSL_R_SSL3_SESSION_ID_TOO_LONG = 300;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_BAD_CERTIFICATE}
  SSL_R_SSLV3_ALERT_BAD_CERTIFICATE = 1042;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_BAD_RECORD_MAC}
  SSL_R_SSLV3_ALERT_BAD_RECORD_MAC = 1020;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_CERTIFICATE_EXPIRED}
  SSL_R_SSLV3_ALERT_CERTIFICATE_EXPIRED = 1045;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_CERTIFICATE_REVOKED}
  SSL_R_SSLV3_ALERT_CERTIFICATE_REVOKED = 1044;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN}
  SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN = 1046;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_DECOMPRESSION_FAILURE}
  SSL_R_SSLV3_ALERT_DECOMPRESSION_FAILURE = 1030;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_HANDSHAKE_FAILURE}
  SSL_R_SSLV3_ALERT_HANDSHAKE_FAILURE = 1040;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_ILLEGAL_PARAMETER}
  SSL_R_SSLV3_ALERT_ILLEGAL_PARAMETER = 1047;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_NO_CERTIFICATE}
  SSL_R_SSLV3_ALERT_NO_CERTIFICATE = 1041;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE}
  SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE = 1010;
  {$EXTERNALSYM SSL_R_SSLV3_ALERT_UNSUPPORTED_CERTIFICATE}
  SSL_R_SSLV3_ALERT_UNSUPPORTED_CERTIFICATE = 1043;
  {$EXTERNALSYM SSL_R_SSL_COMMAND_SECTION_EMPTY}
  SSL_R_SSL_COMMAND_SECTION_EMPTY = 117;
  {$EXTERNALSYM SSL_R_SSL_COMMAND_SECTION_NOT_FOUND}
  SSL_R_SSL_COMMAND_SECTION_NOT_FOUND = 125;
  {$EXTERNALSYM SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION}
  SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION = 228;
  {$EXTERNALSYM SSL_R_SSL_HANDSHAKE_FAILURE}
  SSL_R_SSL_HANDSHAKE_FAILURE = 229;
  {$EXTERNALSYM SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS}
  SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS = 230;
  {$EXTERNALSYM SSL_R_SSL_NEGATIVE_LENGTH}
  SSL_R_SSL_NEGATIVE_LENGTH = 372;
  {$EXTERNALSYM SSL_R_SSL_SECTION_EMPTY}
  SSL_R_SSL_SECTION_EMPTY = 126;
  {$EXTERNALSYM SSL_R_SSL_SECTION_NOT_FOUND}
  SSL_R_SSL_SECTION_NOT_FOUND = 136;
  {$EXTERNALSYM SSL_R_SSL_SESSION_ID_CALLBACK_FAILED}
  SSL_R_SSL_SESSION_ID_CALLBACK_FAILED = 301;
  {$EXTERNALSYM SSL_R_SSL_SESSION_ID_CONFLICT}
  SSL_R_SSL_SESSION_ID_CONFLICT = 302;
  {$EXTERNALSYM SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG}
  SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG = 273;
  {$EXTERNALSYM SSL_R_SSL_SESSION_ID_HAS_BAD_LENGTH}
  SSL_R_SSL_SESSION_ID_HAS_BAD_LENGTH = 303;
  {$EXTERNALSYM SSL_R_SSL_SESSION_ID_TOO_LONG}
  SSL_R_SSL_SESSION_ID_TOO_LONG = 408;
  {$EXTERNALSYM SSL_R_SSL_SESSION_VERSION_MISMATCH}
  SSL_R_SSL_SESSION_VERSION_MISMATCH = 210;
  {$EXTERNALSYM SSL_R_STILL_IN_INIT}
  SSL_R_STILL_IN_INIT = 121;
  {$EXTERNALSYM SSL_R_TLSV13_ALERT_CERTIFICATE_REQUIRED}
  SSL_R_TLSV13_ALERT_CERTIFICATE_REQUIRED = 1116;
  {$EXTERNALSYM SSL_R_TLSV13_ALERT_MISSING_EXTENSION}
  SSL_R_TLSV13_ALERT_MISSING_EXTENSION = 1109;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_ACCESS_DENIED}
  SSL_R_TLSV1_ALERT_ACCESS_DENIED = 1049;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_DECODE_ERROR}
  SSL_R_TLSV1_ALERT_DECODE_ERROR = 1050;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_DECRYPTION_FAILED}
  SSL_R_TLSV1_ALERT_DECRYPTION_FAILED = 1021;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_DECRYPT_ERROR}
  SSL_R_TLSV1_ALERT_DECRYPT_ERROR = 1051;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_EXPORT_RESTRICTION}
  SSL_R_TLSV1_ALERT_EXPORT_RESTRICTION = 1060;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_INAPPROPRIATE_FALLBACK}
  SSL_R_TLSV1_ALERT_INAPPROPRIATE_FALLBACK = 1086;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY}
  SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY = 1071;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_INTERNAL_ERROR}
  SSL_R_TLSV1_ALERT_INTERNAL_ERROR = 1080;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_NO_RENEGOTIATION}
  SSL_R_TLSV1_ALERT_NO_RENEGOTIATION = 1100;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_PROTOCOL_VERSION}
  SSL_R_TLSV1_ALERT_PROTOCOL_VERSION = 1070;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_RECORD_OVERFLOW}
  SSL_R_TLSV1_ALERT_RECORD_OVERFLOW = 1022;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_UNKNOWN_CA}
  SSL_R_TLSV1_ALERT_UNKNOWN_CA = 1048;
  {$EXTERNALSYM SSL_R_TLSV1_ALERT_USER_CANCELLED}
  SSL_R_TLSV1_ALERT_USER_CANCELLED = 1090;
  {$EXTERNALSYM SSL_R_TLSV1_BAD_CERTIFICATE_HASH_VALUE}
  SSL_R_TLSV1_BAD_CERTIFICATE_HASH_VALUE = 1114;
  {$EXTERNALSYM SSL_R_TLSV1_BAD_CERTIFICATE_STATUS_RESPONSE}
  SSL_R_TLSV1_BAD_CERTIFICATE_STATUS_RESPONSE = 1113;
  {$EXTERNALSYM SSL_R_TLSV1_CERTIFICATE_UNOBTAINABLE}
  SSL_R_TLSV1_CERTIFICATE_UNOBTAINABLE = 1111;
  {$EXTERNALSYM SSL_R_TLSV1_UNRECOGNIZED_NAME}
  SSL_R_TLSV1_UNRECOGNIZED_NAME = 1112;
  {$EXTERNALSYM SSL_R_TLSV1_UNSUPPORTED_EXTENSION}
  SSL_R_TLSV1_UNSUPPORTED_EXTENSION = 1110;
  {$EXTERNALSYM SSL_R_TLS_HEARTBEAT_PEER_DOESNT_ACCEPT}
  SSL_R_TLS_HEARTBEAT_PEER_DOESNT_ACCEPT = 365;
  {$EXTERNALSYM SSL_R_TLS_HEARTBEAT_PENDING}
  SSL_R_TLS_HEARTBEAT_PENDING = 366;
  {$EXTERNALSYM SSL_R_TLS_ILLEGAL_EXPORTER_LABEL}
  SSL_R_TLS_ILLEGAL_EXPORTER_LABEL = 367;
  {$EXTERNALSYM SSL_R_TLS_INVALID_ECPOINTFORMAT_LIST}
  SSL_R_TLS_INVALID_ECPOINTFORMAT_LIST = 157;
  {$EXTERNALSYM SSL_R_TOO_MANY_KEY_UPDATES}
  SSL_R_TOO_MANY_KEY_UPDATES = 132;
  {$EXTERNALSYM SSL_R_TOO_MANY_WARN_ALERTS}
  SSL_R_TOO_MANY_WARN_ALERTS = 409;
  {$EXTERNALSYM SSL_R_TOO_MUCH_EARLY_DATA}
  SSL_R_TOO_MUCH_EARLY_DATA = 164;
  {$EXTERNALSYM SSL_R_UNABLE_TO_FIND_ECDH_PARAMETERS}
  SSL_R_UNABLE_TO_FIND_ECDH_PARAMETERS = 314;
  {$EXTERNALSYM SSL_R_UNABLE_TO_FIND_PUBLIC_KEY_PARAMETERS}
  SSL_R_UNABLE_TO_FIND_PUBLIC_KEY_PARAMETERS = 239;
  {$EXTERNALSYM SSL_R_UNABLE_TO_LOAD_SSL3_MD5_ROUTINES}
  SSL_R_UNABLE_TO_LOAD_SSL3_MD5_ROUTINES = 242;
  {$EXTERNALSYM SSL_R_UNABLE_TO_LOAD_SSL3_SHA1_ROUTINES}
  SSL_R_UNABLE_TO_LOAD_SSL3_SHA1_ROUTINES = 243;
  {$EXTERNALSYM SSL_R_UNEXPECTED_CCS_MESSAGE}
  SSL_R_UNEXPECTED_CCS_MESSAGE = 262;
  {$EXTERNALSYM SSL_R_UNEXPECTED_END_OF_EARLY_DATA}
  SSL_R_UNEXPECTED_END_OF_EARLY_DATA = 178;
  {$EXTERNALSYM SSL_R_UNEXPECTED_MESSAGE}
  SSL_R_UNEXPECTED_MESSAGE = 244;
  {$EXTERNALSYM SSL_R_UNEXPECTED_RECORD}
  SSL_R_UNEXPECTED_RECORD = 245;
  {$EXTERNALSYM SSL_R_UNINITIALIZED}
  SSL_R_UNINITIALIZED = 276;
  {$EXTERNALSYM SSL_R_UNKNOWN_ALERT_TYPE}
  SSL_R_UNKNOWN_ALERT_TYPE = 246;
  {$EXTERNALSYM SSL_R_UNKNOWN_CERTIFICATE_TYPE}
  SSL_R_UNKNOWN_CERTIFICATE_TYPE = 247;
  {$EXTERNALSYM SSL_R_UNKNOWN_CIPHER_RETURNED}
  SSL_R_UNKNOWN_CIPHER_RETURNED = 248;
  {$EXTERNALSYM SSL_R_UNKNOWN_CIPHER_TYPE}
  SSL_R_UNKNOWN_CIPHER_TYPE = 249;
  {$EXTERNALSYM SSL_R_UNKNOWN_CMD_NAME}
  SSL_R_UNKNOWN_CMD_NAME = 386;
  {$EXTERNALSYM SSL_R_UNKNOWN_COMMAND}
  SSL_R_UNKNOWN_COMMAND = 139;
  {$EXTERNALSYM SSL_R_UNKNOWN_DIGEST}
  SSL_R_UNKNOWN_DIGEST = 368;
  {$EXTERNALSYM SSL_R_UNKNOWN_KEY_EXCHANGE_TYPE}
  SSL_R_UNKNOWN_KEY_EXCHANGE_TYPE = 250;
  {$EXTERNALSYM SSL_R_UNKNOWN_PKEY_TYPE}
  SSL_R_UNKNOWN_PKEY_TYPE = 251;
  {$EXTERNALSYM SSL_R_UNKNOWN_PROTOCOL}
  SSL_R_UNKNOWN_PROTOCOL = 252;
  {$EXTERNALSYM SSL_R_UNKNOWN_SSL_VERSION}
  SSL_R_UNKNOWN_SSL_VERSION = 254;
  {$EXTERNALSYM SSL_R_UNKNOWN_STATE}
  SSL_R_UNKNOWN_STATE = 255;
  {$EXTERNALSYM SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED}
  SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED = 338;
  {$EXTERNALSYM SSL_R_UNSOLICITED_EXTENSION}
  SSL_R_UNSOLICITED_EXTENSION = 217;
  {$EXTERNALSYM SSL_R_UNSUPPORTED_COMPRESSION_ALGORITHM}
  SSL_R_UNSUPPORTED_COMPRESSION_ALGORITHM = 257;
  {$EXTERNALSYM SSL_R_UNSUPPORTED_ELLIPTIC_CURVE}
  SSL_R_UNSUPPORTED_ELLIPTIC_CURVE = 315;
  {$EXTERNALSYM SSL_R_UNSUPPORTED_PROTOCOL}
  SSL_R_UNSUPPORTED_PROTOCOL = 258;
  {$EXTERNALSYM SSL_R_UNSUPPORTED_SSL_VERSION}
  SSL_R_UNSUPPORTED_SSL_VERSION = 259;
  {$EXTERNALSYM SSL_R_UNSUPPORTED_STATUS_TYPE}
  SSL_R_UNSUPPORTED_STATUS_TYPE = 329;
  {$EXTERNALSYM SSL_R_USE_SRTP_NOT_NEGOTIATED}
  SSL_R_USE_SRTP_NOT_NEGOTIATED = 369;
  {$EXTERNALSYM SSL_R_VERSION_TOO_HIGH}
  SSL_R_VERSION_TOO_HIGH = 166;
  {$EXTERNALSYM SSL_R_VERSION_TOO_LOW}
  SSL_R_VERSION_TOO_LOW = 396;
  {$EXTERNALSYM SSL_R_WRONG_CERTIFICATE_TYPE}
  SSL_R_WRONG_CERTIFICATE_TYPE = 383;
  {$EXTERNALSYM SSL_R_WRONG_CIPHER_RETURNED}
  SSL_R_WRONG_CIPHER_RETURNED = 261;
  {$EXTERNALSYM SSL_R_WRONG_CURVE}
  SSL_R_WRONG_CURVE = 378;
  {$EXTERNALSYM SSL_R_WRONG_SIGNATURE_LENGTH}
  SSL_R_WRONG_SIGNATURE_LENGTH = 264;
  {$EXTERNALSYM SSL_R_WRONG_SIGNATURE_SIZE}
  SSL_R_WRONG_SIGNATURE_SIZE = 265;
  {$EXTERNALSYM SSL_R_WRONG_SIGNATURE_TYPE}
  SSL_R_WRONG_SIGNATURE_TYPE = 370;
  {$EXTERNALSYM SSL_R_WRONG_SSL_VERSION}
  SSL_R_WRONG_SSL_VERSION = 266;
  {$EXTERNALSYM SSL_R_WRONG_VERSION_NUMBER}
  SSL_R_WRONG_VERSION_NUMBER = 267;
  {$EXTERNALSYM SSL_R_X509_LIB}
  SSL_R_X509_LIB = 268;
  {$EXTERNALSYM SSL_R_X509_VERIFICATION_SETUP_PROBLEMS}
  SSL_R_X509_VERIFICATION_SETUP_PROBLEMS = 269;
  {$EXTERNALSYM SSL_R_UNEXPECTED_EOF_WHILE_READING}
  SSL_R_UNEXPECTED_EOF_WHILE_READING = 294;

    { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:
		
  	  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header 
	  files generated for C++. }
	  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
var
  ERR_load_SSL_strings: function : TIdC_INT; cdecl = nil;

{$ELSE}
  function ERR_load_SSL_strings: TIdC_INT cdecl; external CLibSSL;

{$ENDIF}

implementation

  uses
    classes, 
    TaurusTLSExceptionHandlers
  {$IFNDEF OPENSSL_STATIC_LINK_MODEL}
    ,TaurusTLSLoader
  {$ENDIF};

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
const
  ERR_load_SSL_strings_procname = 'ERR_load_SSL_strings';

  {$IFNDEF _FIXINSIGHT_}
  {$I TaurusTLSNoRetValOff.inc} 
function  ERR_ERR_load_SSL_strings: TIdC_INT; cdecl;
begin
  ETaurusTLSAPIFunctionNotPresent.RaiseException(ERR_load_SSL_strings_procname);
end;



  {$I TaurusTLSNoRetValOn.inc} 

  {$I TaurusTLSUnusedParamOff.inc}
procedure Load(const ADllHandle: TIdLibHandle; LibVersion: TIdC_UINT; const AFailed: TStringList);

var FuncLoadError: boolean;

begin
  ERR_load_SSL_strings := LoadLibFunction(ADllHandle, ERR_load_SSL_strings_procname);
  FuncLoadError := not assigned(ERR_load_SSL_strings);
  if FuncLoadError then
  begin
    {$if not defined(ERR_load_SSL_strings_allownil)}
    ERR_load_SSL_strings := ERR_ERR_load_SSL_strings;
    {$ifend}
    {$if declared(ERR_load_SSL_strings_introduced)}
    if LibVersion < ERR_load_SSL_strings_introduced then
    begin
      {$if declared(FC_ERR_load_SSL_strings)}
      ERR_load_SSL_strings := FC_ERR_load_SSL_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if declared(ERR_load_SSL_strings_removed)}
    if ERR_load_SSL_strings_removed <= LibVersion then
    begin
      {$if declared(_ERR_load_SSL_strings)}
      ERR_load_SSL_strings := _ERR_load_SSL_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if not defined(ERR_load_SSL_strings_allownil)}
    if FuncLoadError then
      AFailed.Add('ERR_load_SSL_strings');
    {$ifend}
  end;


end;

  {$I TaurusTLSUnusedParamOn.inc}

procedure Unload;
begin
  ERR_load_SSL_strings := nil;
end;
  {$ENDIF}
{$ENDIF}

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
initialization
  Register_SSLLoader(Load,'LibSSL');
  Register_SSLUnloader(Unload);
{$ENDIF}
end.
