/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_engineerr.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_engineerr.h2pas
     and this file regenerated. TaurusTLSHeaders_engineerr.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_engineerr;

interface

// Headers for OpenSSL 1.1.1
// engineerr.h


uses
  IdCTypes,
  IdGlobal
  {$IFDEF OPENSSL_STATIC_LINK_MODEL}
  , TaurusTLSConsts
  {$ENDIF};

const
  (*
   * ENGINE function codes.
   *)
  {$EXTERNALSYM ENGINE_F_DIGEST_UPDATE}
  ENGINE_F_DIGEST_UPDATE = 198;
  {$EXTERNALSYM ENGINE_F_DYNAMIC_CTRL}
  ENGINE_F_DYNAMIC_CTRL = 180;
  {$EXTERNALSYM ENGINE_F_DYNAMIC_GET_DATA_CTX}
  ENGINE_F_DYNAMIC_GET_DATA_CTX = 181;
  {$EXTERNALSYM ENGINE_F_DYNAMIC_LOAD}
  ENGINE_F_DYNAMIC_LOAD = 182;
  {$EXTERNALSYM ENGINE_F_DYNAMIC_SET_DATA_CTX}
  ENGINE_F_DYNAMIC_SET_DATA_CTX = 183;
  {$EXTERNALSYM ENGINE_F_ENGINE_ADD}
  ENGINE_F_ENGINE_ADD = 105;
  {$EXTERNALSYM ENGINE_F_ENGINE_BY_ID}
  ENGINE_F_ENGINE_BY_ID = 106;
  {$EXTERNALSYM ENGINE_F_ENGINE_CMD_IS_EXECUTABLE}
  ENGINE_F_ENGINE_CMD_IS_EXECUTABLE = 170;
  {$EXTERNALSYM ENGINE_F_ENGINE_CTRL}
  ENGINE_F_ENGINE_CTRL = 142;
  {$EXTERNALSYM ENGINE_F_ENGINE_CTRL_CMD}
  ENGINE_F_ENGINE_CTRL_CMD = 178;
  {$EXTERNALSYM ENGINE_F_ENGINE_CTRL_CMD_STRING}
  ENGINE_F_ENGINE_CTRL_CMD_STRING = 171;
  {$EXTERNALSYM ENGINE_F_ENGINE_FINISH}
  ENGINE_F_ENGINE_FINISH = 107;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_CIPHER}
  ENGINE_F_ENGINE_GET_CIPHER = 185;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_DIGEST}
  ENGINE_F_ENGINE_GET_DIGEST = 186;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_FIRST}
  ENGINE_F_ENGINE_GET_FIRST = 195;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_LAST}
  ENGINE_F_ENGINE_GET_LAST = 196;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_NEXT}
  ENGINE_F_ENGINE_GET_NEXT = 115;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_PKEY_ASN1_METH}
  ENGINE_F_ENGINE_GET_PKEY_ASN1_METH = 193;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_PKEY_METH}
  ENGINE_F_ENGINE_GET_PKEY_METH = 192;
  {$EXTERNALSYM ENGINE_F_ENGINE_GET_PREV}
  ENGINE_F_ENGINE_GET_PREV = 116;
  {$EXTERNALSYM ENGINE_F_ENGINE_INIT}
  ENGINE_F_ENGINE_INIT = 119;
  {$EXTERNALSYM ENGINE_F_ENGINE_LIST_ADD}
  ENGINE_F_ENGINE_LIST_ADD = 120;
  {$EXTERNALSYM ENGINE_F_ENGINE_LIST_REMOVE}
  ENGINE_F_ENGINE_LIST_REMOVE = 121;
  {$EXTERNALSYM ENGINE_F_ENGINE_LOAD_PRIVATE_KEY}
  ENGINE_F_ENGINE_LOAD_PRIVATE_KEY = 150;
  {$EXTERNALSYM ENGINE_F_ENGINE_LOAD_PUBLIC_KEY}
  ENGINE_F_ENGINE_LOAD_PUBLIC_KEY = 151;
  {$EXTERNALSYM ENGINE_F_ENGINE_LOAD_SSL_CLIENT_CERT}
  ENGINE_F_ENGINE_LOAD_SSL_CLIENT_CERT = 194;
  {$EXTERNALSYM ENGINE_F_ENGINE_NEW}
  ENGINE_F_ENGINE_NEW = 122;
  {$EXTERNALSYM ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR}
  ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR = 197;
  {$EXTERNALSYM ENGINE_F_ENGINE_REMOVE}
  ENGINE_F_ENGINE_REMOVE = 123;
  {$EXTERNALSYM ENGINE_F_ENGINE_SET_DEFAULT_STRING}
  ENGINE_F_ENGINE_SET_DEFAULT_STRING = 189;
  {$EXTERNALSYM ENGINE_F_ENGINE_SET_ID}
  ENGINE_F_ENGINE_SET_ID = 129;
  {$EXTERNALSYM ENGINE_F_ENGINE_SET_NAME}
  ENGINE_F_ENGINE_SET_NAME = 130;
  {$EXTERNALSYM ENGINE_F_ENGINE_TABLE_REGISTER}
  ENGINE_F_ENGINE_TABLE_REGISTER = 184;
  {$EXTERNALSYM ENGINE_F_ENGINE_UNLOCKED_FINISH}
  ENGINE_F_ENGINE_UNLOCKED_FINISH = 191;
  {$EXTERNALSYM ENGINE_F_ENGINE_UP_REF}
  ENGINE_F_ENGINE_UP_REF = 190;
  {$EXTERNALSYM ENGINE_F_INT_CLEANUP_ITEM}
  ENGINE_F_INT_CLEANUP_ITEM = 199;
  {$EXTERNALSYM ENGINE_F_INT_CTRL_HELPER}
  ENGINE_F_INT_CTRL_HELPER = 172;
  {$EXTERNALSYM ENGINE_F_INT_ENGINE_CONFIGURE}
  ENGINE_F_INT_ENGINE_CONFIGURE = 188;
  {$EXTERNALSYM ENGINE_F_INT_ENGINE_MODULE_INIT}
  ENGINE_F_INT_ENGINE_MODULE_INIT = 187;
  {$EXTERNALSYM ENGINE_F_OSSL_HMAC_INIT}
  ENGINE_F_OSSL_HMAC_INIT = 200;

  (*
   * ENGINE reason codes.
   *)
  {$EXTERNALSYM ENGINE_R_ALREADY_LOADED}
  ENGINE_R_ALREADY_LOADED = 100;
  {$EXTERNALSYM ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER}
  ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER = 133;
  {$EXTERNALSYM ENGINE_R_CMD_NOT_EXECUTABLE}
  ENGINE_R_CMD_NOT_EXECUTABLE = 134;
  {$EXTERNALSYM ENGINE_R_COMMAND_TAKES_INPUT}
  ENGINE_R_COMMAND_TAKES_INPUT = 135;
  {$EXTERNALSYM ENGINE_R_COMMAND_TAKES_NO_INPUT}
  ENGINE_R_COMMAND_TAKES_NO_INPUT = 136;
  {$EXTERNALSYM ENGINE_R_CONFLICTING_ENGINE_ID}
  ENGINE_R_CONFLICTING_ENGINE_ID = 103;
  {$EXTERNALSYM ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED}
  ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED = 119;
  {$EXTERNALSYM ENGINE_R_DSO_FAILURE}
  ENGINE_R_DSO_FAILURE = 104;
  {$EXTERNALSYM ENGINE_R_DSO_NOT_FOUND}
  ENGINE_R_DSO_NOT_FOUND = 132;
  {$EXTERNALSYM ENGINE_R_ENGINES_SECTION_ERROR}
  ENGINE_R_ENGINES_SECTION_ERROR = 148;
  {$EXTERNALSYM ENGINE_R_ENGINE_CONFIGURATION_ERROR}
  ENGINE_R_ENGINE_CONFIGURATION_ERROR = 102;
  {$EXTERNALSYM ENGINE_R_ENGINE_IS_NOT_IN_LIST}
  ENGINE_R_ENGINE_IS_NOT_IN_LIST = 105;
  {$EXTERNALSYM ENGINE_R_ENGINE_SECTION_ERROR}
  ENGINE_R_ENGINE_SECTION_ERROR = 149;
  {$EXTERNALSYM ENGINE_R_FAILED_LOADING_PRIVATE_KEY}
  ENGINE_R_FAILED_LOADING_PRIVATE_KEY = 128;
  {$EXTERNALSYM ENGINE_R_FAILED_LOADING_PUBLIC_KEY}
  ENGINE_R_FAILED_LOADING_PUBLIC_KEY = 129;
  {$EXTERNALSYM ENGINE_R_FINISH_FAILED}
  ENGINE_R_FINISH_FAILED = 106;
  {$EXTERNALSYM ENGINE_R_ID_OR_NAME_MISSING}
  ENGINE_R_ID_OR_NAME_MISSING = 108;
  {$EXTERNALSYM ENGINE_R_INIT_FAILED}
  ENGINE_R_INIT_FAILED = 109;
  {$EXTERNALSYM ENGINE_R_INTERNAL_LIST_ERROR}
  ENGINE_R_INTERNAL_LIST_ERROR = 110;
  {$EXTERNALSYM ENGINE_R_INVALID_ARGUMENT}
  ENGINE_R_INVALID_ARGUMENT = 143;
  {$EXTERNALSYM ENGINE_R_INVALID_CMD_NAME}
  ENGINE_R_INVALID_CMD_NAME = 137;
  {$EXTERNALSYM ENGINE_R_INVALID_CMD_NUMBER}
  ENGINE_R_INVALID_CMD_NUMBER = 138;
  {$EXTERNALSYM ENGINE_R_INVALID_INIT_VALUE}
  ENGINE_R_INVALID_INIT_VALUE = 151;
  {$EXTERNALSYM ENGINE_R_INVALID_STRING}
  ENGINE_R_INVALID_STRING = 150;
  {$EXTERNALSYM ENGINE_R_NOT_INITIALISED}
  ENGINE_R_NOT_INITIALISED = 117;
  {$EXTERNALSYM ENGINE_R_NOT_LOADED}
  ENGINE_R_NOT_LOADED = 112;
  {$EXTERNALSYM ENGINE_R_NO_CONTROL_FUNCTION}
  ENGINE_R_NO_CONTROL_FUNCTION = 120;
  {$EXTERNALSYM ENGINE_R_NO_INDEX}
  ENGINE_R_NO_INDEX = 144;
  {$EXTERNALSYM ENGINE_R_NO_LOAD_FUNCTION}
  ENGINE_R_NO_LOAD_FUNCTION = 125;
  {$EXTERNALSYM ENGINE_R_NO_REFERENCE}
  ENGINE_R_NO_REFERENCE = 130;
  {$EXTERNALSYM ENGINE_R_NO_SUCH_ENGINE}
  ENGINE_R_NO_SUCH_ENGINE = 116;
  {$EXTERNALSYM ENGINE_R_UNIMPLEMENTED_CIPHER}
  ENGINE_R_UNIMPLEMENTED_CIPHER = 146;
  {$EXTERNALSYM ENGINE_R_UNIMPLEMENTED_DIGEST}
  ENGINE_R_UNIMPLEMENTED_DIGEST = 147;
  {$EXTERNALSYM ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD}
  ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD = 101;
  {$EXTERNALSYM ENGINE_R_VERSION_INCOMPATIBILITY}
  ENGINE_R_VERSION_INCOMPATIBILITY = 145;

    { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:
		
  	  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header 
	  files generated for C++. }
	  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
var
  ERR_load_ENGINE_strings: function : TIdC_INT; cdecl = nil;

{$ELSE}
  function ERR_load_ENGINE_strings: TIdC_INT cdecl; external CLibCrypto;

{$ENDIF}

implementation

  uses
    classes, 
    TaurusTLSExceptionHandlers
  {$IFNDEF OPENSSL_STATIC_LINK_MODEL}
    ,TaurusTLSLoader
  {$ENDIF};
  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
const
  ERR_load_ENGINE_strings_procname = 'ERR_load_ENGINE_strings';
  ERR_load_ENGINE_strings_removed = (byte(4) shl 8 or byte(0)) shl 8 or byte(0);
  {$IFNDEF _FIXINSIGHT_}
  {$I TaurusTLSNoRetValOff.inc} 
function  ERR_ERR_load_ENGINE_strings: TIdC_INT; cdecl;
begin
  ETaurusTLSAPIFunctionNotPresent.RaiseException(ERR_load_ENGINE_strings_procname);
end;



  {$I TaurusTLSNoRetValOn.inc} 
  {$I TaurusTLSUnusedParamOff.inc}
procedure Load(const ADllHandle: TIdLibHandle; LibVersion: TIdC_UINT; const AFailed: TStringList);

var FuncLoadError: boolean;

begin
  ERR_load_ENGINE_strings := LoadLibFunction(ADllHandle, ERR_load_ENGINE_strings_procname);
  FuncLoadError := not assigned(ERR_load_ENGINE_strings);
  if FuncLoadError then
  begin
    {$if not defined(ERR_load_ENGINE_strings_allownil)}
    ERR_load_ENGINE_strings := ERR_ERR_load_ENGINE_strings;
    {$ifend}
    {$if declared(ERR_load_ENGINE_strings_introduced)}
    if LibVersion < ERR_load_ENGINE_strings_introduced then
    begin
      {$if declared(FC_ERR_load_ENGINE_strings)}
      ERR_load_ENGINE_strings := FC_ERR_load_ENGINE_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if declared(ERR_load_ENGINE_strings_removed)}
    if ERR_load_ENGINE_strings_removed <= LibVersion then
    begin
      {$if declared(_ERR_load_ENGINE_strings)}
      ERR_load_ENGINE_strings := _ERR_load_ENGINE_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if not defined(ERR_load_ENGINE_strings_allownil)}
    if FuncLoadError then
      AFailed.Add('ERR_load_ENGINE_strings');
    {$ifend}
  end;
end;
 {$I TaurusTLSUnusedParamOn.inc}

procedure Unload;
begin
  ERR_load_ENGINE_strings := nil;
end;
  {$ENDIF}
{$ENDIF}

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
initialization
  Register_SSLLoader(Load,'LibCrypto');
  Register_SSLUnloader(Unload);
{$ENDIF}
end.
