/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_ecerr.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_ecerr.h2pas
     and this file regenerated. TaurusTLSHeaders_ecerr.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_ecerr;

interface

// Headers for OpenSSL 1.1.1
// ecerr.h


uses
  IdCTypes,
  IdGlobal
  {$IFDEF OPENSSL_STATIC_LINK_MODEL}
  , TaurusTLSConsts
  {$ENDIF};

const
  (*
   * EC function codes.
   *)
  {$EXTERNALSYM EC_F_BN_TO_FELEM}
  EC_F_BN_TO_FELEM = 224;
  {$EXTERNALSYM EC_F_D2I_ECPARAMETERS}
  EC_F_D2I_ECPARAMETERS = 144;
  {$EXTERNALSYM EC_F_D2I_ECPKPARAMETERS}
  EC_F_D2I_ECPKPARAMETERS = 145;
  {$EXTERNALSYM EC_F_D2I_ECPRIVATEKEY}
  EC_F_D2I_ECPRIVATEKEY = 146;
  {$EXTERNALSYM EC_F_DO_EC_KEY_PRINT}
  EC_F_DO_EC_KEY_PRINT = 221;
  {$EXTERNALSYM EC_F_ECDH_CMS_DECRYPT}
  EC_F_ECDH_CMS_DECRYPT = 238;
  {$EXTERNALSYM EC_F_ECDH_CMS_SET_SHARED_INFO}
  EC_F_ECDH_CMS_SET_SHARED_INFO = 239;
  {$EXTERNALSYM EC_F_ECDH_COMPUTE_KEY}
  EC_F_ECDH_COMPUTE_KEY = 246;
  {$EXTERNALSYM EC_F_ECDH_SIMPLE_COMPUTE_KEY}
  EC_F_ECDH_SIMPLE_COMPUTE_KEY = 257;
  {$EXTERNALSYM EC_F_ECDSA_DO_SIGN_EX}
  EC_F_ECDSA_DO_SIGN_EX = 251;
  {$EXTERNALSYM EC_F_ECDSA_DO_VERIFY}
  EC_F_ECDSA_DO_VERIFY = 252;
  {$EXTERNALSYM EC_F_ECDSA_SIGN_EX}
  EC_F_ECDSA_SIGN_EX = 254;
  {$EXTERNALSYM EC_F_ECDSA_SIGN_SETUP}
  EC_F_ECDSA_SIGN_SETUP = 248;
  {$EXTERNALSYM EC_F_ECDSA_SIG_NEW}
  EC_F_ECDSA_SIG_NEW = 265;
  {$EXTERNALSYM EC_F_ECDSA_VERIFY}
  EC_F_ECDSA_VERIFY = 253;
  {$EXTERNALSYM EC_F_ECD_ITEM_VERIFY}
  EC_F_ECD_ITEM_VERIFY = 270;
  {$EXTERNALSYM EC_F_ECKEY_PARAM2TYPE}
  EC_F_ECKEY_PARAM2TYPE = 223;
  {$EXTERNALSYM EC_F_ECKEY_PARAM_DECODE}
  EC_F_ECKEY_PARAM_DECODE = 212;
  {$EXTERNALSYM EC_F_ECKEY_PRIV_DECODE}
  EC_F_ECKEY_PRIV_DECODE = 213;
  {$EXTERNALSYM EC_F_ECKEY_PRIV_ENCODE}
  EC_F_ECKEY_PRIV_ENCODE = 214;
  {$EXTERNALSYM EC_F_ECKEY_PUB_DECODE}
  EC_F_ECKEY_PUB_DECODE = 215;
  {$EXTERNALSYM EC_F_ECKEY_PUB_ENCODE}
  EC_F_ECKEY_PUB_ENCODE = 216;
  {$EXTERNALSYM EC_F_ECKEY_TYPE2PARAM}
  EC_F_ECKEY_TYPE2PARAM = 220;
  {$EXTERNALSYM EC_F_ECPARAMETERS_PRINT}
  EC_F_ECPARAMETERS_PRINT = 147;
  {$EXTERNALSYM EC_F_ECPARAMETERS_PRINT_FP}
  EC_F_ECPARAMETERS_PRINT_FP = 148;
  {$EXTERNALSYM EC_F_ECPKPARAMETERS_PRINT}
  EC_F_ECPKPARAMETERS_PRINT = 149;
  {$EXTERNALSYM EC_F_ECPKPARAMETERS_PRINT_FP}
  EC_F_ECPKPARAMETERS_PRINT_FP = 150;
  {$EXTERNALSYM EC_F_ECP_NISTZ256_GET_AFFINE}
  EC_F_ECP_NISTZ256_GET_AFFINE = 240;
  {$EXTERNALSYM EC_F_ECP_NISTZ256_INV_MOD_ORD}
  EC_F_ECP_NISTZ256_INV_MOD_ORD = 275;
  {$EXTERNALSYM EC_F_ECP_NISTZ256_MULT_PRECOMPUTE}
  EC_F_ECP_NISTZ256_MULT_PRECOMPUTE = 243;
  {$EXTERNALSYM EC_F_ECP_NISTZ256_POINTS_MUL}
  EC_F_ECP_NISTZ256_POINTS_MUL = 241;
  {$EXTERNALSYM EC_F_ECP_NISTZ256_PRE_COMP_NEW}
  EC_F_ECP_NISTZ256_PRE_COMP_NEW = 244;
  {$EXTERNALSYM EC_F_ECP_NISTZ256_WINDOWED_MUL}
  EC_F_ECP_NISTZ256_WINDOWED_MUL = 242;
  {$EXTERNALSYM EC_F_ECX_KEY_OP}
  EC_F_ECX_KEY_OP = 266;
  {$EXTERNALSYM EC_F_ECX_PRIV_ENCODE}
  EC_F_ECX_PRIV_ENCODE = 267;
  {$EXTERNALSYM EC_F_ECX_PUB_ENCODE}
  EC_F_ECX_PUB_ENCODE = 268;
  {$EXTERNALSYM EC_F_EC_ASN1_GROUP2CURVE}
  EC_F_EC_ASN1_GROUP2CURVE = 153;
  {$EXTERNALSYM EC_F_EC_ASN1_GROUP2FIELDID}
  EC_F_EC_ASN1_GROUP2FIELDID = 154;
  {$EXTERNALSYM EC_F_EC_GF2M_MONTGOMERY_POINT_MULTIPLY}
  EC_F_EC_GF2M_MONTGOMERY_POINT_MULTIPLY = 208;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_FIELD_INV}
  EC_F_EC_GF2M_SIMPLE_FIELD_INV = 296;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_GROUP_CHECK_DISCRIMINANT}
  EC_F_EC_GF2M_SIMPLE_GROUP_CHECK_DISCRIMINANT = 159;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_GROUP_SET_CURVE}
  EC_F_EC_GF2M_SIMPLE_GROUP_SET_CURVE = 195;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_LADDER_POST}
  EC_F_EC_GF2M_SIMPLE_LADDER_POST = 285;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_LADDER_PRE}
  EC_F_EC_GF2M_SIMPLE_LADDER_PRE = 288;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_OCT2POINT}
  EC_F_EC_GF2M_SIMPLE_OCT2POINT = 160;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_POINT2OCT}
  EC_F_EC_GF2M_SIMPLE_POINT2OCT = 161;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_POINTS_MUL}
  EC_F_EC_GF2M_SIMPLE_POINTS_MUL = 289;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_POINT_GET_AFFINE_COORDINATES}
  EC_F_EC_GF2M_SIMPLE_POINT_GET_AFFINE_COORDINATES = 162;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_POINT_SET_AFFINE_COORDINATES}
  EC_F_EC_GF2M_SIMPLE_POINT_SET_AFFINE_COORDINATES = 163;
  {$EXTERNALSYM EC_F_EC_GF2M_SIMPLE_SET_COMPRESSED_COORDINATES}
  EC_F_EC_GF2M_SIMPLE_SET_COMPRESSED_COORDINATES = 164;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_FIELD_DECODE}
  EC_F_EC_GFP_MONT_FIELD_DECODE = 133;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_FIELD_ENCODE}
  EC_F_EC_GFP_MONT_FIELD_ENCODE = 134;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_FIELD_INV}
  EC_F_EC_GFP_MONT_FIELD_INV = 297;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_FIELD_MUL}
  EC_F_EC_GFP_MONT_FIELD_MUL = 131;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE}
  EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE = 209;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_FIELD_SQR}
  EC_F_EC_GFP_MONT_FIELD_SQR = 132;
  {$EXTERNALSYM EC_F_EC_GFP_MONT_GROUP_SET_CURVE}
  EC_F_EC_GFP_MONT_GROUP_SET_CURVE = 189;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP224_GROUP_SET_CURVE}
  EC_F_EC_GFP_NISTP224_GROUP_SET_CURVE = 225;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP224_POINTS_MUL}
  EC_F_EC_GFP_NISTP224_POINTS_MUL = 228;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES}
  EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES = 226;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP256_GROUP_SET_CURVE}
  EC_F_EC_GFP_NISTP256_GROUP_SET_CURVE = 230;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP256_POINTS_MUL}
  EC_F_EC_GFP_NISTP256_POINTS_MUL = 231;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES}
  EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES = 232;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP521_GROUP_SET_CURVE}
  EC_F_EC_GFP_NISTP521_GROUP_SET_CURVE = 233;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP521_POINTS_MUL}
  EC_F_EC_GFP_NISTP521_POINTS_MUL = 234;
  {$EXTERNALSYM EC_F_EC_GFP_NISTP521_POINT_GET_AFFINE_COORDINATES}
  EC_F_EC_GFP_NISTP521_POINT_GET_AFFINE_COORDINATES = 235;
  {$EXTERNALSYM EC_F_EC_GFP_NIST_FIELD_MUL}
  EC_F_EC_GFP_NIST_FIELD_MUL = 200;
  {$EXTERNALSYM EC_F_EC_GFP_NIST_FIELD_SQR}
  EC_F_EC_GFP_NIST_FIELD_SQR = 201;
  {$EXTERNALSYM EC_F_EC_GFP_NIST_GROUP_SET_CURVE}
  EC_F_EC_GFP_NIST_GROUP_SET_CURVE = 202;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_BLIND_COORDINATES}
  EC_F_EC_GFP_SIMPLE_BLIND_COORDINATES = 287;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_FIELD_INV}
  EC_F_EC_GFP_SIMPLE_FIELD_INV = 298;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_GROUP_CHECK_DISCRIMINANT}
  EC_F_EC_GFP_SIMPLE_GROUP_CHECK_DISCRIMINANT = 165;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_GROUP_SET_CURVE}
  EC_F_EC_GFP_SIMPLE_GROUP_SET_CURVE = 166;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_MAKE_AFFINE}
  EC_F_EC_GFP_SIMPLE_MAKE_AFFINE = 102;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_OCT2POINT}
  EC_F_EC_GFP_SIMPLE_OCT2POINT = 103;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_POINT2OCT}
  EC_F_EC_GFP_SIMPLE_POINT2OCT = 104;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_POINTS_MAKE_AFFINE}
  EC_F_EC_GFP_SIMPLE_POINTS_MAKE_AFFINE = 137;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_POINT_GET_AFFINE_COORDINATES}
  EC_F_EC_GFP_SIMPLE_POINT_GET_AFFINE_COORDINATES = 167;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES}
  EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES = 168;
  {$EXTERNALSYM EC_F_EC_GFP_SIMPLE_SET_COMPRESSED_COORDINATES}
  EC_F_EC_GFP_SIMPLE_SET_COMPRESSED_COORDINATES = 169;
  {$EXTERNALSYM EC_F_EC_GROUP_CHECK}
  EC_F_EC_GROUP_CHECK = 170;
  {$EXTERNALSYM EC_F_EC_GROUP_CHECK_DISCRIMINANT}
  EC_F_EC_GROUP_CHECK_DISCRIMINANT = 171;
  {$EXTERNALSYM EC_F_EC_GROUP_COPY}
  EC_F_EC_GROUP_COPY = 106;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_CURVE}
  EC_F_EC_GROUP_GET_CURVE = 291;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_CURVE_GF2M}
  EC_F_EC_GROUP_GET_CURVE_GF2M = 172;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_CURVE_GFP}
  EC_F_EC_GROUP_GET_CURVE_GFP = 130;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_DEGREE}
  EC_F_EC_GROUP_GET_DEGREE = 173;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_ECPARAMETERS}
  EC_F_EC_GROUP_GET_ECPARAMETERS = 261;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_ECPKPARAMETERS}
  EC_F_EC_GROUP_GET_ECPKPARAMETERS = 262;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS}
  EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS = 193;
  {$EXTERNALSYM EC_F_EC_GROUP_GET_TRINOMIAL_BASIS}
  EC_F_EC_GROUP_GET_TRINOMIAL_BASIS = 194;
  {$EXTERNALSYM EC_F_EC_GROUP_NEW}
  EC_F_EC_GROUP_NEW = 108;
  {$EXTERNALSYM EC_F_EC_GROUP_NEW_BY_CURVE_NAME}
  EC_F_EC_GROUP_NEW_BY_CURVE_NAME = 174;
  {$EXTERNALSYM EC_F_EC_GROUP_NEW_FROM_DATA}
  EC_F_EC_GROUP_NEW_FROM_DATA = 175;
  {$EXTERNALSYM EC_F_EC_GROUP_NEW_FROM_ECPARAMETERS}
  EC_F_EC_GROUP_NEW_FROM_ECPARAMETERS = 263;
  {$EXTERNALSYM EC_F_EC_GROUP_NEW_FROM_ECPKPARAMETERS}
  EC_F_EC_GROUP_NEW_FROM_ECPKPARAMETERS = 264;
  {$EXTERNALSYM EC_F_EC_GROUP_SET_CURVE}
  EC_F_EC_GROUP_SET_CURVE = 292;
  {$EXTERNALSYM EC_F_EC_GROUP_SET_CURVE_GF2M}
  EC_F_EC_GROUP_SET_CURVE_GF2M = 176;
  {$EXTERNALSYM EC_F_EC_GROUP_SET_CURVE_GFP}
  EC_F_EC_GROUP_SET_CURVE_GFP = 109;
  {$EXTERNALSYM EC_F_EC_GROUP_SET_GENERATOR}
  EC_F_EC_GROUP_SET_GENERATOR = 111;
  {$EXTERNALSYM EC_F_EC_GROUP_SET_SEED}
  EC_F_EC_GROUP_SET_SEED = 286;
  {$EXTERNALSYM EC_F_EC_KEY_CHECK_KEY}
  EC_F_EC_KEY_CHECK_KEY = 177;
  {$EXTERNALSYM EC_F_EC_KEY_COPY}
  EC_F_EC_KEY_COPY = 178;
  {$EXTERNALSYM EC_F_EC_KEY_GENERATE_KEY}
  EC_F_EC_KEY_GENERATE_KEY = 179;
  {$EXTERNALSYM EC_F_EC_KEY_NEW}
  EC_F_EC_KEY_NEW = 182;
  {$EXTERNALSYM EC_F_EC_KEY_NEW_METHOD}
  EC_F_EC_KEY_NEW_METHOD = 245;
  {$EXTERNALSYM EC_F_EC_KEY_OCT2PRIV}
  EC_F_EC_KEY_OCT2PRIV = 255;
  {$EXTERNALSYM EC_F_EC_KEY_PRINT}
  EC_F_EC_KEY_PRINT = 180;
  {$EXTERNALSYM EC_F_EC_KEY_PRINT_FP}
  EC_F_EC_KEY_PRINT_FP = 181;
  {$EXTERNALSYM EC_F_EC_KEY_PRIV2BUF}
  EC_F_EC_KEY_PRIV2BUF = 279;
  {$EXTERNALSYM EC_F_EC_KEY_PRIV2OCT}
  EC_F_EC_KEY_PRIV2OCT = 256;
  {$EXTERNALSYM EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES}
  EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES = 229;
  {$EXTERNALSYM EC_F_EC_KEY_SIMPLE_CHECK_KEY}
  EC_F_EC_KEY_SIMPLE_CHECK_KEY = 258;
  {$EXTERNALSYM EC_F_EC_KEY_SIMPLE_OCT2PRIV}
  EC_F_EC_KEY_SIMPLE_OCT2PRIV = 259;
  {$EXTERNALSYM EC_F_EC_KEY_SIMPLE_PRIV2OCT}
  EC_F_EC_KEY_SIMPLE_PRIV2OCT = 260;
  {$EXTERNALSYM EC_F_EC_PKEY_CHECK}
  EC_F_EC_PKEY_CHECK = 273;
  {$EXTERNALSYM EC_F_EC_PKEY_PARAM_CHECK}
  EC_F_EC_PKEY_PARAM_CHECK = 274;
  {$EXTERNALSYM EC_F_EC_POINTS_MAKE_AFFINE}
  EC_F_EC_POINTS_MAKE_AFFINE = 136;
  {$EXTERNALSYM EC_F_EC_POINTS_MUL}
  EC_F_EC_POINTS_MUL = 290;
  {$EXTERNALSYM EC_F_EC_POINT_ADD}
  EC_F_EC_POINT_ADD = 112;
  {$EXTERNALSYM EC_F_EC_POINT_BN2POINT}
  EC_F_EC_POINT_BN2POINT = 280;
  {$EXTERNALSYM EC_F_EC_POINT_CMP}
  EC_F_EC_POINT_CMP = 113;
  {$EXTERNALSYM EC_F_EC_POINT_COPY}
  EC_F_EC_POINT_COPY = 114;
  {$EXTERNALSYM EC_F_EC_POINT_DBL}
  EC_F_EC_POINT_DBL = 115;
  {$EXTERNALSYM EC_F_EC_POINT_GET_AFFINE_COORDINATES}
  EC_F_EC_POINT_GET_AFFINE_COORDINATES = 293;
  {$EXTERNALSYM EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M}
  EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M = 183;
  {$EXTERNALSYM EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP}
  EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP = 116;
  {$EXTERNALSYM EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP}
  EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP = 117;
  {$EXTERNALSYM EC_F_EC_POINT_INVERT}
  EC_F_EC_POINT_INVERT = 210;
  {$EXTERNALSYM EC_F_EC_POINT_IS_AT_INFINITY}
  EC_F_EC_POINT_IS_AT_INFINITY = 118;
  {$EXTERNALSYM EC_F_EC_POINT_IS_ON_CURVE}
  EC_F_EC_POINT_IS_ON_CURVE = 119;
  {$EXTERNALSYM EC_F_EC_POINT_MAKE_AFFINE}
  EC_F_EC_POINT_MAKE_AFFINE = 120;
  {$EXTERNALSYM EC_F_EC_POINT_NEW}
  EC_F_EC_POINT_NEW = 121;
  {$EXTERNALSYM EC_F_EC_POINT_OCT2POINT}
  EC_F_EC_POINT_OCT2POINT = 122;
  {$EXTERNALSYM EC_F_EC_POINT_POINT2BUF}
  EC_F_EC_POINT_POINT2BUF = 281;
  {$EXTERNALSYM EC_F_EC_POINT_POINT2OCT}
  EC_F_EC_POINT_POINT2OCT = 123;
  {$EXTERNALSYM EC_F_EC_POINT_SET_AFFINE_COORDINATES}
  EC_F_EC_POINT_SET_AFFINE_COORDINATES = 294;
  {$EXTERNALSYM EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M}
  EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M = 185;
  {$EXTERNALSYM EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP}
  EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP = 124;
  {$EXTERNALSYM EC_F_EC_POINT_SET_COMPRESSED_COORDINATES}
  EC_F_EC_POINT_SET_COMPRESSED_COORDINATES = 295;
  {$EXTERNALSYM EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M}
  EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M = 186;
  {$EXTERNALSYM EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP}
  EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP = 125;
  {$EXTERNALSYM EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP}
  EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP = 126;
  {$EXTERNALSYM EC_F_EC_POINT_SET_TO_INFINITY}
  EC_F_EC_POINT_SET_TO_INFINITY = 127;
  {$EXTERNALSYM EC_F_EC_PRE_COMP_NEW}
  EC_F_EC_PRE_COMP_NEW = 196;
  {$EXTERNALSYM EC_F_EC_SCALAR_MUL_LADDER}
  EC_F_EC_SCALAR_MUL_LADDER = 284;
  {$EXTERNALSYM EC_F_EC_WNAF_MUL}
  EC_F_EC_WNAF_MUL = 187;
  {$EXTERNALSYM EC_F_EC_WNAF_PRECOMPUTE_MULT}
  EC_F_EC_WNAF_PRECOMPUTE_MULT = 188;
  {$EXTERNALSYM EC_F_I2D_ECPARAMETERS}
  EC_F_I2D_ECPARAMETERS = 190;
  {$EXTERNALSYM EC_F_I2D_ECPKPARAMETERS}
  EC_F_I2D_ECPKPARAMETERS = 191;
  {$EXTERNALSYM EC_F_I2D_ECPRIVATEKEY}
  EC_F_I2D_ECPRIVATEKEY = 192;
  {$EXTERNALSYM EC_F_I2O_ECPUBLICKEY}
  EC_F_I2O_ECPUBLICKEY = 151;
  {$EXTERNALSYM EC_F_NISTP224_PRE_COMP_NEW}
  EC_F_NISTP224_PRE_COMP_NEW = 227;
  {$EXTERNALSYM EC_F_NISTP256_PRE_COMP_NEW}
  EC_F_NISTP256_PRE_COMP_NEW = 236;
  {$EXTERNALSYM EC_F_NISTP521_PRE_COMP_NEW}
  EC_F_NISTP521_PRE_COMP_NEW = 237;
  {$EXTERNALSYM EC_F_O2I_ECPUBLICKEY}
  EC_F_O2I_ECPUBLICKEY = 152;
  {$EXTERNALSYM EC_F_OLD_EC_PRIV_DECODE}
  EC_F_OLD_EC_PRIV_DECODE = 222;
  {$EXTERNALSYM EC_F_OSSL_ECDH_COMPUTE_KEY}
  EC_F_OSSL_ECDH_COMPUTE_KEY = 247;
  {$EXTERNALSYM EC_F_OSSL_ECDSA_SIGN_SIG}
  EC_F_OSSL_ECDSA_SIGN_SIG = 249;
  {$EXTERNALSYM EC_F_OSSL_ECDSA_VERIFY_SIG}
  EC_F_OSSL_ECDSA_VERIFY_SIG = 250;
  {$EXTERNALSYM EC_F_PKEY_ECD_CTRL}
  EC_F_PKEY_ECD_CTRL = 271;
  {$EXTERNALSYM EC_F_PKEY_ECD_DIGESTSIGN}
  EC_F_PKEY_ECD_DIGESTSIGN = 272;
  {$EXTERNALSYM EC_F_PKEY_ECD_DIGESTSIGN25519}
  EC_F_PKEY_ECD_DIGESTSIGN25519 = 276;
  {$EXTERNALSYM EC_F_PKEY_ECD_DIGESTSIGN448}
  EC_F_PKEY_ECD_DIGESTSIGN448 = 277;
  {$EXTERNALSYM EC_F_PKEY_ECX_DERIVE}
  EC_F_PKEY_ECX_DERIVE = 269;
  {$EXTERNALSYM EC_F_PKEY_EC_CTRL}
  EC_F_PKEY_EC_CTRL = 197;
  {$EXTERNALSYM EC_F_PKEY_EC_CTRL_STR}
  EC_F_PKEY_EC_CTRL_STR = 198;
  {$EXTERNALSYM EC_F_PKEY_EC_DERIVE}
  EC_F_PKEY_EC_DERIVE = 217;
  {$EXTERNALSYM EC_F_PKEY_EC_INIT}
  EC_F_PKEY_EC_INIT = 282;
  {$EXTERNALSYM EC_F_PKEY_EC_KDF_DERIVE}
  EC_F_PKEY_EC_KDF_DERIVE = 283;
  {$EXTERNALSYM EC_F_PKEY_EC_KEYGEN}
  EC_F_PKEY_EC_KEYGEN = 199;
  {$EXTERNALSYM EC_F_PKEY_EC_PARAMGEN}
  EC_F_PKEY_EC_PARAMGEN = 219;
  {$EXTERNALSYM EC_F_PKEY_EC_SIGN}
  EC_F_PKEY_EC_SIGN = 218;
  {$EXTERNALSYM EC_F_VALIDATE_ECX_DERIVE}
  EC_F_VALIDATE_ECX_DERIVE = 278;

  (*
   * EC reason codes.
   *)
  {$EXTERNALSYM EC_R_ASN1_ERROR}
  EC_R_ASN1_ERROR =   115;
  {$EXTERNALSYM EC_R_BAD_SIGNATURE}
  EC_R_BAD_SIGNATURE =   156;
  {$EXTERNALSYM EC_R_BIGNUM_OUT_OF_RANGE}
  EC_R_BIGNUM_OUT_OF_RANGE =  144;
  {$EXTERNALSYM EC_R_BUFFER_TOO_SMALL}
  EC_R_BUFFER_TOO_SMALL =  100;
  {$EXTERNALSYM EC_R_CANNOT_INVERT}
  EC_R_CANNOT_INVERT =   165;
  {$EXTERNALSYM EC_R_COORDINATES_OUT_OF_RANGE}
  EC_R_COORDINATES_OUT_OF_RANGE =  146;
  {$EXTERNALSYM EC_R_CURVE_DOES_NOT_SUPPORT_ECDH}
  EC_R_CURVE_DOES_NOT_SUPPORT_ECDH =  160;
  {$EXTERNALSYM EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING}
  EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING = 159;
  {$EXTERNALSYM EC_R_D2I_ECPKPARAMETERS_FAILURE}
  EC_R_D2I_ECPKPARAMETERS_FAILURE =  117;
  {$EXTERNALSYM EC_R_DECODE_ERROR}
  EC_R_DECODE_ERROR =   142;
  {$EXTERNALSYM EC_R_DISCRIMINANT_IS_ZERO}
  EC_R_DISCRIMINANT_IS_ZERO =  118;
  {$EXTERNALSYM EC_R_EC_GROUP_NEW_BY_NAME_FAILURE}
  EC_R_EC_GROUP_NEW_BY_NAME_FAILURE =  119;
  {$EXTERNALSYM EC_R_FIELD_TOO_LARGE}
  EC_R_FIELD_TOO_LARGE =  143;
  {$EXTERNALSYM EC_R_GF2M_NOT_SUPPORTED}
  EC_R_GF2M_NOT_SUPPORTED =  147;
  {$EXTERNALSYM EC_R_GROUP2PKPARAMETERS_FAILURE}
  EC_R_GROUP2PKPARAMETERS_FAILURE =  120;
  {$EXTERNALSYM EC_R_I2D_ECPKPARAMETERS_FAILURE}
  EC_R_I2D_ECPKPARAMETERS_FAILURE =  121;
  {$EXTERNALSYM EC_R_INCOMPATIBLE_OBJECTS}
  EC_R_INCOMPATIBLE_OBJECTS =  101;
  {$EXTERNALSYM EC_R_INVALID_ARGUMENT}
  EC_R_INVALID_ARGUMENT =  112;
  {$EXTERNALSYM EC_R_INVALID_COMPRESSED_POINT}
  EC_R_INVALID_COMPRESSED_POINT =  110;
  {$EXTERNALSYM EC_R_INVALID_COMPRESSION_BIT}
  EC_R_INVALID_COMPRESSION_BIT =  109;
  {$EXTERNALSYM EC_R_INVALID_CURVE}
  EC_R_INVALID_CURVE =   141;
  {$EXTERNALSYM EC_R_INVALID_DIGEST}
  EC_R_INVALID_DIGEST =  151;
  {$EXTERNALSYM EC_R_INVALID_DIGEST_TYPE}
  EC_R_INVALID_DIGEST_TYPE =  138;
  {$EXTERNALSYM EC_R_INVALID_ENCODING}
  EC_R_INVALID_ENCODING =  102;
  {$EXTERNALSYM EC_R_INVALID_FIELD}
  EC_R_INVALID_FIELD =   103;
  {$EXTERNALSYM EC_R_INVALID_FORM}
  EC_R_INVALID_FORM =   104;
  {$EXTERNALSYM EC_R_INVALID_GROUP_ORDER}
  EC_R_INVALID_GROUP_ORDER =  122;
  {$EXTERNALSYM EC_R_INVALID_KEY}
  EC_R_INVALID_KEY =   116;
  {$EXTERNALSYM EC_R_INVALID_OUTPUT_LENGTH}
  EC_R_INVALID_OUTPUT_LENGTH =  161;
  {$EXTERNALSYM EC_R_INVALID_PEER_KEY}
  EC_R_INVALID_PEER_KEY =  133;
  {$EXTERNALSYM EC_R_INVALID_PENTANOMIAL_BASIS}
  EC_R_INVALID_PENTANOMIAL_BASIS =  132;
  {$EXTERNALSYM EC_R_INVALID_PRIVATE_KEY}
  EC_R_INVALID_PRIVATE_KEY =  123;
  {$EXTERNALSYM EC_R_INVALID_TRINOMIAL_BASIS}
  EC_R_INVALID_TRINOMIAL_BASIS =  137;
  {$EXTERNALSYM EC_R_KDF_PARAMETER_ERROR}
  EC_R_KDF_PARAMETER_ERROR =  148;
  {$EXTERNALSYM EC_R_KEYS_NOT_SET}
  EC_R_KEYS_NOT_SET =   140;
  {$EXTERNALSYM EC_R_LADDER_POST_FAILURE}
  EC_R_LADDER_POST_FAILURE =  136;
  {$EXTERNALSYM EC_R_LADDER_PRE_FAILURE}
  EC_R_LADDER_PRE_FAILURE =  153;
  {$EXTERNALSYM EC_R_LADDER_STEP_FAILURE}
  EC_R_LADDER_STEP_FAILURE =  162;
  {$EXTERNALSYM EC_R_MISSING_PARAMETERS}
  EC_R_MISSING_PARAMETERS =  124;
  {$EXTERNALSYM EC_R_MISSING_PRIVATE_KEY}
  EC_R_MISSING_PRIVATE_KEY =  125;
  {$EXTERNALSYM EC_R_NEED_NEW_SETUP_VALUES}
  EC_R_NEED_NEW_SETUP_VALUES =  157;
  {$EXTERNALSYM EC_R_NOT_A_NIST_PRIME}
  EC_R_NOT_A_NIST_PRIME =  135;
  {$EXTERNALSYM EC_R_NOT_IMPLEMENTED}
  EC_R_NOT_IMPLEMENTED =  126;
  {$EXTERNALSYM EC_R_NOT_INITIALIZED}
  EC_R_NOT_INITIALIZED =  111;
  {$EXTERNALSYM EC_R_NO_PARAMETERS_SET}
  EC_R_NO_PARAMETERS_SET =  139;
  {$EXTERNALSYM EC_R_NO_PRIVATE_VALUE}
  EC_R_NO_PRIVATE_VALUE =  154;
  {$EXTERNALSYM EC_R_OPERATION_NOT_SUPPORTED}
  EC_R_OPERATION_NOT_SUPPORTED =  152;
  {$EXTERNALSYM EC_R_PASSED_NULL_PARAMETER}
  EC_R_PASSED_NULL_PARAMETER =  134;
  {$EXTERNALSYM EC_R_PEER_KEY_ERROR}
  EC_R_PEER_KEY_ERROR =  149;
  {$EXTERNALSYM EC_R_PKPARAMETERS2GROUP_FAILURE}
  EC_R_PKPARAMETERS2GROUP_FAILURE =  127;
  {$EXTERNALSYM EC_R_POINT_ARITHMETIC_FAILURE}
  EC_R_POINT_ARITHMETIC_FAILURE =  155;
  {$EXTERNALSYM EC_R_POINT_AT_INFINITY}
  EC_R_POINT_AT_INFINITY =  106;
  {$EXTERNALSYM EC_R_POINT_COORDINATES_BLIND_FAILURE}
  EC_R_POINT_COORDINATES_BLIND_FAILURE = 163;
  {$EXTERNALSYM EC_R_POINT_IS_NOT_ON_CURVE}
  EC_R_POINT_IS_NOT_ON_CURVE =  107;
  {$EXTERNALSYM EC_R_RANDOM_NUMBER_GENERATION_FAILED}
  EC_R_RANDOM_NUMBER_GENERATION_FAILED = 158;
  {$EXTERNALSYM EC_R_SHARED_INFO_ERROR}
  EC_R_SHARED_INFO_ERROR =  150;
  {$EXTERNALSYM EC_R_SLOT_FULL}
  EC_R_SLOT_FULL =   108;
  {$EXTERNALSYM EC_R_UNDEFINED_GENERATOR}
  EC_R_UNDEFINED_GENERATOR =  113;
  {$EXTERNALSYM EC_R_UNDEFINED_ORDER}
  EC_R_UNDEFINED_ORDER =  128;
  {$EXTERNALSYM EC_R_UNKNOWN_COFACTOR}
  EC_R_UNKNOWN_COFACTOR =  164;
  {$EXTERNALSYM EC_R_UNKNOWN_GROUP}
  EC_R_UNKNOWN_GROUP =   129;
  {$EXTERNALSYM EC_R_UNKNOWN_ORDER}
  EC_R_UNKNOWN_ORDER =   114;
  {$EXTERNALSYM EC_R_UNSUPPORTED_FIELD}
  EC_R_UNSUPPORTED_FIELD =  131;
  {$EXTERNALSYM EC_R_WRONG_CURVE_PARAMETERS}
  EC_R_WRONG_CURVE_PARAMETERS =  145;
  {$EXTERNALSYM EC_R_WRONG_ORDER}
  EC_R_WRONG_ORDER =   130;

    { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:
		
  	  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header 
	  files generated for C++. }
	  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
var
  ERR_load_EC_strings: function : TIdC_INT; cdecl = nil;

{$ELSE}
  function ERR_load_EC_strings: TIdC_INT cdecl; external CLibCrypto;

{$ENDIF}

implementation

  uses
    classes, 
    TaurusTLSExceptionHandlers
  {$IFNDEF OPENSSL_STATIC_LINK_MODEL}
    ,TaurusTLSLoader
  {$ENDIF};
  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
const
  ERR_load_EC_strings_procname = 'ERR_load_EC_strings';

  {$IFNDEF _FIXINSIGHT_}
  {$I TaurusTLSNoRetValOff.inc} 
function  ERR_ERR_load_EC_strings: TIdC_INT; cdecl;
begin
  ETaurusTLSAPIFunctionNotPresent.RaiseException(ERR_load_EC_strings_procname);
end;



  {$I TaurusTLSNoRetValOn.inc} 
  {$I TaurusTLSUnusedParamOff.inc}
procedure Load(const ADllHandle: TIdLibHandle; LibVersion: TIdC_UINT; const AFailed: TStringList);

var FuncLoadError: boolean;

begin
  ERR_load_EC_strings := LoadLibFunction(ADllHandle, ERR_load_EC_strings_procname);
  FuncLoadError := not assigned(ERR_load_EC_strings);
  if FuncLoadError then
  begin
    {$if not defined(ERR_load_EC_strings_allownil)}
    ERR_load_EC_strings := ERR_ERR_load_EC_strings;
    {$ifend}
    {$if declared(ERR_load_EC_strings_introduced)}
    if LibVersion < ERR_load_EC_strings_introduced then
    begin
      {$if declared(FC_ERR_load_EC_strings)}
      ERR_load_EC_strings := FC_ERR_load_EC_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if declared(ERR_load_EC_strings_removed)}
    if ERR_load_EC_strings_removed <= LibVersion then
    begin
      {$if declared(_ERR_load_EC_strings)}
      ERR_load_EC_strings := _ERR_load_EC_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if not defined(ERR_load_EC_strings_allownil)}
    if FuncLoadError then
      AFailed.Add('ERR_load_EC_strings');
    {$ifend}
  end;
end;
  {$I TaurusTLSUnusedParamOn.inc}

procedure Unload;
begin
  ERR_load_EC_strings := nil;
end;
  {$ENDIF}
{$ELSE}
{$ENDIF}

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
initialization
  Register_SSLLoader(Load,'LibCrypto');
  Register_SSLUnloader(Unload);
{$ENDIF}
end.
