/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_tserr.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_tserr.h2pas
     and this file regenerated. TaurusTLSHeaders_tserr.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_tserr;

interface

// Headers for OpenSSL 1.1.1
// tserr.h


uses
  IdCTypes,
  IdGlobal
  {$IFDEF OPENSSL_STATIC_LINK_MODEL}
  , TaurusTLSConsts
  {$ENDIF};

const
  (*
   * TS function codes.
   *)
  {$EXTERNALSYM TS_F_DEF_SERIAL_CB}
  TS_F_DEF_SERIAL_CB = 110;
  {$EXTERNALSYM TS_F_DEF_TIME_CB}
  TS_F_DEF_TIME_CB = 111;
  {$EXTERNALSYM TS_F_ESS_ADD_SIGNING_CERT}
  TS_F_ESS_ADD_SIGNING_CERT = 112;
  {$EXTERNALSYM TS_F_ESS_ADD_SIGNING_CERT_V2}
  TS_F_ESS_ADD_SIGNING_CERT_V2 = 147;
  {$EXTERNALSYM TS_F_ESS_CERT_ID_NEW_INIT}
  TS_F_ESS_CERT_ID_NEW_INIT = 113;
  {$EXTERNALSYM TS_F_ESS_CERT_ID_V2_NEW_INIT}
  TS_F_ESS_CERT_ID_V2_NEW_INIT = 156;
  {$EXTERNALSYM TS_F_ESS_SIGNING_CERT_NEW_INIT}
  TS_F_ESS_SIGNING_CERT_NEW_INIT = 114;
  {$EXTERNALSYM TS_F_ESS_SIGNING_CERT_V2_NEW_INIT}
  TS_F_ESS_SIGNING_CERT_V2_NEW_INIT = 157;
  {$EXTERNALSYM TS_F_INT_TS_RESP_VERIFY_TOKEN}
  TS_F_INT_TS_RESP_VERIFY_TOKEN = 149;
  {$EXTERNALSYM TS_F_PKCS7_TO_TS_TST_INFO}
  TS_F_PKCS7_TO_TS_TST_INFO = 148;
  {$EXTERNALSYM TS_F_TS_ACCURACY_SET_MICROS}
  TS_F_TS_ACCURACY_SET_MICROS = 115;
  {$EXTERNALSYM TS_F_TS_ACCURACY_SET_MILLIS}
  TS_F_TS_ACCURACY_SET_MILLIS = 116;
  {$EXTERNALSYM TS_F_TS_ACCURACY_SET_SECONDS}
  TS_F_TS_ACCURACY_SET_SECONDS = 117;
  {$EXTERNALSYM TS_F_TS_CHECK_IMPRINTS}
  TS_F_TS_CHECK_IMPRINTS = 100;
  {$EXTERNALSYM TS_F_TS_CHECK_NONCES}
  TS_F_TS_CHECK_NONCES = 101;
  {$EXTERNALSYM TS_F_TS_CHECK_POLICY}
  TS_F_TS_CHECK_POLICY = 102;
  {$EXTERNALSYM TS_F_TS_CHECK_SIGNING_CERTS}
  TS_F_TS_CHECK_SIGNING_CERTS = 103;
  {$EXTERNALSYM TS_F_TS_CHECK_STATUS_INFO}
  TS_F_TS_CHECK_STATUS_INFO = 104;
  {$EXTERNALSYM TS_F_TS_COMPUTE_IMPRINT}
  TS_F_TS_COMPUTE_IMPRINT = 145;
  {$EXTERNALSYM TS_F_TS_CONF_INVALID}
  TS_F_TS_CONF_INVALID = 151;
  {$EXTERNALSYM TS_F_TS_CONF_LOAD_CERT}
  TS_F_TS_CONF_LOAD_CERT = 153;
  {$EXTERNALSYM TS_F_TS_CONF_LOAD_CERTS}
  TS_F_TS_CONF_LOAD_CERTS = 154;
  {$EXTERNALSYM TS_F_TS_CONF_LOAD_KEY}
  TS_F_TS_CONF_LOAD_KEY = 155;
  {$EXTERNALSYM TS_F_TS_CONF_LOOKUP_FAIL}
  TS_F_TS_CONF_LOOKUP_FAIL = 152;
  {$EXTERNALSYM TS_F_TS_CONF_SET_DEFAULT_ENGINE}
  TS_F_TS_CONF_SET_DEFAULT_ENGINE = 146;
  {$EXTERNALSYM TS_F_TS_GET_STATUS_TEXT}
  TS_F_TS_GET_STATUS_TEXT = 105;
  {$EXTERNALSYM TS_F_TS_MSG_IMPRINT_SET_ALGO}
  TS_F_TS_MSG_IMPRINT_SET_ALGO = 118;
  {$EXTERNALSYM TS_F_TS_REQ_SET_MSG_IMPRINT}
  TS_F_TS_REQ_SET_MSG_IMPRINT = 119;
  {$EXTERNALSYM TS_F_TS_REQ_SET_NONCE}
  TS_F_TS_REQ_SET_NONCE = 120;
  {$EXTERNALSYM TS_F_TS_REQ_SET_POLICY_ID}
  TS_F_TS_REQ_SET_POLICY_ID = 121;
  {$EXTERNALSYM TS_F_TS_RESP_CREATE_RESPONSE}
  TS_F_TS_RESP_CREATE_RESPONSE = 122;
  {$EXTERNALSYM TS_F_TS_RESP_CREATE_TST_INFO}
  TS_F_TS_RESP_CREATE_TST_INFO = 123;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_ADD_FAILURE_INFO}
  TS_F_TS_RESP_CTX_ADD_FAILURE_INFO = 124;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_ADD_MD}
  TS_F_TS_RESP_CTX_ADD_MD = 125;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_ADD_POLICY}
  TS_F_TS_RESP_CTX_ADD_POLICY = 126;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_NEW}
  TS_F_TS_RESP_CTX_NEW = 127;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_SET_ACCURACY}
  TS_F_TS_RESP_CTX_SET_ACCURACY = 128;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_SET_CERTS}
  TS_F_TS_RESP_CTX_SET_CERTS = 129;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_SET_DEF_POLICY}
  TS_F_TS_RESP_CTX_SET_DEF_POLICY = 130;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_SET_SIGNER_CERT}
  TS_F_TS_RESP_CTX_SET_SIGNER_CERT = 131;
  {$EXTERNALSYM TS_F_TS_RESP_CTX_SET_STATUS_INFO}
  TS_F_TS_RESP_CTX_SET_STATUS_INFO = 132;
  {$EXTERNALSYM TS_F_TS_RESP_GET_POLICY}
  TS_F_TS_RESP_GET_POLICY = 133;
  {$EXTERNALSYM TS_F_TS_RESP_SET_GENTIME_WITH_PRECISION}
  TS_F_TS_RESP_SET_GENTIME_WITH_PRECISION = 134;
  {$EXTERNALSYM TS_F_TS_RESP_SET_STATUS_INFO}
  TS_F_TS_RESP_SET_STATUS_INFO = 135;
  {$EXTERNALSYM TS_F_TS_RESP_SET_TST_INFO}
  TS_F_TS_RESP_SET_TST_INFO = 150;
  {$EXTERNALSYM TS_F_TS_RESP_SIGN}
  TS_F_TS_RESP_SIGN = 136;
  {$EXTERNALSYM TS_F_TS_RESP_VERIFY_SIGNATURE}
  TS_F_TS_RESP_VERIFY_SIGNATURE = 106;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_ACCURACY}
  TS_F_TS_TST_INFO_SET_ACCURACY = 137;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_MSG_IMPRINT}
  TS_F_TS_TST_INFO_SET_MSG_IMPRINT = 138;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_NONCE}
  TS_F_TS_TST_INFO_SET_NONCE = 139;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_POLICY_ID}
  TS_F_TS_TST_INFO_SET_POLICY_ID = 140;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_SERIAL}
  TS_F_TS_TST_INFO_SET_SERIAL = 141;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_TIME}
  TS_F_TS_TST_INFO_SET_TIME = 142;
  {$EXTERNALSYM TS_F_TS_TST_INFO_SET_TSA}
  TS_F_TS_TST_INFO_SET_TSA = 143;
  {$EXTERNALSYM TS_F_TS_VERIFY}
  TS_F_TS_VERIFY = 108;
  {$EXTERNALSYM TS_F_TS_VERIFY_CERT}
  TS_F_TS_VERIFY_CERT = 109;
  {$EXTERNALSYM TS_F_TS_VERIFY_CTX_NEW}
  TS_F_TS_VERIFY_CTX_NEW = 144;

  (*
   * TS reason codes.
   *)
  {$EXTERNALSYM TS_R_BAD_PKCS7_TYPE}
  TS_R_BAD_PKCS7_TYPE = 132;
  {$EXTERNALSYM TS_R_BAD_TYPE}
  TS_R_BAD_TYPE = 133;
  {$EXTERNALSYM TS_R_CANNOT_LOAD_CERT}
  TS_R_CANNOT_LOAD_CERT = 137;
  {$EXTERNALSYM TS_R_CANNOT_LOAD_KEY}
  TS_R_CANNOT_LOAD_KEY = 138;
  {$EXTERNALSYM TS_R_CERTIFICATE_VERIFY_ERROR}
  TS_R_CERTIFICATE_VERIFY_ERROR = 100;
  {$EXTERNALSYM TS_R_COULD_NOT_SET_ENGINE}
  TS_R_COULD_NOT_SET_ENGINE = 127;
  {$EXTERNALSYM TS_R_COULD_NOT_SET_TIME}
  TS_R_COULD_NOT_SET_TIME = 115;
  {$EXTERNALSYM TS_R_DETACHED_CONTENT}
  TS_R_DETACHED_CONTENT = 134;
  {$EXTERNALSYM TS_R_ESS_ADD_SIGNING_CERT_ERROR}
  TS_R_ESS_ADD_SIGNING_CERT_ERROR = 116;
  {$EXTERNALSYM TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR}
  TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR = 139;
  {$EXTERNALSYM TS_R_ESS_SIGNING_CERTIFICATE_ERROR}
  TS_R_ESS_SIGNING_CERTIFICATE_ERROR = 101;
  {$EXTERNALSYM TS_R_INVALID_NULL_POINTER}
  TS_R_INVALID_NULL_POINTER = 102;
  {$EXTERNALSYM TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE}
  TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE = 117;
  {$EXTERNALSYM TS_R_MESSAGE_IMPRINT_MISMATCH}
  TS_R_MESSAGE_IMPRINT_MISMATCH = 103;
  {$EXTERNALSYM TS_R_NONCE_MISMATCH}
  TS_R_NONCE_MISMATCH = 104;
  {$EXTERNALSYM TS_R_NONCE_NOT_RETURNED}
  TS_R_NONCE_NOT_RETURNED = 105;
  {$EXTERNALSYM TS_R_NO_CONTENT}
  TS_R_NO_CONTENT = 106;
  {$EXTERNALSYM TS_R_NO_TIME_STAMP_TOKEN}
  TS_R_NO_TIME_STAMP_TOKEN = 107;
  {$EXTERNALSYM TS_R_PKCS7_ADD_SIGNATURE_ERROR}
  TS_R_PKCS7_ADD_SIGNATURE_ERROR = 118;
  {$EXTERNALSYM TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR}
  TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR = 119;
  {$EXTERNALSYM TS_R_PKCS7_TO_TS_TST_INFO_FAILED}
  TS_R_PKCS7_TO_TS_TST_INFO_FAILED = 129;
  {$EXTERNALSYM TS_R_POLICY_MISMATCH}
  TS_R_POLICY_MISMATCH = 108;
  {$EXTERNALSYM TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE}
  TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE = 120;
  {$EXTERNALSYM TS_R_RESPONSE_SETUP_ERROR}
  TS_R_RESPONSE_SETUP_ERROR = 121;
  {$EXTERNALSYM TS_R_SIGNATURE_FAILURE}
  TS_R_SIGNATURE_FAILURE = 109;
  {$EXTERNALSYM TS_R_THERE_MUST_BE_ONE_SIGNER}
  TS_R_THERE_MUST_BE_ONE_SIGNER = 110;
  {$EXTERNALSYM TS_R_TIME_SYSCALL_ERROR}
  TS_R_TIME_SYSCALL_ERROR = 122;
  {$EXTERNALSYM TS_R_TOKEN_NOT_PRESENT}
  TS_R_TOKEN_NOT_PRESENT = 130;
  {$EXTERNALSYM TS_R_TOKEN_PRESENT}
  TS_R_TOKEN_PRESENT = 131;
  {$EXTERNALSYM TS_R_TSA_NAME_MISMATCH}
  TS_R_TSA_NAME_MISMATCH = 111;
  {$EXTERNALSYM TS_R_TSA_UNTRUSTED}
  TS_R_TSA_UNTRUSTED = 112;
  {$EXTERNALSYM TS_R_TST_INFO_SETUP_ERROR}
  TS_R_TST_INFO_SETUP_ERROR = 123;
  {$EXTERNALSYM TS_R_TS_DATASIGN}
  TS_R_TS_DATASIGN = 124;
  {$EXTERNALSYM TS_R_UNACCEPTABLE_POLICY}
  TS_R_UNACCEPTABLE_POLICY = 125;
  {$EXTERNALSYM TS_R_UNSUPPORTED_MD_ALGORITHM}
  TS_R_UNSUPPORTED_MD_ALGORITHM = 126;
  {$EXTERNALSYM TS_R_UNSUPPORTED_VERSION}
  TS_R_UNSUPPORTED_VERSION = 113;
  {$EXTERNALSYM TS_R_VAR_BAD_VALUE}
  TS_R_VAR_BAD_VALUE = 135;
  {$EXTERNALSYM TS_R_VAR_LOOKUP_FAILURE}
  TS_R_VAR_LOOKUP_FAILURE = 136;
  {$EXTERNALSYM TS_R_WRONG_CONTENT_TYPE}
  TS_R_WRONG_CONTENT_TYPE = 114;

    { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:
		
  	  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header 
	  files generated for C++. }
	  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
var
  ERR_load_TS_strings: function : TIdC_INT; cdecl = nil;

{$ELSE}
  function ERR_load_TS_strings: TIdC_INT cdecl; external CLibCrypto;

{$ENDIF}

implementation

  uses
    classes, 
    TaurusTLSExceptionHandlers
  {$IFNDEF OPENSSL_STATIC_LINK_MODEL}
    ,TaurusTLSLoader
  {$ENDIF};
  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
const
  ERR_load_TS_strings_procname = 'ERR_load_TS_strings';

  {$IFNDEF _FIXINSIGHT_}
  {$I TaurusTLSNoRetValOff.inc} 
function  ERR_ERR_load_TS_strings: TIdC_INT;  cdecl;
begin
  ETaurusTLSAPIFunctionNotPresent.RaiseException(ERR_load_TS_strings_procname);
end;



  {$I TaurusTLSNoRetValOn.inc} 
  {$I TaurusTLSUnusedParamOff.inc}
procedure Load(const ADllHandle: TIdLibHandle; LibVersion: TIdC_UINT; const AFailed: TStringList);

var FuncLoadError: boolean;

begin
  ERR_load_TS_strings := LoadLibFunction(ADllHandle, ERR_load_TS_strings_procname);
  FuncLoadError := not assigned(ERR_load_TS_strings);
  if FuncLoadError then
  begin
    {$if not defined(ERR_load_TS_strings_allownil)}
    ERR_load_TS_strings := ERR_ERR_load_TS_strings;
    {$ifend}
    {$if declared(ERR_load_TS_strings_introduced)}
    if LibVersion < ERR_load_TS_strings_introduced then
    begin
      {$if declared(FC_ERR_load_TS_strings)}
      ERR_load_TS_strings := FC_ERR_load_TS_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if declared(ERR_load_TS_strings_removed)}
    if ERR_load_TS_strings_removed <= LibVersion then
    begin
      {$if declared(_ERR_load_TS_strings)}
      ERR_load_TS_strings := _ERR_load_TS_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if not defined(ERR_load_TS_strings_allownil)}
    if FuncLoadError then
      AFailed.Add('ERR_load_TS_strings');
    {$ifend}
  end;


end;

procedure Unload;
begin
  ERR_load_TS_strings := nil;
end;
  {$I TaurusTLSUnusedParamOff.inc}
  {$ENDIF}
{$ENDIF}

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
initialization
  Register_SSLLoader(Load,'LibCrypto');
  Register_SSLUnloader(Unload);
{$ENDIF}
end.
