/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_ssl3.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_ssl3.h2pas
     and this file regenerated. TaurusTLSHeaders_ssl3.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_ssl3;

interface

// Headers for OpenSSL 1.1.1
// ssl3.h


uses
  IdGlobal,
  TaurusTLSHeaders_prov_ssl
  {$IFNDEF FPC}
  , TaurusTLSHeaders_types
  {$ENDIF};

const
  (*
   * Signalling cipher suite value from RFC 5746
   * (TLS_EMPTY_RENEGOTIATION_INFO_SCSV)
   *)
  {$EXTERNALSYM SSL3_CK_SCSV}
  SSL3_CK_SCSV = $030000FF;

  (*
  * Signalling cipher suite value from draft-ietf-tls-downgrade-scsv-00
  * (TLS_FALLBACK_SCSV)
  *)
  {$EXTERNALSYM SSL3_CK_FALLBACK_SCSV}
  SSL3_CK_FALLBACK_SCSV = $03005600;

  {$EXTERNALSYM SSL3_CK_RSA_NULL_MD5}
  SSL3_CK_RSA_NULL_MD5 = $03000001;
  {$EXTERNALSYM SSL3_CK_RSA_NULL_SHA}
  SSL3_CK_RSA_NULL_SHA = $03000002;
  {$EXTERNALSYM SSL3_CK_RSA_RC4_40_MD5}
  SSL3_CK_RSA_RC4_40_MD5 = $03000003;
  {$EXTERNALSYM SSL3_CK_RSA_RC4_128_MD5}
  SSL3_CK_RSA_RC4_128_MD5 = $03000004;
  {$EXTERNALSYM SSL3_CK_RSA_RC4_128_SHA}
  SSL3_CK_RSA_RC4_128_SHA = $03000005;
  {$EXTERNALSYM SSL3_CK_RSA_RC2_40_MD5}
  SSL3_CK_RSA_RC2_40_MD5 = $03000006;
  {$EXTERNALSYM SSL3_CK_RSA_IDEA_128_SHA}
  SSL3_CK_RSA_IDEA_128_SHA = $03000007;
  {$EXTERNALSYM SSL3_CK_RSA_DES_40_CBC_SHA}
  SSL3_CK_RSA_DES_40_CBC_SHA = $03000008;
  {$EXTERNALSYM SSL3_CK_RSA_DES_64_CBC_SHA}
  SSL3_CK_RSA_DES_64_CBC_SHA = $03000009;
  {$EXTERNALSYM SSL3_CK_RSA_DES_192_CBC3_SHA}
  SSL3_CK_RSA_DES_192_CBC3_SHA = $0300000A;

  {$EXTERNALSYM SSL3_CK_DH_DSS_DES_40_CBC_SHA}
  SSL3_CK_DH_DSS_DES_40_CBC_SHA = $0300000B;
  {$EXTERNALSYM SSL3_CK_DH_DSS_DES_64_CBC_SHA}
  SSL3_CK_DH_DSS_DES_64_CBC_SHA = $0300000C;
  {$EXTERNALSYM SSL3_CK_DH_DSS_DES_192_CBC3_SHA}
  SSL3_CK_DH_DSS_DES_192_CBC3_SHA = $0300000D;
  {$EXTERNALSYM SSL3_CK_DH_RSA_DES_40_CBC_SHA}
  SSL3_CK_DH_RSA_DES_40_CBC_SHA = $0300000E;
  {$EXTERNALSYM SSL3_CK_DH_RSA_DES_64_CBC_SHA}
  SSL3_CK_DH_RSA_DES_64_CBC_SHA = $0300000F;
  {$EXTERNALSYM SSL3_CK_DH_RSA_DES_192_CBC3_SHA}
  SSL3_CK_DH_RSA_DES_192_CBC3_SHA = $03000010;

  {$EXTERNALSYM SSL3_CK_DHE_DSS_DES_40_CBC_SHA}
  SSL3_CK_DHE_DSS_DES_40_CBC_SHA = $03000011;
  {$EXTERNALSYM SSL3_CK_EDH_DSS_DES_40_CBC_SHA}
  SSL3_CK_EDH_DSS_DES_40_CBC_SHA = SSL3_CK_DHE_DSS_DES_40_CBC_SHA;
  {$EXTERNALSYM SSL3_CK_DHE_DSS_DES_64_CBC_SHA}
  SSL3_CK_DHE_DSS_DES_64_CBC_SHA = $03000012;
  {$EXTERNALSYM SSL3_CK_EDH_DSS_DES_64_CBC_SHA}
  SSL3_CK_EDH_DSS_DES_64_CBC_SHA = SSL3_CK_DHE_DSS_DES_64_CBC_SHA;
  {$EXTERNALSYM SSL3_CK_DHE_DSS_DES_192_CBC3_SHA}
  SSL3_CK_DHE_DSS_DES_192_CBC3_SHA = $03000013;
  {$EXTERNALSYM SSL3_CK_EDH_DSS_DES_192_CBC3_SHA}
  SSL3_CK_EDH_DSS_DES_192_CBC3_SHA = SSL3_CK_DHE_DSS_DES_192_CBC3_SHA;
  {$EXTERNALSYM SSL3_CK_DHE_RSA_DES_40_CBC_SHA}
  SSL3_CK_DHE_RSA_DES_40_CBC_SHA = $03000014;
  {$EXTERNALSYM SSL3_CK_EDH_RSA_DES_40_CBC_SHA}
  SSL3_CK_EDH_RSA_DES_40_CBC_SHA = SSL3_CK_DHE_RSA_DES_40_CBC_SHA;
  {$EXTERNALSYM SSL3_CK_DHE_RSA_DES_64_CBC_SHA}
  SSL3_CK_DHE_RSA_DES_64_CBC_SHA = $03000015;
  {$EXTERNALSYM SSL3_CK_EDH_RSA_DES_64_CBC_SHA}
  SSL3_CK_EDH_RSA_DES_64_CBC_SHA = SSL3_CK_DHE_RSA_DES_64_CBC_SHA;
  {$EXTERNALSYM SSL3_CK_DHE_RSA_DES_192_CBC3_SHA}
  SSL3_CK_DHE_RSA_DES_192_CBC3_SHA = $03000016;
  {$EXTERNALSYM SSL3_CK_EDH_RSA_DES_192_CBC3_SHA}
  SSL3_CK_EDH_RSA_DES_192_CBC3_SHA = SSL3_CK_DHE_RSA_DES_192_CBC3_SHA;

  {$EXTERNALSYM SSL3_CK_ADH_RC4_40_MD5}
  SSL3_CK_ADH_RC4_40_MD5 = $03000017;
  {$EXTERNALSYM SSL3_CK_ADH_RC4_128_MD5}
  SSL3_CK_ADH_RC4_128_MD5 = $03000018;
  {$EXTERNALSYM SSL3_CK_ADH_DES_40_CBC_SHA}
  SSL3_CK_ADH_DES_40_CBC_SHA = $03000019;
  {$EXTERNALSYM SSL3_CK_ADH_DES_64_CBC_SHA}
  SSL3_CK_ADH_DES_64_CBC_SHA = $0300001A;
  {$EXTERNALSYM SSL3_CK_ADH_DES_192_CBC_SHA}
  SSL3_CK_ADH_DES_192_CBC_SHA = $0300001B;

  (* a bundle of RFC standard cipher names, generated from ssl3_ciphers[] *)
  {$EXTERNALSYM SSL3_RFC_RSA_NULL_MD5}
  SSL3_RFC_RSA_NULL_MD5 = 'TLS_RSA_WITH_NULL_MD5';
  {$EXTERNALSYM SSL3_RFC_RSA_NULL_SHA}
  SSL3_RFC_RSA_NULL_SHA = 'TLS_RSA_WITH_NULL_SHA';
  {$EXTERNALSYM SSL3_RFC_RSA_DES_192_CBC3_SHA}
  SSL3_RFC_RSA_DES_192_CBC3_SHA = 'TLS_RSA_WITH_3DES_EDE_CBC_SHA';
  {$EXTERNALSYM SSL3_RFC_DHE_DSS_DES_192_CBC3_SHA}
  SSL3_RFC_DHE_DSS_DES_192_CBC3_SHA = 'TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA';
  {$EXTERNALSYM SSL3_RFC_DHE_RSA_DES_192_CBC3_SHA}
  SSL3_RFC_DHE_RSA_DES_192_CBC3_SHA = 'TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA';
  {$EXTERNALSYM SSL3_RFC_ADH_DES_192_CBC_SHA}
  SSL3_RFC_ADH_DES_192_CBC_SHA = 'TLS_DH_anon_WITH_3DES_EDE_CBC_SHA';
  {$EXTERNALSYM SSL3_RFC_RSA_IDEA_128_SHA}
  SSL3_RFC_RSA_IDEA_128_SHA = 'TLS_RSA_WITH_IDEA_CBC_SHA';
  {$EXTERNALSYM SSL3_RFC_RSA_RC4_128_MD5}
  SSL3_RFC_RSA_RC4_128_MD5 = 'TLS_RSA_WITH_RC4_128_MD5';
  {$EXTERNALSYM SSL3_RFC_RSA_RC4_128_SHA}
  SSL3_RFC_RSA_RC4_128_SHA = 'TLS_RSA_WITH_RC4_128_SHA';
  {$EXTERNALSYM SSL3_RFC_ADH_RC4_128_MD5}
  SSL3_RFC_ADH_RC4_128_MD5 = 'TLS_DH_anon_WITH_RC4_128_MD5';

  {$EXTERNALSYM SSL3_TXT_RSA_NULL_MD5}
  SSL3_TXT_RSA_NULL_MD5 = 'NULL-MD5';
  {$EXTERNALSYM SSL3_TXT_RSA_NULL_SHA}
  SSL3_TXT_RSA_NULL_SHA = 'NULL-SHA';
  {$EXTERNALSYM SSL3_TXT_RSA_RC4_40_MD5}
  SSL3_TXT_RSA_RC4_40_MD5 = 'EXP-RC4-MD5';
  {$EXTERNALSYM SSL3_TXT_RSA_RC4_128_MD5}
  SSL3_TXT_RSA_RC4_128_MD5 = 'RC4-MD5';
  {$EXTERNALSYM SSL3_TXT_RSA_RC4_128_SHA}
  SSL3_TXT_RSA_RC4_128_SHA = 'RC4-SHA';
  {$EXTERNALSYM SSL3_TXT_RSA_RC2_40_MD5}
  SSL3_TXT_RSA_RC2_40_MD5 = 'EXP-RC2-CBC-MD5';
  {$EXTERNALSYM SSL3_TXT_RSA_IDEA_128_SHA}
  SSL3_TXT_RSA_IDEA_128_SHA = 'IDEA-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_RSA_DES_40_CBC_SHA}
  SSL3_TXT_RSA_DES_40_CBC_SHA = 'EXP-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_RSA_DES_64_CBC_SHA}
  SSL3_TXT_RSA_DES_64_CBC_SHA = 'DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_RSA_DES_192_CBC3_SHA}
  SSL3_TXT_RSA_DES_192_CBC3_SHA = 'DES-CBC3-SHA';

  {$EXTERNALSYM SSL3_TXT_DH_DSS_DES_40_CBC_SHA}
  SSL3_TXT_DH_DSS_DES_40_CBC_SHA = 'EXP-DH-DSS-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DH_DSS_DES_64_CBC_SHA}
  SSL3_TXT_DH_DSS_DES_64_CBC_SHA = 'DH-DSS-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DH_DSS_DES_192_CBC3_SHA}
  SSL3_TXT_DH_DSS_DES_192_CBC3_SHA = 'DH-DSS-DES-CBC3-SHA';
  {$EXTERNALSYM SSL3_TXT_DH_RSA_DES_40_CBC_SHA}
  SSL3_TXT_DH_RSA_DES_40_CBC_SHA = 'EXP-DH-RSA-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DH_RSA_DES_64_CBC_SHA}
  SSL3_TXT_DH_RSA_DES_64_CBC_SHA = 'DH-RSA-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DH_RSA_DES_192_CBC3_SHA}
  SSL3_TXT_DH_RSA_DES_192_CBC3_SHA = 'DH-RSA-DES-CBC3-SHA';

  {$EXTERNALSYM SSL3_TXT_DHE_DSS_DES_40_CBC_SHA}
  SSL3_TXT_DHE_DSS_DES_40_CBC_SHA = 'EXP-DHE-DSS-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DHE_DSS_DES_64_CBC_SHA}
  SSL3_TXT_DHE_DSS_DES_64_CBC_SHA = 'DHE-DSS-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DHE_DSS_DES_192_CBC3_SHA}
  SSL3_TXT_DHE_DSS_DES_192_CBC3_SHA = 'DHE-DSS-DES-CBC3-SHA';
  {$EXTERNALSYM SSL3_TXT_DHE_RSA_DES_40_CBC_SHA}
  SSL3_TXT_DHE_RSA_DES_40_CBC_SHA = 'EXP-DHE-RSA-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DHE_RSA_DES_64_CBC_SHA}
  SSL3_TXT_DHE_RSA_DES_64_CBC_SHA = 'DHE-RSA-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_DHE_RSA_DES_192_CBC3_SHA}
  SSL3_TXT_DHE_RSA_DES_192_CBC3_SHA = 'DHE-RSA-DES-CBC3-SHA';

  (*
   * This next block of six 'EDH' labels is for backward compatibility with
   * older versions of TaurusTLS.  New code should use the six 'DHE' labels above
   * instead:
   *)
  {$EXTERNALSYM SSL3_TXT_EDH_DSS_DES_40_CBC_SHA}
  SSL3_TXT_EDH_DSS_DES_40_CBC_SHA = 'EXP-EDH-DSS-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_EDH_DSS_DES_64_CBC_SHA}
  SSL3_TXT_EDH_DSS_DES_64_CBC_SHA = 'EDH-DSS-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_EDH_DSS_DES_192_CBC3_SHA}
  SSL3_TXT_EDH_DSS_DES_192_CBC3_SHA = 'EDH-DSS-DES-CBC3-SHA';
  {$EXTERNALSYM SSL3_TXT_EDH_RSA_DES_40_CBC_SHA}
  SSL3_TXT_EDH_RSA_DES_40_CBC_SHA = 'EXP-EDH-RSA-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_EDH_RSA_DES_64_CBC_SHA}
  SSL3_TXT_EDH_RSA_DES_64_CBC_SHA = 'EDH-RSA-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_EDH_RSA_DES_192_CBC3_SHA}
  SSL3_TXT_EDH_RSA_DES_192_CBC3_SHA = 'EDH-RSA-DES-CBC3-SHA';

  {$EXTERNALSYM SSL3_TXT_ADH_RC4_40_MD5}
  SSL3_TXT_ADH_RC4_40_MD5 = 'EXP-ADH-RC4-MD5';
  {$EXTERNALSYM SSL3_TXT_ADH_RC4_128_MD5}
  SSL3_TXT_ADH_RC4_128_MD5 = 'ADH-RC4-MD5';
  {$EXTERNALSYM SSL3_TXT_ADH_DES_40_CBC_SHA}
  SSL3_TXT_ADH_DES_40_CBC_SHA = 'EXP-ADH-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_ADH_DES_64_CBC_SHA}
  SSL3_TXT_ADH_DES_64_CBC_SHA = 'ADH-DES-CBC-SHA';
  {$EXTERNALSYM SSL3_TXT_ADH_DES_192_CBC_SHA}
  SSL3_TXT_ADH_DES_192_CBC_SHA = 'ADH-DES-CBC3-SHA';

  {$EXTERNALSYM SSL3_SSL_SESSION_ID_LENGTH}
  SSL3_SSL_SESSION_ID_LENGTH = 32;
  {$EXTERNALSYM SSL3_MAX_SSL_SESSION_ID_LENGTH}
  SSL3_MAX_SSL_SESSION_ID_LENGTH = 32;

  {$EXTERNALSYM SSL3_MASTER_SECRET_SIZE}
  SSL3_MASTER_SECRET_SIZE = 48;
  {$EXTERNALSYM SSL3_RANDOM_SIZE}
  SSL3_RANDOM_SIZE = 32;
  {$EXTERNALSYM SSL3_SESSION_ID_SIZE}
  SSL3_SESSION_ID_SIZE = 32;
  {$EXTERNALSYM SSL3_RT_HEADER_LENGTH}
  SSL3_RT_HEADER_LENGTH = 5;

  {$EXTERNALSYM SSL3_HM_HEADER_LENGTH}
  SSL3_HM_HEADER_LENGTH = 4;

  (*
   * Some will argue that this increases memory footprint, but it's not
   * actually true. Point is that malloc has to return at least 64-bit aligned
   * pointers, meaning that allocating 5 bytes wastes 3 bytes in either case.
   * Suggested pre-gaping simply moves these wasted bytes from the end of
   * allocated region to its front, but makes data payload aligned, which
   * improves performance:-)
   *)
  {$EXTERNALSYM SSL3_ALIGN_PAYLOAD}
  SSL3_ALIGN_PAYLOAD = 8;


  (*
   * This is the maximum MAC (digest) size used by the SSL library. Currently
   * maximum of 20 is used by SHA1, but we reserve for future extension for
   * 512-bit hashes.
   *)
  {$EXTERNALSYM SSL3_RT_MAX_MD_SIZE}
  SSL3_RT_MAX_MD_SIZE = 64;

  (*
   * Maximum block size used in all ciphersuites. Currently 16 for AES.
   *)
  {$EXTERNALSYM SSL_RT_MAX_CIPHER_BLOCK_SIZE}
  SSL_RT_MAX_CIPHER_BLOCK_SIZE = 16;
  {$EXTERNALSYM SSL3_RT_MAX_EXTRA}
  SSL3_RT_MAX_EXTRA = 16384;

  (* Maximum compression overhead: defined by SSL/TLS standards *)
  {$EXTERNALSYM SSL3_RT_MAX_COMPRESSED_OVERHEAD}
  SSL3_RT_MAX_COMPRESSED_OVERHEAD = 1024;

  (*
   * The standards give a maximum encryption overhead of 1024 bytes. In
   * practice the value is lower than this. The overhead is the maximum number
   * of padding bytes (256) plus the mac size.
   *)
  {$EXTERNALSYM SSL3_RT_MAX_ENCRYPTED_OVERHEAD}
  SSL3_RT_MAX_ENCRYPTED_OVERHEAD = 256 + SSL3_RT_MAX_MD_SIZE;
  {$EXTERNALSYM SSL3_RT_MAX_TLS13_ENCRYPTED_OVERHEAD}
  SSL3_RT_MAX_TLS13_ENCRYPTED_OVERHEAD = 256;

  (*
   * TaurusTLS currently only uses a padding length of at most one block so the
   * send overhead is smaller.
   *)
  {$EXTERNALSYM SSL3_RT_SEND_MAX_ENCRYPTED_OVERHEAD}
  SSL3_RT_SEND_MAX_ENCRYPTED_OVERHEAD = SSL_RT_MAX_CIPHER_BLOCK_SIZE + SSL3_RT_MAX_MD_SIZE;

  (* If compression isn't used don't include the compression overhead *)
  {$EXTERNALSYM SSL3_RT_MAX_COMPRESSED_LENGTH}
  SSL3_RT_MAX_COMPRESSED_LENGTH = SSL3_RT_MAX_PLAIN_LENGTH;
//  SSL3_RT_MAX_COMPRESSED_LENGTH = (SSL3_RT_MAX_PLAIN_LENGTH + SSL3_RT_MAX_COMPRESSED_OVERHEAD);

  {$EXTERNALSYM SSL3_RT_MAX_ENCRYPTED_LENGTH}
  SSL3_RT_MAX_ENCRYPTED_LENGTH = SSL3_RT_MAX_ENCRYPTED_OVERHEAD + SSL3_RT_MAX_COMPRESSED_LENGTH;
  {$EXTERNALSYM SSL3_RT_MAX_TLS13_ENCRYPTED_LENGTH}
  SSL3_RT_MAX_TLS13_ENCRYPTED_LENGTH = SSL3_RT_MAX_PLAIN_LENGTH + SSL3_RT_MAX_TLS13_ENCRYPTED_OVERHEAD;
  {$EXTERNALSYM SSL3_RT_MAX_PACKET_SIZE}
  SSL3_RT_MAX_PACKET_SIZE = SSL3_RT_MAX_ENCRYPTED_LENGTH + SSL3_RT_HEADER_LENGTH;

  SSL3_MD_CLIENT_FINISHED_= TIdAnsiChar($43) + TIdAnsiChar($4C) + TIdAnsiChar($4E) + TIdAnsiChar($54);
  SSL3_MD_SERVER_FINISHED_= TIdAnsiChar($53) + TIdAnsiChar($52) + TIdAnsiChar($56) + TIdAnsiChar($52);

  {$EXTERNALSYM SSL3_VERSION}
  SSL3_VERSION = $0300;
  {$EXTERNALSYM SSL3_VERSION_MAJOR}
  SSL3_VERSION_MAJOR = $03;
  {$EXTERNALSYM SSL3_VERSION_MINOR}
  SSL3_VERSION_MINOR = $00;

  {$EXTERNALSYM SSL3_RT_CHANGE_CIPHER_SPEC}
  SSL3_RT_CHANGE_CIPHER_SPEC = 20;
  {$EXTERNALSYM SSL3_RT_ALERT}
  SSL3_RT_ALERT = 21;
  {$EXTERNALSYM SSL3_RT_HANDSHAKE}
  SSL3_RT_HANDSHAKE = 22;
  {$EXTERNALSYM SSL3_RT_APPLICATION_DATA}
  SSL3_RT_APPLICATION_DATA = 23;
  {$EXTERNALSYM DTLS1_RT_HEARTBEAT}
  DTLS1_RT_HEARTBEAT = 24;
  {$EXTERNALSYM SSL3_RT_ACK}
  SSL3_RT_ACK = 26; {* RFC 9147 *}

  (* Pseudo content types to indicate additional parameters *)
  {$EXTERNALSYM TLS1_RT_CRYPTO}
  TLS1_RT_CRYPTO = $1000;
  {$EXTERNALSYM TLS1_RT_CRYPTO_PREMASTER}
  TLS1_RT_CRYPTO_PREMASTER = TLS1_RT_CRYPTO or $1;
  {$EXTERNALSYM TLS1_RT_CRYPTO_CLIENT_RANDOM}
  TLS1_RT_CRYPTO_CLIENT_RANDOM = TLS1_RT_CRYPTO or $2;
  {$EXTERNALSYM TLS1_RT_CRYPTO_SERVER_RANDOM}
  TLS1_RT_CRYPTO_SERVER_RANDOM = TLS1_RT_CRYPTO or $3;
  {$EXTERNALSYM TLS1_RT_CRYPTO_MASTER}
  TLS1_RT_CRYPTO_MASTER = TLS1_RT_CRYPTO or $4;

  {$EXTERNALSYM TLS1_RT_CRYPTO_READ}
  TLS1_RT_CRYPTO_READ = $0000;
  {$EXTERNALSYM TLS1_RT_CRYPTO_WRITE}
  TLS1_RT_CRYPTO_WRITE = $0100;
  {$EXTERNALSYM TLS1_RT_CRYPTO_MAC}
  TLS1_RT_CRYPTO_MAC = TLS1_RT_CRYPTO or $5;
  {$EXTERNALSYM TLS1_RT_CRYPTO_KEY}
  TLS1_RT_CRYPTO_KEY = TLS1_RT_CRYPTO or $6;
  {$EXTERNALSYM TLS1_RT_CRYPTO_IV}
  TLS1_RT_CRYPTO_IV = TLS1_RT_CRYPTO or $7;
  {$EXTERNALSYM TLS1_RT_CRYPTO_FIXED_IV}
  TLS1_RT_CRYPTO_FIXED_IV = TLS1_RT_CRYPTO or $8;

  (* Pseudo content types for SSL/TLS header info *)
  {$EXTERNALSYM SSL3_RT_HEADER}
  SSL3_RT_HEADER = $100;
  {$EXTERNALSYM SSL3_RT_INNER_CONTENT_TYPE}
  SSL3_RT_INNER_CONTENT_TYPE = $101;

  //* Pseudo content types for QUIC */
  {$EXTERNALSYM SSL3_RT_QUIC_DATAGRAM}
  SSL3_RT_QUIC_DATAGRAM           = $200;
  {$EXTERNALSYM SSL3_RT_QUIC_PACKET}
  SSL3_RT_QUIC_PACKET             = $201;
  {$EXTERNALSYM SSL3_RT_QUIC_FRAME_FULL}
  SSL3_RT_QUIC_FRAME_FULL         = $202;
  {$EXTERNALSYM SSL3_RT_QUIC_FRAME_HEADER}
  SSL3_RT_QUIC_FRAME_HEADER       = $203;
  {$EXTERNALSYM SSL3_RT_QUIC_FRAME_PADDING}
  SSL3_RT_QUIC_FRAME_PADDING      = $204;

  {$EXTERNALSYM SSL3_AL_WARNING}
  SSL3_AL_WARNING = 1;
  {$EXTERNALSYM SSL3_AL_FATAL}
  SSL3_AL_FATAL = 2;

  {$EXTERNALSYM SSL3_AD_CLOSE_NOTIFY}
  SSL3_AD_CLOSE_NOTIFY = 0;
  {$EXTERNALSYM SSL3_AD_UNEXPECTED_MESSAGE}
  SSL3_AD_UNEXPECTED_MESSAGE = 10; (* fatal *)
  {$EXTERNALSYM SSL3_AD_BAD_RECORD_MAC}
  SSL3_AD_BAD_RECORD_MAC = 20; (* fatal *)
  {$EXTERNALSYM SSL3_AD_DECOMPRESSION_FAILURE}
  SSL3_AD_DECOMPRESSION_FAILURE = 30; (* fatal *)
  {$EXTERNALSYM SSL3_AD_HANDSHAKE_FAILURE}
  SSL3_AD_HANDSHAKE_FAILURE = 40; (* fatal *)
  {$EXTERNALSYM SSL3_AD_NO_CERTIFICATE}
  SSL3_AD_NO_CERTIFICATE = 41;
  {$EXTERNALSYM SSL3_AD_BAD_CERTIFICATE}
  SSL3_AD_BAD_CERTIFICATE = 42;
  {$EXTERNALSYM SSL3_AD_UNSUPPORTED_CERTIFICATE}
  SSL3_AD_UNSUPPORTED_CERTIFICATE = 43;
  {$EXTERNALSYM SSL3_AD_CERTIFICATE_REVOKED}
  SSL3_AD_CERTIFICATE_REVOKED = 44;
  {$EXTERNALSYM SSL3_AD_CERTIFICATE_EXPIRED}
  SSL3_AD_CERTIFICATE_EXPIRED = 45;
  {$EXTERNALSYM SSL3_AD_CERTIFICATE_UNKNOWN}
  SSL3_AD_CERTIFICATE_UNKNOWN = 46;
  {$EXTERNALSYM SSL3_AD_ILLEGAL_PARAMETER}
  SSL3_AD_ILLEGAL_PARAMETER = 47; (* fatal *)

  {$EXTERNALSYM TLS1_HB_REQUEST}
  TLS1_HB_REQUEST = 1;
  {$EXTERNALSYM TLS1_HB_RESPONSE}
  TLS1_HB_RESPONSE = 2;

  {$EXTERNALSYM SSL3_CT_RSA_SIGN}
  SSL3_CT_RSA_SIGN = 1;
  {$EXTERNALSYM SSL3_CT_DSS_SIGN}
  SSL3_CT_DSS_SIGN = 2;
  {$EXTERNALSYM SSL3_CT_RSA_FIXED_DH}
  SSL3_CT_RSA_FIXED_DH = 3;
  {$EXTERNALSYM SSL3_CT_DSS_FIXED_DH}
  SSL3_CT_DSS_FIXED_DH = 4;
  {$EXTERNALSYM SSL3_CT_RSA_EPHEMERAL_DH}
  SSL3_CT_RSA_EPHEMERAL_DH = 5;
  {$EXTERNALSYM SSL3_CT_DSS_EPHEMERAL_DH}
  SSL3_CT_DSS_EPHEMERAL_DH = 6;
  {$EXTERNALSYM SSL3_CT_FORTEZZA_DMS}
  SSL3_CT_FORTEZZA_DMS = 20;

  (*
   * SSL3_CT_NUMBER is used to size arrays and it must be large enough to
   * contain all of the cert types defined for *either* SSLv3 and TLSv1.
   *)
  {$EXTERNALSYM SSL3_CT_NUMBER}
  SSL3_CT_NUMBER = 10;

  (* No longer used as of TaurusTLS 1.1.1 *)
  {$EXTERNALSYM SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS}
  SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS = $0001;

  (* Removed from TaurusTLS 1.1.0 *)
  {$EXTERNALSYM TLS1_FLAGS_TLS_PADDING_BUG}
  TLS1_FLAGS_TLS_PADDING_BUG = $0;
  {$EXTERNALSYM TLS1_FLAGS_SKIP_CERT_VERIFY}
  TLS1_FLAGS_SKIP_CERT_VERIFY = $0010;

  (* Set if we encrypt then mac instead of usual mac then encrypt *)
  {$EXTERNALSYM TLS1_FLAGS_ENCRYPT_THEN_MAC_READ}
  TLS1_FLAGS_ENCRYPT_THEN_MAC_READ = $0100;
  {$EXTERNALSYM TLS1_FLAGS_ENCRYPT_THEN_MAC}
  TLS1_FLAGS_ENCRYPT_THEN_MAC = TLS1_FLAGS_ENCRYPT_THEN_MAC_READ;


  (* Set if extended master secret extension received from peer *)
  {$EXTERNALSYM TLS1_FLAGS_RECEIVED_EXTMS}
  TLS1_FLAGS_RECEIVED_EXTMS = $0200;

  {$EXTERNALSYM TLS1_FLAGS_ENCRYPT_THEN_MAC_WRITE}
  TLS1_FLAGS_ENCRYPT_THEN_MAC_WRITE = $0400;

  {$EXTERNALSYM TLS1_FLAGS_STATELESS}
  TLS1_FLAGS_STATELESS = $0800;

  {$EXTERNALSYM SSL3_MT_HELLO_REQUEST}
  SSL3_MT_HELLO_REQUEST = 0;
  {$EXTERNALSYM SSL3_MT_CLIENT_HELLO}
  SSL3_MT_CLIENT_HELLO = 1;
  {$EXTERNALSYM SSL3_MT_SERVER_HELLO}
  SSL3_MT_SERVER_HELLO = 2;
  {$EXTERNALSYM SSL3_MT_NEWSESSION_TICKET}
  SSL3_MT_NEWSESSION_TICKET = 4;
  {$EXTERNALSYM SSL3_MT_END_OF_EARLY_DATA}
  SSL3_MT_END_OF_EARLY_DATA = 5;
  {$EXTERNALSYM SSL3_MT_ENCRYPTED_EXTENSIONS}
  SSL3_MT_ENCRYPTED_EXTENSIONS = 8;
  {$EXTERNALSYM SSL3_MT_CERTIFICATE}
  SSL3_MT_CERTIFICATE = 11;
  {$EXTERNALSYM SSL3_MT_SERVER_KEY_EXCHANGE}
  SSL3_MT_SERVER_KEY_EXCHANGE = 12;
  {$EXTERNALSYM SSL3_MT_CERTIFICATE_REQUEST}
  SSL3_MT_CERTIFICATE_REQUEST = 13;
  {$EXTERNALSYM SSL3_MT_SERVER_DONE}
  SSL3_MT_SERVER_DONE = 14;
  {$EXTERNALSYM SSL3_MT_CERTIFICATE_VERIFY}
  SSL3_MT_CERTIFICATE_VERIFY = 15;
  {$EXTERNALSYM SSL3_MT_CLIENT_KEY_EXCHANGE}
  SSL3_MT_CLIENT_KEY_EXCHANGE = 16;
  {$EXTERNALSYM SSL3_MT_FINISHED}
  SSL3_MT_FINISHED = 20;
  {$EXTERNALSYM SSL3_MT_CERTIFICATE_URL}
  SSL3_MT_CERTIFICATE_URL = 21;
  {$EXTERNALSYM SSL3_MT_CERTIFICATE_STATUS}
  SSL3_MT_CERTIFICATE_STATUS = 22;
  {$EXTERNALSYM SSL3_MT_SUPPLEMENTAL_DATA}
  SSL3_MT_SUPPLEMENTAL_DATA = 23;
  {$EXTERNALSYM SSL3_MT_KEY_UPDATE}
  SSL3_MT_KEY_UPDATE = 24;
  {$EXTERNALSYM SSL3_MT_NEXT_PROTO}
  SSL3_MT_NEXT_PROTO = 67;
  {$EXTERNALSYM SSL3_MT_MESSAGE_HASH}
  SSL3_MT_MESSAGE_HASH = 254;
  {$EXTERNALSYM DTLS1_MT_HELLO_VERIFY_REQUEST}
  DTLS1_MT_HELLO_VERIFY_REQUEST = 3;

  (* Dummy message type for handling ACK like a normal handshake message *)
  {$EXTERNALSYM DTLS13_MT_ACK}
  DTLS13_MT_ACK = $0126;

  (* Dummy message type for handling CCS like a normal handshake message *)
  {$EXTERNALSYM SSL3_MT_CHANGE_CIPHER_SPEC}
  SSL3_MT_CHANGE_CIPHER_SPEC = $0101;

  {$EXTERNALSYM SSL3_MT_CCS}
  SSL3_MT_CCS = 1;

  (* These are used when changing over to a new cipher *)
  {$EXTERNALSYM SSL3_CC_READ}
  SSL3_CC_READ = $001;
  {$EXTERNALSYM SSL3_CC_WRITE}
  SSL3_CC_WRITE = $002;
  {$EXTERNALSYM SSL3_CC_CLIENT}
  SSL3_CC_CLIENT = $010;
  {$EXTERNALSYM SSL3_CC_SERVER}
  SSL3_CC_SERVER = $020;
  {$EXTERNALSYM SSL3_CC_EARLY}
  SSL3_CC_EARLY = $040;
  {$EXTERNALSYM SSL3_CC_HANDSHAKE}
  SSL3_CC_HANDSHAKE = $080;
  {$EXTERNALSYM SSL3_CC_APPLICATION}
  SSL3_CC_APPLICATION = $100;
  {$EXTERNALSYM SSL3_CC_COMP_CERT}
  SSL3_CC_COMP_CERT = $200;
  {$EXTERNALSYM SSL3_CHANGE_CIPHER_CLIENT_WRITE}
  SSL3_CHANGE_CIPHER_CLIENT_WRITE = SSL3_CC_CLIENT or SSL3_CC_WRITE;
  {$EXTERNALSYM SSL3_CHANGE_CIPHER_SERVER_READ}
  SSL3_CHANGE_CIPHER_SERVER_READ = SSL3_CC_SERVER or SSL3_CC_READ;
  {$EXTERNALSYM SSL3_CHANGE_CIPHER_CLIENT_READ}
  SSL3_CHANGE_CIPHER_CLIENT_READ = SSL3_CC_CLIENT or SSL3_CC_READ;
  {$EXTERNALSYM SSL3_CHANGE_CIPHER_SERVER_WRITE}
  SSL3_CHANGE_CIPHER_SERVER_WRITE = SSL3_CC_SERVER or SSL3_CC_WRITE;

implementation

end.
