/// <exclude />
  (* This unit was generated using the script genTaurusTLSHdrs.sh from the source file TaurusTLSHeaders_evperr.h2pas
     It should not be modified directly. All changes should be made to TaurusTLSHeaders_evperr.h2pas
     and this file regenerated. TaurusTLSHeaders_evperr.h2pas is distributed with the full Indy
     Distribution.
   *)
   
{$I TaurusTLSCompilerDefines.inc} 
{$I TaurusTLSLinkDefines.inc} 
{$IFNDEF USE_OPENSSL}
  { error Should not compile if USE_OPENSSL is not defined!!!}
{$ENDIF}
{******************************************************************************}
{*  TaurusTLS                                                                 *}
{*           https://github.com/JPeterMugaas/TaurusTLS                        *}
{*                                                                            *}
{*  Copyright (c) 2024 TaurusTLS Developers, All Rights Reserved              *}
{*                                                                            *}
{* Portions of this software are Copyright (c) 1993 – 2018,                   *}
{* Chad Z. Hower (Kudzu) and the Indy Pit Crew – http://www.IndyProject.org/  *}
{******************************************************************************}
unit TaurusTLSHeaders_evperr;

interface

// Headers for OpenSSL 1.1.1
// evperr.h


uses
  IdCTypes,
  IdGlobal
  {$IFDEF OPENSSL_STATIC_LINK_MODEL}
  , TaurusTLSConsts
  {$ENDIF};

const
  (*
   * EVP function codes.
   *)
  {$EXTERNALSYM EVP_F_AESNI_INIT_KEY}
  EVP_F_AESNI_INIT_KEY =        165;
  {$EXTERNALSYM EVP_F_AESNI_XTS_INIT_KEY}
  EVP_F_AESNI_XTS_INIT_KEY =       207;
  {$EXTERNALSYM EVP_F_AES_GCM_CTRL}
  EVP_F_AES_GCM_CTRL =         196;
  {$EXTERNALSYM EVP_F_AES_INIT_KEY}
  EVP_F_AES_INIT_KEY =         133;
  {$EXTERNALSYM EVP_F_AES_OCB_CIPHER}
  EVP_F_AES_OCB_CIPHER =        169;
  {$EXTERNALSYM EVP_F_AES_T4_INIT_KEY}
  EVP_F_AES_T4_INIT_KEY =        178;
  {$EXTERNALSYM EVP_F_AES_T4_XTS_INIT_KEY}
  EVP_F_AES_T4_XTS_INIT_KEY =       208;
  {$EXTERNALSYM EVP_F_AES_WRAP_CIPHER}
  EVP_F_AES_WRAP_CIPHER =        170;
  {$EXTERNALSYM EVP_F_AES_XTS_INIT_KEY}
  EVP_F_AES_XTS_INIT_KEY =        209;
  {$EXTERNALSYM EVP_F_ALG_MODULE_INIT}
  EVP_F_ALG_MODULE_INIT =        177;
  {$EXTERNALSYM EVP_F_ARIA_CCM_INIT_KEY}
  EVP_F_ARIA_CCM_INIT_KEY =       175;
  {$EXTERNALSYM EVP_F_ARIA_GCM_CTRL}
  EVP_F_ARIA_GCM_CTRL =        197;
  {$EXTERNALSYM EVP_F_ARIA_GCM_INIT_KEY}
  EVP_F_ARIA_GCM_INIT_KEY =       176;
  {$EXTERNALSYM EVP_F_ARIA_INIT_KEY}
  EVP_F_ARIA_INIT_KEY =        185;
  {$EXTERNALSYM EVP_F_B64_NEW}
  EVP_F_B64_NEW =          198;
  {$EXTERNALSYM EVP_F_CAMELLIA_INIT_KEY}
  EVP_F_CAMELLIA_INIT_KEY =       159;
  {$EXTERNALSYM EVP_F_CHACHA20_POLY1305_CTRL}
  EVP_F_CHACHA20_POLY1305_CTRL =      182;
  {$EXTERNALSYM EVP_F_CMLL_T4_INIT_KEY}
  EVP_F_CMLL_T4_INIT_KEY =        179;
  {$EXTERNALSYM EVP_F_DES_EDE3_WRAP_CIPHER}
  EVP_F_DES_EDE3_WRAP_CIPHER =       171;
  {$EXTERNALSYM EVP_F_DO_SIGVER_INIT}
  EVP_F_DO_SIGVER_INIT =        161;
  {$EXTERNALSYM EVP_F_ENC_NEW}
  EVP_F_ENC_NEW =          199;
  {$EXTERNALSYM EVP_F_EVP_CIPHERINIT_EX}
  EVP_F_EVP_CIPHERINIT_EX =       123;
  {$EXTERNALSYM EVP_F_EVP_CIPHER_ASN1_TO_PARAM}
  EVP_F_EVP_CIPHER_ASN1_TO_PARAM =      204;
  {$EXTERNALSYM EVP_F_EVP_CIPHER_CTX_COPY}
  EVP_F_EVP_CIPHER_CTX_COPY =       163;
  {$EXTERNALSYM EVP_F_EVP_CIPHER_CTX_CTRL}
  EVP_F_EVP_CIPHER_CTX_CTRL =       124;
  {$EXTERNALSYM EVP_F_EVP_CIPHER_CTX_SET_KEY_LENGTH}
  EVP_F_EVP_CIPHER_CTX_SET_KEY_LENGTH =    122;
  {$EXTERNALSYM EVP_F_EVP_CIPHER_PARAM_TO_ASN1}
  EVP_F_EVP_CIPHER_PARAM_TO_ASN1 =      205;
  {$EXTERNALSYM EVP_F_EVP_DECRYPTFINAL_EX}
  EVP_F_EVP_DECRYPTFINAL_EX =       101;
  {$EXTERNALSYM EVP_F_EVP_DECRYPTUPDATE}
  EVP_F_EVP_DECRYPTUPDATE =       166;
  {$EXTERNALSYM EVP_F_EVP_DIGESTFINALXOF}
  EVP_F_EVP_DIGESTFINALXOF =       174;
  {$EXTERNALSYM EVP_F_EVP_DIGESTINIT_EX}
  EVP_F_EVP_DIGESTINIT_EX =       128;
  {$EXTERNALSYM EVP_F_EVP_ENCRYPTDECRYPTUPDATE}
  EVP_F_EVP_ENCRYPTDECRYPTUPDATE =      219;
  {$EXTERNALSYM EVP_F_EVP_ENCRYPTFINAL_EX}
  EVP_F_EVP_ENCRYPTFINAL_EX =       127;
  {$EXTERNALSYM EVP_F_EVP_ENCRYPTUPDATE}
  EVP_F_EVP_ENCRYPTUPDATE =       167;
  {$EXTERNALSYM EVP_F_EVP_MD_CTX_COPY_EX}
  EVP_F_EVP_MD_CTX_COPY_EX =       110;
  {$EXTERNALSYM EVP_F_EVP_MD_SIZE}
  EVP_F_EVP_MD_SIZE =         162;
  {$EXTERNALSYM EVP_F_EVP_OPENINIT}
  EVP_F_EVP_OPENINIT =         102;
  {$EXTERNALSYM EVP_F_EVP_PBE_ALG_ADD}
  EVP_F_EVP_PBE_ALG_ADD =        115;
  {$EXTERNALSYM EVP_F_EVP_PBE_ALG_ADD_TYPE}
  EVP_F_EVP_PBE_ALG_ADD_TYPE =       160;
  {$EXTERNALSYM EVP_F_EVP_PBE_CIPHERINIT}
  EVP_F_EVP_PBE_CIPHERINIT =       116;
  {$EXTERNALSYM EVP_F_EVP_PBE_SCRYPT}
  EVP_F_EVP_PBE_SCRYPT =        181;
  {$EXTERNALSYM EVP_F_EVP_PKCS82PKEY}
  EVP_F_EVP_PKCS82PKEY =        111;
  {$EXTERNALSYM EVP_F_EVP_PKEY2PKCS8}
  EVP_F_EVP_PKEY2PKCS8 =        113;
  {$EXTERNALSYM EVP_F_EVP_PKEY_ASN1_ADD0}
  EVP_F_EVP_PKEY_ASN1_ADD0 =       188;
  {$EXTERNALSYM EVP_F_EVP_PKEY_CHECK}
  EVP_F_EVP_PKEY_CHECK =        186;
  {$EXTERNALSYM EVP_F_EVP_PKEY_COPY_PARAMETERS}
  EVP_F_EVP_PKEY_COPY_PARAMETERS =      103;
  {$EXTERNALSYM EVP_F_EVP_PKEY_CTX_CTRL}
  EVP_F_EVP_PKEY_CTX_CTRL =       137;
  {$EXTERNALSYM EVP_F_EVP_PKEY_CTX_CTRL_STR}
  EVP_F_EVP_PKEY_CTX_CTRL_STR =      150;
  {$EXTERNALSYM EVP_F_EVP_PKEY_CTX_DUP}
  EVP_F_EVP_PKEY_CTX_DUP =        156;
  {$EXTERNALSYM EVP_F_EVP_PKEY_CTX_MD}
  EVP_F_EVP_PKEY_CTX_MD =        168;
  {$EXTERNALSYM EVP_F_EVP_PKEY_DECRYPT}
  EVP_F_EVP_PKEY_DECRYPT =        104;
  {$EXTERNALSYM EVP_F_EVP_PKEY_DECRYPT_INIT}
  EVP_F_EVP_PKEY_DECRYPT_INIT =      138;
  {$EXTERNALSYM EVP_F_EVP_PKEY_DECRYPT_OLD}
  EVP_F_EVP_PKEY_DECRYPT_OLD =       151;
  {$EXTERNALSYM EVP_F_EVP_PKEY_DERIVE}
  EVP_F_EVP_PKEY_DERIVE =        153;
  {$EXTERNALSYM EVP_F_EVP_PKEY_DERIVE_INIT}
  EVP_F_EVP_PKEY_DERIVE_INIT =       154;
  {$EXTERNALSYM EVP_F_EVP_PKEY_DERIVE_SET_PEER}
  EVP_F_EVP_PKEY_DERIVE_SET_PEER =      155;
  {$EXTERNALSYM EVP_F_EVP_PKEY_ENCRYPT}
  EVP_F_EVP_PKEY_ENCRYPT =        105;
  {$EXTERNALSYM EVP_F_EVP_PKEY_ENCRYPT_INIT}
  EVP_F_EVP_PKEY_ENCRYPT_INIT =      139;
  {$EXTERNALSYM EVP_F_EVP_PKEY_ENCRYPT_OLD}
  EVP_F_EVP_PKEY_ENCRYPT_OLD =       152;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_DH}
  EVP_F_EVP_PKEY_GET0_DH =        119;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_DSA}
  EVP_F_EVP_PKEY_GET0_DSA =       120;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_EC_KEY}
  EVP_F_EVP_PKEY_GET0_EC_KEY =       131;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_HMAC}
  EVP_F_EVP_PKEY_GET0_HMAC =       183;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_POLY1305}
  EVP_F_EVP_PKEY_GET0_POLY1305 =      184;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_RSA}
  EVP_F_EVP_PKEY_GET0_RSA =       121;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET0_SIPHASH}
  EVP_F_EVP_PKEY_GET0_SIPHASH =      172;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET_RAW_PRIVATE_KEY}
  EVP_F_EVP_PKEY_GET_RAW_PRIVATE_KEY =     202;
  {$EXTERNALSYM EVP_F_EVP_PKEY_GET_RAW_PUBLIC_KEY}
  EVP_F_EVP_PKEY_GET_RAW_PUBLIC_KEY =     203;
  {$EXTERNALSYM EVP_F_EVP_PKEY_KEYGEN}
  EVP_F_EVP_PKEY_KEYGEN =        146;
  {$EXTERNALSYM EVP_F_EVP_PKEY_KEYGEN_INIT}
  EVP_F_EVP_PKEY_KEYGEN_INIT =       147;
  {$EXTERNALSYM EVP_F_EVP_PKEY_METH_ADD0}
  EVP_F_EVP_PKEY_METH_ADD0 =       194;
  {$EXTERNALSYM EVP_F_EVP_PKEY_METH_NEW}
  EVP_F_EVP_PKEY_METH_NEW =       195;
  {$EXTERNALSYM EVP_F_EVP_PKEY_NEW}
  EVP_F_EVP_PKEY_NEW =         106;
  {$EXTERNALSYM EVP_F_EVP_PKEY_NEW_CMAC_KEY}
  EVP_F_EVP_PKEY_NEW_CMAC_KEY =      193;
  {$EXTERNALSYM EVP_F_EVP_PKEY_NEW_RAW_PRIVATE_KEY}
  EVP_F_EVP_PKEY_NEW_RAW_PRIVATE_KEY =     191;
  {$EXTERNALSYM EVP_F_EVP_PKEY_NEW_RAW_PUBLIC_KEY}
  EVP_F_EVP_PKEY_NEW_RAW_PUBLIC_KEY =     192;
  {$EXTERNALSYM EVP_F_EVP_PKEY_PARAMGEN}
  EVP_F_EVP_PKEY_PARAMGEN =       148;
  {$EXTERNALSYM EVP_F_EVP_PKEY_PARAMGEN_INIT}
  EVP_F_EVP_PKEY_PARAMGEN_INIT =      149;
  {$EXTERNALSYM EVP_F_EVP_PKEY_PARAM_CHECK}
  EVP_F_EVP_PKEY_PARAM_CHECK =       189;
  {$EXTERNALSYM EVP_F_EVP_PKEY_PUBLIC_CHECK}
  EVP_F_EVP_PKEY_PUBLIC_CHECK =      190;
  {$EXTERNALSYM EVP_F_EVP_PKEY_SET1_ENGINE}
  EVP_F_EVP_PKEY_SET1_ENGINE =       187;
  {$EXTERNALSYM EVP_F_EVP_PKEY_SET_ALIAS_TYPE}
  EVP_F_EVP_PKEY_SET_ALIAS_TYPE =      206;
  {$EXTERNALSYM EVP_F_EVP_PKEY_SIGN}
  EVP_F_EVP_PKEY_SIGN =        140;
  {$EXTERNALSYM EVP_F_EVP_PKEY_SIGN_INIT}
  EVP_F_EVP_PKEY_SIGN_INIT =       141;
  {$EXTERNALSYM EVP_F_EVP_PKEY_VERIFY}
  EVP_F_EVP_PKEY_VERIFY =        142;
  {$EXTERNALSYM EVP_F_EVP_PKEY_VERIFY_INIT}
  EVP_F_EVP_PKEY_VERIFY_INIT =       143;
  {$EXTERNALSYM EVP_F_EVP_PKEY_VERIFY_RECOVER}
  EVP_F_EVP_PKEY_VERIFY_RECOVER =      144;
  {$EXTERNALSYM EVP_F_EVP_PKEY_VERIFY_RECOVER_INIT}
  EVP_F_EVP_PKEY_VERIFY_RECOVER_INIT =     145;
  {$EXTERNALSYM EVP_F_EVP_SIGNFINAL}
  EVP_F_EVP_SIGNFINAL =        107;
  {$EXTERNALSYM EVP_F_EVP_VERIFYFINAL}
  EVP_F_EVP_VERIFYFINAL =        108;
  {$EXTERNALSYM EVP_F_INT_CTX_NEW}
  EVP_F_INT_CTX_NEW =         157;
  {$EXTERNALSYM EVP_F_OK_NEW}
  EVP_F_OK_NEW =          200;
  {$EXTERNALSYM EVP_F_PKCS5_PBE_KEYIVGEN}
  EVP_F_PKCS5_PBE_KEYIVGEN =       117;
  {$EXTERNALSYM EVP_F_PKCS5_V2_PBE_KEYIVGEN}
  EVP_F_PKCS5_V2_PBE_KEYIVGEN =      118;
  {$EXTERNALSYM EVP_F_PKCS5_V2_PBKDF2_KEYIVGEN}
  EVP_F_PKCS5_V2_PBKDF2_KEYIVGEN =      164;
  {$EXTERNALSYM EVP_F_PKCS5_V2_SCRYPT_KEYIVGEN}
  EVP_F_PKCS5_V2_SCRYPT_KEYIVGEN =      180;
  {$EXTERNALSYM EVP_F_PKEY_SET_TYPE}
  EVP_F_PKEY_SET_TYPE =        158;
  {$EXTERNALSYM EVP_F_RC2_MAGIC_TO_METH}
  EVP_F_RC2_MAGIC_TO_METH =       109;
  {$EXTERNALSYM EVP_F_RC5_CTRL}
  EVP_F_RC5_CTRL =          125;
  {$EXTERNALSYM EVP_F_R_32_12_16_INIT_KEY}
  EVP_F_R_32_12_16_INIT_KEY =       242;
  {$EXTERNALSYM EVP_F_S390X_AES_GCM_CTRL}
  EVP_F_S390X_AES_GCM_CTRL =       201;
  {$EXTERNALSYM EVP_F_UPDATE}
  EVP_F_UPDATE =          173;

  (*
   * EVP reason codes.
   *)
  {$EXTERNALSYM EVP_R_AES_KEY_SETUP_FAILED}
  EVP_R_AES_KEY_SETUP_FAILED = 143;
  {$EXTERNALSYM EVP_R_ARIA_KEY_SETUP_FAILED}
  EVP_R_ARIA_KEY_SETUP_FAILED = 176;
  {$EXTERNALSYM EVP_R_BAD_DECRYPT}
  EVP_R_BAD_DECRYPT = 100;
  {$EXTERNALSYM EVP_R_BAD_KEY_LENGTH}
  EVP_R_BAD_KEY_LENGTH = 195;
  {$EXTERNALSYM EVP_R_BUFFER_TOO_SMALL}
  EVP_R_BUFFER_TOO_SMALL = 155;
  {$EXTERNALSYM EVP_R_CAMELLIA_KEY_SETUP_FAILED}
  EVP_R_CAMELLIA_KEY_SETUP_FAILED = 157;
  {$EXTERNALSYM EVP_R_CIPHER_PARAMETER_ERROR}
  EVP_R_CIPHER_PARAMETER_ERROR = 122;
  {$EXTERNALSYM EVP_R_COMMAND_NOT_SUPPORTED}
  EVP_R_COMMAND_NOT_SUPPORTED = 147;
  {$EXTERNALSYM EVP_R_COPY_ERROR}
  EVP_R_COPY_ERROR = 173;
  {$EXTERNALSYM EVP_R_CTRL_NOT_IMPLEMENTED}
  EVP_R_CTRL_NOT_IMPLEMENTED = 132;
  {$EXTERNALSYM EVP_R_CTRL_OPERATION_NOT_IMPLEMENTED}
  EVP_R_CTRL_OPERATION_NOT_IMPLEMENTED = 133;
  {$EXTERNALSYM EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH}
  EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH = 138;
  {$EXTERNALSYM EVP_R_DECODE_ERROR}
  EVP_R_DECODE_ERROR = 114;
  {$EXTERNALSYM EVP_R_DIFFERENT_KEY_TYPES}
  EVP_R_DIFFERENT_KEY_TYPES = 101;
  {$EXTERNALSYM EVP_R_DIFFERENT_PARAMETERS}
  EVP_R_DIFFERENT_PARAMETERS = 153;
  {$EXTERNALSYM EVP_R_ERROR_LOADING_SECTION}
  EVP_R_ERROR_LOADING_SECTION = 165;
  {$EXTERNALSYM EVP_R_ERROR_SETTING_FIPS_MODE}
  EVP_R_ERROR_SETTING_FIPS_MODE = 166;
  {$EXTERNALSYM EVP_R_EXPECTING_AN_HMAC_KEY}
  EVP_R_EXPECTING_AN_HMAC_KEY = 174;
  {$EXTERNALSYM EVP_R_EXPECTING_AN_RSA_KEY}
  EVP_R_EXPECTING_AN_RSA_KEY = 127;
  {$EXTERNALSYM EVP_R_EXPECTING_A_DH_KEY}
  EVP_R_EXPECTING_A_DH_KEY = 128;
  {$EXTERNALSYM EVP_R_EXPECTING_A_DSA_KEY}
  EVP_R_EXPECTING_A_DSA_KEY = 129;
  {$EXTERNALSYM EVP_R_EXPECTING_A_EC_KEY}
  EVP_R_EXPECTING_A_EC_KEY = 142;
  {$EXTERNALSYM EVP_R_EXPECTING_A_POLY1305_KEY}
  EVP_R_EXPECTING_A_POLY1305_KEY = 164;
  {$EXTERNALSYM EVP_R_EXPECTING_A_SIPHASH_KEY}
  EVP_R_EXPECTING_A_SIPHASH_KEY = 175;
  {$EXTERNALSYM EVP_R_FIPS_MODE_NOT_SUPPORTED}
  EVP_R_FIPS_MODE_NOT_SUPPORTED = 167;
  {$EXTERNALSYM EVP_R_GET_RAW_KEY_FAILED}
  EVP_R_GET_RAW_KEY_FAILED = 182;
  {$EXTERNALSYM EVP_R_ILLEGAL_SCRYPT_PARAMETERS}
  EVP_R_ILLEGAL_SCRYPT_PARAMETERS = 171;
  {$EXTERNALSYM EVP_R_INITIALIZATION_ERROR}
  EVP_R_INITIALIZATION_ERROR = 134;
  {$EXTERNALSYM EVP_R_INPUT_NOT_INITIALIZED}
  EVP_R_INPUT_NOT_INITIALIZED = 111;
  {$EXTERNALSYM EVP_R_INVALID_DIGEST}
  EVP_R_INVALID_DIGEST = 152;
  {$EXTERNALSYM EVP_R_INVALID_IV_LENGTH}
  EVP_R_INVALID_IV_LENGTH = 194;
  {$EXTERNALSYM EVP_R_INVALID_FIPS_MODE}
  EVP_R_INVALID_FIPS_MODE = 168;
  {$EXTERNALSYM EVP_R_INVALID_KEY}
  EVP_R_INVALID_KEY = 163;
  {$EXTERNALSYM EVP_R_INVALID_KEY_LENGTH}
  EVP_R_INVALID_KEY_LENGTH = 130;
  {$EXTERNALSYM EVP_R_INVALID_OPERATION}
  EVP_R_INVALID_OPERATION = 148;
  {$EXTERNALSYM EVP_R_KEYGEN_FAILURE}
  EVP_R_KEYGEN_FAILURE = 120;
  {$EXTERNALSYM EVP_R_KEY_SETUP_FAILED}
  EVP_R_KEY_SETUP_FAILED = 180;
  {$EXTERNALSYM EVP_R_MEMORY_LIMIT_EXCEEDED}
  EVP_R_MEMORY_LIMIT_EXCEEDED = 172;
  {$EXTERNALSYM EVP_R_MESSAGE_DIGEST_IS_NULL}
  EVP_R_MESSAGE_DIGEST_IS_NULL = 159;
  {$EXTERNALSYM EVP_R_METHOD_NOT_SUPPORTED}
  EVP_R_METHOD_NOT_SUPPORTED = 144;
  {$EXTERNALSYM EVP_R_MISSING_PARAMETERS}
  EVP_R_MISSING_PARAMETERS = 103;
  {$EXTERNALSYM EVP_R_NOT_XOF_OR_INVALID_LENGTH}
  EVP_R_NOT_XOF_OR_INVALID_LENGTH = 178;
  {$EXTERNALSYM EVP_R_NO_CIPHER_SET}
  EVP_R_NO_CIPHER_SET = 131;
  {$EXTERNALSYM EVP_R_NO_DEFAULT_DIGEST}
  EVP_R_NO_DEFAULT_DIGEST = 158;
  {$EXTERNALSYM EVP_R_NO_DIGEST_SET}
  EVP_R_NO_DIGEST_SET = 139;
  {$EXTERNALSYM EVP_R_NO_KEY_SET}
  EVP_R_NO_KEY_SET = 154;
  {$EXTERNALSYM EVP_R_NO_OPERATION_SET}
  EVP_R_NO_OPERATION_SET = 149;
  {$EXTERNALSYM EVP_R_ONLY_ONESHOT_SUPPORTED}
  EVP_R_ONLY_ONESHOT_SUPPORTED = 177;
  {$EXTERNALSYM EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE}
  EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE = 150;
  {$EXTERNALSYM EVP_R_OPERATON_NOT_INITIALIZED}
  EVP_R_OPERATON_NOT_INITIALIZED = 151;
  {$EXTERNALSYM EVP_R_PARTIALLY_OVERLAPPING}
  EVP_R_PARTIALLY_OVERLAPPING = 162;
  {$EXTERNALSYM EVP_R_PBKDF2_ERROR}
  EVP_R_PBKDF2_ERROR = 181;
  {$EXTERNALSYM EVP_R_PKEY_APPLICATION_ASN1_METHOD_ALREADY_REGISTERED}
  EVP_R_PKEY_APPLICATION_ASN1_METHOD_ALREADY_REGISTERED = 179;
  {$EXTERNALSYM EVP_R_PRIVATE_KEY_DECODE_ERROR}
  EVP_R_PRIVATE_KEY_DECODE_ERROR = 145;
  {$EXTERNALSYM EVP_R_PRIVATE_KEY_ENCODE_ERROR}
  EVP_R_PRIVATE_KEY_ENCODE_ERROR = 146;
  {$EXTERNALSYM EVP_R_PUBLIC_KEY_NOT_RSA}
  EVP_R_PUBLIC_KEY_NOT_RSA = 106;
  {$EXTERNALSYM EVP_R_UNKNOWN_CIPHER}
  EVP_R_UNKNOWN_CIPHER = 160;
  {$EXTERNALSYM EVP_R_UNKNOWN_DIGEST}
  EVP_R_UNKNOWN_DIGEST = 161;
  {$EXTERNALSYM EVP_R_UNKNOWN_OPTION}
  EVP_R_UNKNOWN_OPTION = 169;
  {$EXTERNALSYM EVP_R_UNKNOWN_PBE_ALGORITHM}
  EVP_R_UNKNOWN_PBE_ALGORITHM = 121;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_ALGORITHM}
  EVP_R_UNSUPPORTED_ALGORITHM = 156;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_CIPHER}
  EVP_R_UNSUPPORTED_CIPHER = 107;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_KEYLENGTH}
  EVP_R_UNSUPPORTED_KEYLENGTH = 123;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_KEY_DERIVATION_FUNCTION}
  EVP_R_UNSUPPORTED_KEY_DERIVATION_FUNCTION = 124;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_KEY_SIZE}
  EVP_R_UNSUPPORTED_KEY_SIZE = 108;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_NUMBER_OF_ROUNDS}
  EVP_R_UNSUPPORTED_NUMBER_OF_ROUNDS = 135;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_PRF}
  EVP_R_UNSUPPORTED_PRF = 125;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM}
  EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM = 118;
  {$EXTERNALSYM EVP_R_UNSUPPORTED_SALT_TYPE}
  EVP_R_UNSUPPORTED_SALT_TYPE = 126;
  {$EXTERNALSYM EVP_R_WRAP_MODE_NOT_ALLOWED}
  EVP_R_WRAP_MODE_NOT_ALLOWED = 170;
  {$EXTERNALSYM EVP_R_WRONG_FINAL_BLOCK_LENGTH}
  EVP_R_WRONG_FINAL_BLOCK_LENGTH = 109;
  {$EXTERNALSYM EVP_R_XTS_DUPLICATED_KEYS}
  EVP_R_XTS_DUPLICATED_KEYS = 183;

    { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:
		
  	  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header 
	  files generated for C++. }
	  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
var
  ERR_load_EVP_strings: function : TIdC_INT; cdecl = nil;

{$ELSE}
  function ERR_load_EVP_strings: TIdC_INT cdecl; external CLibCrypto;

{$ENDIF}

implementation

  uses
    classes, 
    TaurusTLSExceptionHandlers
  {$IFNDEF OPENSSL_STATIC_LINK_MODEL}
    ,TaurusTLSLoader
  {$ENDIF};
  

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
const
  ERR_load_EVP_strings_procname = 'ERR_load_EVP_strings';

  {$IFNDEF _FIXINSIGHT_}
  {$I TaurusTLSNoRetValOff.inc} 
function  ERR_ERR_load_EVP_strings: TIdC_INT; cdecl;
begin
  ETaurusTLSAPIFunctionNotPresent.RaiseException(ERR_load_EVP_strings_procname);
end;



  {$I TaurusTLSNoRetValOn.inc} 
  {$I TaurusTLSUnusedParamOff.inc}
procedure Load(const ADllHandle: TIdLibHandle; LibVersion: TIdC_UINT; const AFailed: TStringList);

var FuncLoadError: boolean;

begin
  ERR_load_EVP_strings := LoadLibFunction(ADllHandle, ERR_load_EVP_strings_procname);
  FuncLoadError := not assigned(ERR_load_EVP_strings);
  if FuncLoadError then
  begin
    {$if not defined(ERR_load_EVP_strings_allownil)}
    ERR_load_EVP_strings := ERR_ERR_load_EVP_strings;
    {$ifend}
    {$if declared(ERR_load_EVP_strings_introduced)}
    if LibVersion < ERR_load_EVP_strings_introduced then
    begin
      {$if declared(FC_ERR_load_EVP_strings)}
      ERR_load_EVP_strings := FC_ERR_load_EVP_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if declared(ERR_load_EVP_strings_removed)}
    if ERR_load_EVP_strings_removed <= LibVersion then
    begin
      {$if declared(_ERR_load_EVP_strings)}
      ERR_load_EVP_strings := _ERR_load_EVP_strings;
      {$ifend}
      FuncLoadError := false;
    end;
    {$ifend}
    {$if not defined(ERR_load_EVP_strings_allownil)}
    if FuncLoadError then
      AFailed.Add('ERR_load_EVP_strings');
    {$ifend}
  end;
end;
  {$I TaurusTLSUnusedParamOn.inc}

procedure Unload;
begin
  ERR_load_EVP_strings := nil;
end;
  {$ENDIF}
{$ELSE}
{$ENDIF}

{$IFNDEF OPENSSL_STATIC_LINK_MODEL}
initialization
  Register_SSLLoader(Load,'LibCrypto');
  Register_SSLUnloader(Unload);
{$ENDIF}
end.
