@echo off
rem Regenerates the C++Builder .hpp files for every TaurusTLS run-time unit.
rem
rem   GenerateHpp.bat <Win32|Win64|Win64x>
rem
rem Called by HppCheck.cbproj as its pre-build event, and usable on its own.
rem Needs BDS set (the IDE and rsvars.bat both set it).
rem
rem Indy is taken from, in order of preference:
rem   INDY_PATH  root of an Indy source checkout (the same variable the TaurusTLS
rem              package projects use); Indy is compiled from source, and its
rem              .hpp files are generated next to the TaurusTLS ones
rem   INDY_DCU   folder with prebuilt Indy .dcu files for this platform
rem              (set INDY_HPP too, for the C++ side). Both may contain
rem              {platform}, which is replaced by Win32, Win64 or Win64x
rem   otherwise  the Indy installed with RAD Studio
rem
rem Set HPPCHECK_STATIC=1 to check the static link model (the OpenSSL DLLs
rem bound at load time). On Windows that model can only be selected in
rem TaurusTLSCompilerDefines.inc, so the headers are generated from a copy of
rem Source with OPENSSL_USE_SHARED_LIBRARY switched on there.
rem
rem Extra dcc options can be passed in HPPCHECK_DCC_OPTIONS.
rem
rem Errors are printed as "GenerateHpp : error : ...", which MSBuild and the
rem IDE report as build errors. On a console that supports it they are also
rem shown in red, unless NO_COLOR is set.

setlocal
set "PLAT=%~1"
if "%PLAT%"=="" set PLAT=Win32
if not "%BDS%"=="" goto :have_bds
call :error "BDS is not set. Run from the IDE or a RAD Studio Command Prompt."
exit /b 2
:have_bds

set "HERE=%~dp0"
set "SRC=%HERE%..\..\Source"
set "DPK=%HERE%..\..\Packages\d13\TaurusTLS_RT.dpk"
set "OUT=%HERE%gen\%PLAT%"
set DCC=

if /i "%PLAT%"=="Win32"  (set "DCC=dcc32" & set "LIBPLAT=win32" & set "JF=")
if /i "%PLAT%"=="Win64"  (set "DCC=dcc64" & set "LIBPLAT=win64" & set "JF=")
if /i "%PLAT%"=="Win64x" (set "DCC=dcc64" & set "LIBPLAT=win64x" & set "JF=-JF:COFFI")
if not "%DCC%"=="" goto :have_dcc
call :error "Unsupported platform %PLAT%. Use Win32, Win64 or Win64x."
exit /b 2
:have_dcc

set INDY=
if not "%INDY_PATH%"=="" (
  set "INDY=%INDY_PATH%\Lib\System;%INDY_PATH%\Lib\Core;%INDY_PATH%\Lib\Protocols"
) else if not "%INDY_DCU%"=="" (
  call set "INDY=%%INDY_DCU:{platform}=%PLAT%%%"
)

if exist "%OUT%" rmdir /s /q "%OUT%"
mkdir "%OUT%\dcu" "%OUT%\hpp" "%OUT%\obj" "%OUT%\bin"

set "MODEL=dynamic"
if not "%HPPCHECK_STATIC%"=="1" goto :model_done
set "MODEL=static"
xcopy /e /i /q "%SRC%" "%OUT%\src" >nul
if errorlevel 1 exit /b 1
set "SRC=%OUT%\src"
rem The sources are cp1252, so read and write them with that encoding.
powershell -NoProfile -Command "$f = '%SRC%\TaurusTLSCompilerDefines.inc'; $e = [Text.Encoding]::GetEncoding(1252); $t = [IO.File]::ReadAllText($f, $e); $n = $t.Replace('{/$DEFINE OPENSSL_USE_SHARED_LIBRARY}', '{$DEFINE OPENSSL_USE_SHARED_LIBRARY}'); if ($n -eq $t) { exit 1 }; [IO.File]::WriteAllText($f, $n, $e)"
if not errorlevel 1 goto :model_done
call :error "Could not switch on OPENSSL_USE_SHARED_LIBRARY in TaurusTLSCompilerDefines.inc."
exit /b 1
:model_done

rem Take the unit list from the run-time package, so new units are picked up
rem automatically. Writes a program that uses them all, and a header that
rem includes all of their .hpp files.
> "%OUT%\HppGen.dpr" echo program HppGen;
>> "%OUT%\HppGen.dpr" echo uses
> "%OUT%\TaurusTLSAll.h" echo // Generated by GenerateHpp.bat - includes every TaurusTLS run-time unit.
set COUNT=0
for /f "tokens=1" %%U in ('findstr /r /c:"^ *[A-Za-z_][A-Za-z0-9_.]* in '" "%DPK%"') do (
  >> "%OUT%\HppGen.dpr" echo   %%U,
  >> "%OUT%\TaurusTLSAll.h" echo #include "%%U.hpp"
  set /a COUNT+=1
)
>> "%OUT%\HppGen.dpr" echo   System.SysUtils;
>> "%OUT%\HppGen.dpr" echo begin
>> "%OUT%\HppGen.dpr" echo end.
if not %COUNT%==0 goto :have_units
call :error "Found no units in %DPK%."
exit /b 1
:have_units

set "INDYSHOW=%INDY%"
if "%INDY%"=="" set "INDYSHOW=RAD Studio's lib\%LIBPLAT%\release"
echo GenerateHpp: %PLAT%, %COUNT% units, %MODEL% link model, Indy from %INDYSHOW%
"%BDS%\bin\%DCC%.exe" -B -Q -W- -H- -JPHNE %JF% --no-config ^
  -NS"System;Winapi;System.Win" ^
  -U"%BDS%\lib\%LIBPLAT%\release;%INDY%;%SRC%;%SRC%\Extra" ^
  -I"%SRC%;%INDY%" ^
  -N0"%OUT%\dcu" -NH"%OUT%\hpp" -NO"%OUT%\obj" -E"%OUT%\bin" ^
  %HPPCHECK_DCC_OPTIONS% "%OUT%\HppGen.dpr"
if not errorlevel 1 exit /b 0
call :error "dcc failed. If it cannot find the Id* units, set INDY_PATH, or INDY_DCU and INDY_HPP, to point at your Indy."
exit /b 1

:error
rem Prints %1 as a build error, in red when the output is a console that
rem supports escape sequences. Under MSBuild the output is never a console.
set "ERRLINE=GenerateHpp : error : %~1"
if defined NO_COLOR goto :error_plain
powershell -NoProfile -Command "if ([Console]::IsOutputRedirected -or -not $Host.UI.SupportsVirtualTerminal) { exit 1 }" 2>nul
if errorlevel 1 goto :error_plain
for /f %%E in ('echo prompt $E^| cmd') do set "ESC=%%E"
echo %ESC%[31m%ERRLINE%%ESC%[0m
exit /b 0
:error_plain
echo %ERRLINE%
exit /b 0
