// Checks that the C++Builder headers generated from the TaurusTLS sources
// compile, and that symbols C++Builder code needs are declared in them.
// See README.md.
//
// Every check is resolved at compile time and nothing is called, so this
// program does not need to link against TaurusTLS or Indy.

#include <cstdio>
#include <iostream>
#include <tchar.h>

#include <System.hpp>

// Generated by GenerateHpp.bat (the project's pre-build event): includes the
// .hpp of every unit in the TaurusTLS run-time package.
#include "TaurusTLSAll.h"

#define REQUIRE_TYPE(T)   static_assert(sizeof(T*) != 0, "missing type " #T)
#define REQUIRE_SYMBOL(S) static_assert(sizeof(&(S)) != 0, "missing symbol " #S)

// If implicit namespace use is disabled, use aliases to keep code clean without explicit namespace use
// For each new name, also add a `using` line for it to this block, naming the unit that declares it.
// Otherwise only the build without implicit namespace use fails.
#pragma region no_implicit_namespace
#if defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE)
using Taurustls::TTaurusTLSIOHandlerSocket;
using Taurustls::TTaurusTLSServerIOHandler;
using Taurustls_files::TaurusTLS_SSL_load_client_CA_file;
using Taurustls_files::TaurusTLS_X509_STORE_load_locations;
using Taurustlsheaders_aes::AES_ENCRYPT_CONST;
using Taurustlsheaders_kdf::EVP_PKEY_CTX_hkdf_mode;
using Taurustlsheaders_obj_mac::NID_sha256;
using Taurustlsheaders_safestack::Tsk_OPENSSL_STRING_freefunc;
using Taurustlsheaders_sha::PSHA256_CTX;
using Taurustlsheaders_ssl::IsTaurusTLS_TLSv1_2_Available;
using Taurustlsheaders_ssl::SSL_CTX_new;
using Taurustlsheaders_ssl::SSL_CTX_set_cipher_list;
using Taurustlsheaders_ssl::SSL_CTX_set_options;
using Taurustlsheaders_ssl::SSL_ERROR_WANT_READ;
using Taurustlsheaders_ssl::SSL_OP_NO_SSLv3;
using Taurustlsheaders_ssl::TLS_method;
using Taurustlsheaders_types::PEVP_PKEY_CTX;
using Taurustlsheaders_types::PPSSL_CTX;
using Taurustlsheaders_types::PX509_STORE;
using Taurustlsheaders_types::X509_STORE;
using Taurustlsheaders_x509::PSTACK_OF_X509_NAME;
using Taurustlsheaders_x509_vfy::X509_V_OK;
#endif
#pragma end_region no_implicit_namespace

// Components, the use case from issue #241.
REQUIRE_TYPE(TTaurusTLSIOHandlerSocket);
REQUIRE_TYPE(TTaurusTLSServerIOHandler);

// Names that exist only in the Pascal translation.
REQUIRE_TYPE(PPSSL_CTX);
REQUIRE_TYPE(PSTACK_OF_X509_NAME);
REQUIRE_TYPE(PSHA256_CTX);
REQUIRE_TYPE(Tsk_OPENSSL_STRING_freefunc);
REQUIRE_SYMBOL(IsTaurusTLS_TLSv1_2_Available);
static_assert(AES_ENCRYPT_CONST == 1, "AES_ENCRYPT_CONST");

// OpenSSL types and functions, and TaurusTLS routines that use them.
REQUIRE_TYPE(X509_STORE);
REQUIRE_TYPE(PX509_STORE);
REQUIRE_TYPE(PEVP_PKEY_CTX);
REQUIRE_SYMBOL(TLS_method);
REQUIRE_SYMBOL(SSL_CTX_new);
REQUIRE_SYMBOL(SSL_CTX_set_cipher_list);
REQUIRE_SYMBOL(TaurusTLS_SSL_load_client_CA_file);
REQUIRE_SYMBOL(TaurusTLS_X509_STORE_load_locations);
REQUIRE_SYMBOL(EVP_PKEY_CTX_hkdf_mode);

// Names that OpenSSL defines as macros. The values also check the Pascal
// translation against OpenSSL.
REQUIRE_SYMBOL(SSL_CTX_set_options);
static_assert(SSL_OP_NO_SSLv3 == 0x02000000, "SSL_OP_NO_SSLv3");
static_assert(NID_sha256 == 672, "NID_sha256");
static_assert(SSL_ERROR_WANT_READ == 2, "SSL_ERROR_WANT_READ");
static_assert(X509_V_OK == 0, "X509_V_OK");
// Also declared in TaurusTLSHeaders_prov_ssl, so it must be qualified.
static_assert(Taurustlsheaders_tls1::TLS1_2_VERSION == 0x0303, "TLS1_2_VERSION");

int _tmain(int /*argc*/, _TCHAR* /*argv*/[])
{
#if defined(_WIN64)
  const char *platform = "Win64";
#else
  const char *platform = "Win32";
#endif
  std::printf("TaurusTLS C++Builder header check passed (%s).\n", platform);
  return 0;
}
